// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 826eadcfe2264c6d "Mantra Lingua", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'yue'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop1' | 'Desktop2' | 'Desktop3' | 'Desktop4' | 'Desktop - Video' | 'Mobile 1' | 'Mobile 2' | 'Mobile 3' | 'Mobile 4' | 'Mobile - Video' // Variant
 * image1?: {src: string, srcSet?: string, alt?: string} // Image1
 * image2?: {src: string, srcSet?: string, alt?: string} // Image2
 * image3?: {src: string, srcSet?: string, alt?: string} // Image3
 * image4?: {src: string, srcSet?: string, alt?: string} // Image4
 * imageVideo?: {src: string, srcSet?: string, alt?: string} // Image Video
 * videoURL?: string // Video URL
}} Props

 */
import { Youtube } from "../chunks/chunk-ZCHDBUUA.js";
import "../chunks/chunk-NUFRM6SI.js";
import "../chunks/chunk-KL3BYY5R.js";
import { routes } from "../chunks/chunk-74LWP5VC.js";

// virtual:product-page/product-image
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/3envnBY6fIvbVxH1YGcq/G5Oym8RbuDhtBIp7Nc0K/tp4Kaxcmd.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getLoadingLazyAtYPosition,
	Image,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var YouTubeFonts = getFonts(Youtube);
var cycleOrder = [
	"s1ONweXGT",
	"eeFrNHiVk",
	"saIUKax4u",
	"H7K23EGHP",
	"ZvGlI3KKF",
	"wFN1Jul_Y",
	"fXDGUhWJc",
	"Jr1xBuoZR",
	"Eff06zvGR",
	"eCkwqOzn0",
];
var serializationHash = "framer-dGWdb";
var variantClassNames = {
	eCkwqOzn0: "framer-v-l6ph4u",
	eeFrNHiVk: "framer-v-3mew8r",
	Eff06zvGR: "framer-v-bbhyg",
	fXDGUhWJc: "framer-v-1y0moxl",
	H7K23EGHP: "framer-v-1jx7erh",
	Jr1xBuoZR: "framer-v-1ss58ag",
	s1ONweXGT: "framer-v-hr14di",
	saIUKax4u: "framer-v-a4e5pz",
	wFN1Jul_Y: "framer-v-111x1sn",
	ZvGlI3KKF: "framer-v-29poes",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transition2 = {
	bounce: 0.25,
	delay: 0,
	duration: 0.45,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1.05,
	skewX: 0,
	skewY: 0,
	transition: transition2,
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop - Video": "ZvGlI3KKF",
	"Mobile - Video": "eCkwqOzn0",
	"Mobile 1": "wFN1Jul_Y",
	"Mobile 2": "fXDGUhWJc",
	"Mobile 3": "Jr1xBuoZR",
	"Mobile 4": "Eff06zvGR",
	Desktop1: "s1ONweXGT",
	Desktop2: "eeFrNHiVk",
	Desktop3: "saIUKax4u",
	Desktop4: "H7K23EGHP",
};
var getProps = ({
	height,
	id,
	image1,
	image2,
	image3,
	image4,
	imageVideo,
	videoURL,
	width,
	...props
}) => {
	return {
		...props,
		BaWCWxrWG: imageVideo ??
			props.BaWCWxrWG ?? {
				pixelHeight: 480,
				pixelWidth: 480,
				src: "https://framerusercontent.com/images/9c3b2KgMhKtlS5vXwTbyHVZbMw.png?width=480&height=480",
			},
		dMdqsKCdd: image4 ?? props.dMdqsKCdd,
		J4_BLkspo: videoURL ?? props.J4_BLkspo,
		KRT89CsEf: image3 ?? props.KRT89CsEf,
		NDAAlnFoJ: image1 ?? props.NDAAlnFoJ,
		UVBHb43fo: image2 ?? props.UVBHb43fo,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "s1ONweXGT",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		NDAAlnFoJ,
		UVBHb43fo,
		KRT89CsEf,
		dMdqsKCdd,
		BaWCWxrWG,
		J4_BLkspo,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "s1ONweXGT",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapwqowio = activeVariantCallback(async (...args) => {
		setVariant("s1ONweXGT");
	});
	const onMouseEnterwqowio = activeVariantCallback(async (...args) => {
		setVariant("s1ONweXGT");
	});
	const onTapp5xufd = activeVariantCallback(async (...args) => {
		setVariant("wFN1Jul_Y");
	});
	const onMouseEnterp5xufd = activeVariantCallback(async (...args) => {
		setVariant("wFN1Jul_Y");
	});
	const onTappo978 = activeVariantCallback(async (...args) => {
		setVariant("eeFrNHiVk");
	});
	const onMouseEnterpo978 = activeVariantCallback(async (...args) => {
		setVariant("eeFrNHiVk");
	});
	const onTapipotge = activeVariantCallback(async (...args) => {
		setVariant("fXDGUhWJc");
	});
	const onMouseEnteripotge = activeVariantCallback(async (...args) => {
		setVariant("fXDGUhWJc");
	});
	const onTap1wuvswz = activeVariantCallback(async (...args) => {
		setVariant("saIUKax4u");
	});
	const onMouseEnter1wuvswz = activeVariantCallback(async (...args) => {
		setVariant("saIUKax4u");
	});
	const onTap1uk1as7 = activeVariantCallback(async (...args) => {
		setVariant("Jr1xBuoZR");
	});
	const onMouseEnter1uk1as7 = activeVariantCallback(async (...args) => {
		setVariant("Jr1xBuoZR");
	});
	const onTap5pf6br = activeVariantCallback(async (...args) => {
		setVariant("H7K23EGHP");
	});
	const onMouseEnter5pf6br = activeVariantCallback(async (...args) => {
		setVariant("H7K23EGHP");
	});
	const onTap1d6k2x8 = activeVariantCallback(async (...args) => {
		setVariant("Eff06zvGR");
	});
	const onMouseEnter1d6k2x8 = activeVariantCallback(async (...args) => {
		setVariant("Eff06zvGR");
	});
	const onTaps0noiq = activeVariantCallback(async (...args) => {
		setVariant("ZvGlI3KKF");
	});
	const onMouseEnters0noiq = activeVariantCallback(async (...args) => {
		setVariant("ZvGlI3KKF");
	});
	const onTap1rcrc60 = activeVariantCallback(async (...args) => {
		setVariant("eCkwqOzn0");
	});
	const onMouseEnter1rcrc60 = activeVariantCallback(async (...args) => {
		setVariant("eCkwqOzn0");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const visible = isSet(UVBHb43fo);
	const visible1 = isSet(KRT89CsEf);
	const visible2 = isSet(dMdqsKCdd);
	const visible3 = isSet(J4_BLkspo);
	const isDisplayed = () => {
		if (["ZvGlI3KKF", "eCkwqOzn0"].includes(baseVariant)) return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-hr14di",
							className,
							classNames,
						)}
						data-framer-name={"Desktop1"}
						layoutDependency={layoutDependency}
						layoutId={"s1ONweXGT"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								eCkwqOzn0: {
									"data-framer-name": "Mobile - Video",
								},
								eeFrNHiVk: {
									"data-framer-name": "Desktop2",
								},
								Eff06zvGR: {
									"data-framer-name": "Mobile 4",
								},
								fXDGUhWJc: {
									"data-framer-name": "Mobile 2",
								},
								H7K23EGHP: {
									"data-framer-name": "Desktop4",
								},
								Jr1xBuoZR: {
									"data-framer-name": "Mobile 3",
								},
								saIUKax4u: {
									"data-framer-name": "Desktop3",
								},
								wFN1Jul_Y: {
									"data-framer-name": "Mobile 1",
								},
								ZvGlI3KKF: {
									"data-framer-name": "Desktop - Video",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1a7jybm"}
							data-framer-name={"Thumbnails"}
							layoutDependency={layoutDependency}
							layoutId={"nh7d1NrUC"}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) + 0 + 0 + 0,
									),
									pixelHeight: 801,
									pixelWidth: 801,
									sizes: "128px",
									...toResponsiveImage(NDAAlnFoJ),
								}}
								className={"framer-dvrjo0"}
								data-border={true}
								data-framer-name={"Image 1"}
								data-highlight={true}
								layoutDependency={layoutDependency}
								layoutId={"VK1Q3EZ7A"}
								onMouseEnter={onMouseEnterwqowio}
								onTap={onTapwqowio}
								style={{
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-21e8d6ad-9790-4538-b4c4-088be5a50c29, rgb(198, 198, 198))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									borderBottomLeftRadius: 4,
									borderBottomRightRadius: 4,
									borderTopLeftRadius: 4,
									borderTopRightRadius: 4,
									filter: "saturate(1.15)",
									WebkitFilter: "saturate(1.15)",
								}}
								whileHover={animation}
								{...addPropertyOverrides(
									{
										eCkwqOzn0: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 0 + 218 + 0,
												),
												pixelHeight: 801,
												pixelWidth: 801,
												sizes: "128px",
												...toResponsiveImage(NDAAlnFoJ),
											},
											onMouseEnter: onMouseEnterp5xufd,
											onTap: onTapp5xufd,
										},
										Eff06zvGR: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 0 + 384 + 0,
												),
												pixelHeight: 801,
												pixelWidth: 801,
												sizes: "128px",
												...toResponsiveImage(NDAAlnFoJ),
											},
											onMouseEnter: onMouseEnterp5xufd,
											onTap: onTapp5xufd,
										},
										fXDGUhWJc: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 0 + 384 + 0,
												),
												pixelHeight: 801,
												pixelWidth: 801,
												sizes: "128px",
												...toResponsiveImage(NDAAlnFoJ),
											},
											onMouseEnter: onMouseEnterp5xufd,
											onTap: onTapp5xufd,
										},
										Jr1xBuoZR: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 0 + 384 + 0,
												),
												pixelHeight: 801,
												pixelWidth: 801,
												sizes: "128px",
												...toResponsiveImage(NDAAlnFoJ),
											},
											onMouseEnter: onMouseEnterp5xufd,
											onTap: onTapp5xufd,
										},
										wFN1Jul_Y: {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 0 + 384 + 0,
												),
												pixelHeight: 801,
												pixelWidth: 801,
												sizes: "128px",
												...toResponsiveImage(NDAAlnFoJ),
											},
											onMouseEnter: onMouseEnterp5xufd,
											onTap: onTapp5xufd,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							{visible && (
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) + 0 + 0 + 152,
										),
										pixelHeight: 1792,
										pixelWidth: 2688,
										sizes: "128px",
										...toResponsiveImage(UVBHb43fo),
									}}
									className={"framer-1291yg6"}
									data-border={true}
									data-framer-name={"Image 2"}
									data-highlight={true}
									layoutDependency={layoutDependency}
									layoutId={"wpB3lmU4F"}
									onMouseEnter={onMouseEnterpo978}
									onTap={onTappo978}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-21e8d6ad-9790-4538-b4c4-088be5a50c29, rgb(198, 198, 198))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 4,
										borderBottomRightRadius: 4,
										borderTopLeftRadius: 4,
										borderTopRightRadius: 4,
										filter: "saturate(1.15)",
										WebkitFilter: "saturate(1.15)",
									}}
									whileHover={animation}
									{...addPropertyOverrides(
										{
											eCkwqOzn0: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 218 + 0,
													),
													pixelHeight: 1792,
													pixelWidth: 2688,
													sizes: "128px",
													...toResponsiveImage(UVBHb43fo),
												},
												onMouseEnter: onMouseEnteripotge,
												onTap: onTapipotge,
											},
											Eff06zvGR: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 1792,
													pixelWidth: 2688,
													sizes: "128px",
													...toResponsiveImage(UVBHb43fo),
												},
												onMouseEnter: onMouseEnteripotge,
												onTap: onTapipotge,
											},
											fXDGUhWJc: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 1792,
													pixelWidth: 2688,
													sizes: "128px",
													...toResponsiveImage(UVBHb43fo),
												},
												onMouseEnter: onMouseEnteripotge,
												onTap: onTapipotge,
											},
											Jr1xBuoZR: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 1792,
													pixelWidth: 2688,
													sizes: "128px",
													...toResponsiveImage(UVBHb43fo),
												},
												onMouseEnter: onMouseEnteripotge,
												onTap: onTapipotge,
											},
											wFN1Jul_Y: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 1792,
													pixelWidth: 2688,
													sizes: "128px",
													...toResponsiveImage(UVBHb43fo),
												},
												onMouseEnter: onMouseEnteripotge,
												onTap: onTapipotge,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
							{visible1 && (
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) + 0 + 0 + 152,
										),
										pixelHeight: 2624,
										pixelWidth: 1856,
										sizes: "128px",
										...toResponsiveImage(KRT89CsEf),
									}}
									className={"framer-lnmo9s"}
									data-border={true}
									data-framer-name={"Image 3"}
									data-highlight={true}
									layoutDependency={layoutDependency}
									layoutId={"cgFVZ7cDv"}
									onMouseEnter={onMouseEnter1wuvswz}
									onTap={onTap1wuvswz}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-21e8d6ad-9790-4538-b4c4-088be5a50c29, rgb(198, 198, 198))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 4,
										borderBottomRightRadius: 4,
										borderTopLeftRadius: 4,
										borderTopRightRadius: 4,
										filter: "saturate(1.15)",
										WebkitFilter: "saturate(1.15)",
									}}
									whileHover={animation}
									{...addPropertyOverrides(
										{
											eCkwqOzn0: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 218 + 0,
													),
													pixelHeight: 2624,
													pixelWidth: 1856,
													sizes: "128px",
													...toResponsiveImage(KRT89CsEf),
												},
												onMouseEnter: onMouseEnter1uk1as7,
												onTap: onTap1uk1as7,
											},
											Eff06zvGR: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 2624,
													pixelWidth: 1856,
													sizes: "128px",
													...toResponsiveImage(KRT89CsEf),
												},
												onMouseEnter: onMouseEnter1uk1as7,
												onTap: onTap1uk1as7,
											},
											fXDGUhWJc: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 2624,
													pixelWidth: 1856,
													sizes: "128px",
													...toResponsiveImage(KRT89CsEf),
												},
												onMouseEnter: onMouseEnter1uk1as7,
												onTap: onTap1uk1as7,
											},
											Jr1xBuoZR: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 2624,
													pixelWidth: 1856,
													sizes: "128px",
													...toResponsiveImage(KRT89CsEf),
												},
												onMouseEnter: onMouseEnter1uk1as7,
												onTap: onTap1uk1as7,
											},
											wFN1Jul_Y: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 2624,
													pixelWidth: 1856,
													sizes: "128px",
													...toResponsiveImage(KRT89CsEf),
												},
												onMouseEnter: onMouseEnter1uk1as7,
												onTap: onTap1uk1as7,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
							{visible2 && (
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) + 0 + 0 + 152,
										),
										pixelHeight: 2624,
										pixelWidth: 1856,
										sizes: "128px",
										...toResponsiveImage(dMdqsKCdd),
									}}
									className={"framer-1my8voi"}
									data-border={true}
									data-framer-name={"Image 4"}
									data-highlight={true}
									layoutDependency={layoutDependency}
									layoutId={"AFTPDBhtQ"}
									onMouseEnter={onMouseEnter5pf6br}
									onTap={onTap5pf6br}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-21e8d6ad-9790-4538-b4c4-088be5a50c29, rgb(198, 198, 198))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 4,
										borderBottomRightRadius: 4,
										borderTopLeftRadius: 4,
										borderTopRightRadius: 4,
										filter: "saturate(1.15)",
										WebkitFilter: "saturate(1.15)",
									}}
									whileHover={animation}
									{...addPropertyOverrides(
										{
											eCkwqOzn0: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 218 + 0,
													),
													pixelHeight: 2624,
													pixelWidth: 1856,
													sizes: "128px",
													...toResponsiveImage(dMdqsKCdd),
												},
												onMouseEnter: onMouseEnter1d6k2x8,
												onTap: onTap1d6k2x8,
											},
											Eff06zvGR: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 2624,
													pixelWidth: 1856,
													sizes: "128px",
													...toResponsiveImage(dMdqsKCdd),
												},
												onMouseEnter: onMouseEnter1uk1as7,
												onTap: onTap1uk1as7,
											},
											fXDGUhWJc: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 2624,
													pixelWidth: 1856,
													sizes: "128px",
													...toResponsiveImage(dMdqsKCdd),
												},
												onMouseEnter: onMouseEnter1uk1as7,
												onTap: onTap1uk1as7,
											},
											Jr1xBuoZR: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 2624,
													pixelWidth: 1856,
													sizes: "128px",
													...toResponsiveImage(dMdqsKCdd),
												},
												onMouseEnter: onMouseEnter1uk1as7,
												onTap: onTap1uk1as7,
											},
											wFN1Jul_Y: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 2624,
													pixelWidth: 1856,
													sizes: "128px",
													...toResponsiveImage(dMdqsKCdd),
												},
												onMouseEnter: onMouseEnter1d6k2x8,
												onTap: onTap1d6k2x8,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
							{visible3 && (
								<Image
									background={{
										alt: "",
										fit: "fill",
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) + 0 + 0 + 152,
										),
										pixelHeight: 2624,
										pixelWidth: 1856,
										sizes: "128px",
										...toResponsiveImage(BaWCWxrWG),
									}}
									className={"framer-zt4v1e"}
									data-border={true}
									data-framer-name={"Image Video"}
									data-highlight={true}
									layoutDependency={layoutDependency}
									layoutId={"VzhwMp9dC"}
									onMouseEnter={onMouseEnters0noiq}
									onTap={onTaps0noiq}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-21e8d6ad-9790-4538-b4c4-088be5a50c29, rgb(198, 198, 198))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 4,
										borderBottomRightRadius: 4,
										borderTopLeftRadius: 4,
										borderTopRightRadius: 4,
										filter: "saturate(1.15)",
										WebkitFilter: "saturate(1.15)",
									}}
									whileHover={animation}
									{...addPropertyOverrides(
										{
											eCkwqOzn0: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 218 + 0,
													),
													pixelHeight: 2624,
													pixelWidth: 1856,
													sizes: "128px",
													...toResponsiveImage(BaWCWxrWG),
												},
												onMouseEnter: onMouseEnter1d6k2x8,
												onTap: onTap1d6k2x8,
											},
											Eff06zvGR: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 2624,
													pixelWidth: 1856,
													sizes: "128px",
													...toResponsiveImage(BaWCWxrWG),
												},
												onMouseEnter: onMouseEnter1uk1as7,
												onTap: onTap1uk1as7,
											},
											fXDGUhWJc: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 2624,
													pixelWidth: 1856,
													sizes: "128px",
													...toResponsiveImage(BaWCWxrWG),
												},
												onMouseEnter: onMouseEnter1uk1as7,
												onTap: onTap1uk1as7,
											},
											Jr1xBuoZR: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 2624,
													pixelWidth: 1856,
													sizes: "128px",
													...toResponsiveImage(BaWCWxrWG),
												},
												onMouseEnter: onMouseEnter1uk1as7,
												onTap: onTap1uk1as7,
											},
											wFN1Jul_Y: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 384 + 0,
													),
													pixelHeight: 2624,
													pixelWidth: 1856,
													sizes: "128px",
													...toResponsiveImage(BaWCWxrWG),
												},
												onMouseEnter: onMouseEnter1rcrc60,
												onTap: onTap1rcrc60,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
						</motion.div>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 0,
								),
								pixelHeight: 801,
								pixelWidth: 801,
								...toResponsiveImage(NDAAlnFoJ),
							}}
							className={"framer-12de1be"}
							data-border={true}
							data-framer-name={"Main Image"}
							layoutDependency={layoutDependency}
							layoutId={"sgVNvmXDD"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								borderBottomLeftRadius: 4,
								borderBottomRightRadius: 4,
								borderTopLeftRadius: 4,
								borderTopRightRadius: 4,
								boxShadow:
									"0px 0.6021873017743928px 1.8065619053231785px -1.25px rgba(0, 0, 0, 0.18), 0px 2.288533303243457px 6.8655999097303715px -2.5px rgba(0, 0, 0, 0.16), 0px 10px 30px -3.75px rgba(0, 0, 0, 0.06)",
								filter: "saturate(1.15)",
								WebkitFilter: "saturate(1.15)",
							}}
							{...addPropertyOverrides(
								{
									eCkwqOzn0: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0 + 0,
											),
											pixelHeight: 801,
											pixelWidth: 801,
											sizes: componentViewport?.width || "100vw",
											...toResponsiveImage(NDAAlnFoJ),
										},
									},
									eeFrNHiVk: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0,
											),
											pixelHeight: 801,
											pixelWidth: 801,
											...toResponsiveImage(UVBHb43fo),
										},
									},
									Eff06zvGR: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0 + 0,
											),
											pixelHeight: 801,
											pixelWidth: 801,
											sizes: componentViewport?.width || "100vw",
											...toResponsiveImage(dMdqsKCdd),
										},
									},
									fXDGUhWJc: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0 + 0,
											),
											pixelHeight: 1792,
											pixelWidth: 2688,
											sizes: componentViewport?.width || "100vw",
											...toResponsiveImage(UVBHb43fo),
										},
									},
									H7K23EGHP: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0,
											),
											pixelHeight: 801,
											pixelWidth: 801,
											...toResponsiveImage(dMdqsKCdd),
										},
									},
									Jr1xBuoZR: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0 + 0,
											),
											pixelHeight: 801,
											pixelWidth: 801,
											sizes: componentViewport?.width || "100vw",
											...toResponsiveImage(KRT89CsEf),
										},
									},
									saIUKax4u: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0,
											),
											pixelHeight: 801,
											pixelWidth: 801,
											...toResponsiveImage(KRT89CsEf),
										},
									},
									wFN1Jul_Y: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 0 + 0,
											),
											pixelHeight: 801,
											pixelWidth: 801,
											sizes: componentViewport?.width || "100vw",
											...toResponsiveImage(NDAAlnFoJ),
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							{isDisplayed() && (
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-m6iyeu-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"c871K4GPI-container"}
										nodeId={"c871K4GPI"}
										rendersWithMotion={true}
										scopeId={"tp4Kaxcmd"}
									>
										<Youtube
											borderRadius={4}
											bottomLeftRadius={4}
											bottomRightRadius={4}
											height={"100%"}
											id={"c871K4GPI"}
											isMixedBorderRadius={false}
											isRed={false}
											layoutId={"c871K4GPI"}
											play={"On"}
											shouldMute={true}
											style={{
												height: "100%",
												width: "100%",
											}}
											thumbnail={"Medium Quality"}
											topLeftRadius={4}
											topRightRadius={4}
											url={J4_BLkspo}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
						</Image>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-dGWdb.framer-6r5btc, .framer-dGWdb .framer-6r5btc { display: block; }",
	".framer-dGWdb.framer-hr14di { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 768px; }",
	".framer-dGWdb .framer-1a7jybm { align-content: center; align-items: center; align-self: stretch; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: auto; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-dGWdb .framer-dvrjo0, .framer-dGWdb .framer-1291yg6, .framer-dGWdb .framer-lnmo9s, .framer-dGWdb .framer-1my8voi, .framer-dGWdb .framer-zt4v1e { cursor: pointer; flex: none; height: 128px; image-rendering: pixelated; overflow: hidden; position: relative; width: 128px; will-change: var(--framer-will-change-effect-override, transform); }",
	".framer-dGWdb .framer-12de1be { aspect-ratio: 1 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 616px); image-rendering: pixelated; overflow: hidden; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-dGWdb .framer-m6iyeu-container { flex: none; height: 346px; left: 0px; position: absolute; right: 0px; top: 128px; }",
	".framer-dGWdb.framer-v-29poes .framer-12de1be { align-content: center; align-items: center; aspect-ratio: unset; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; padding: 0px; }",
	".framer-dGWdb.framer-v-29poes .framer-m6iyeu-container { left: unset; position: relative; right: unset; top: unset; width: 100%; }",
	".framer-dGWdb.framer-v-111x1sn.framer-hr14di, .framer-dGWdb.framer-v-1y0moxl.framer-hr14di, .framer-dGWdb.framer-v-1ss58ag.framer-hr14di, .framer-dGWdb.framer-v-bbhyg.framer-hr14di, .framer-dGWdb.framer-v-l6ph4u.framer-hr14di { flex-direction: column; width: 360px; }",
	".framer-dGWdb.framer-v-111x1sn .framer-1a7jybm, .framer-dGWdb.framer-v-1y0moxl .framer-1a7jybm, .framer-dGWdb.framer-v-1ss58ag .framer-1a7jybm, .framer-dGWdb.framer-v-bbhyg .framer-1a7jybm, .framer-dGWdb.framer-v-l6ph4u .framer-1a7jybm { align-self: unset; flex-direction: row; height: min-content; order: 1; overflow: auto; padding: 0px 0px 12px 0px; width: 100%; }",
	".framer-dGWdb.framer-v-111x1sn .framer-dvrjo0, .framer-dGWdb.framer-v-111x1sn .framer-1291yg6, .framer-dGWdb.framer-v-111x1sn .framer-lnmo9s, .framer-dGWdb.framer-v-111x1sn .framer-1my8voi, .framer-dGWdb.framer-v-111x1sn .framer-zt4v1e, .framer-dGWdb.framer-v-1y0moxl .framer-dvrjo0, .framer-dGWdb.framer-v-1y0moxl .framer-1291yg6, .framer-dGWdb.framer-v-1y0moxl .framer-lnmo9s, .framer-dGWdb.framer-v-1y0moxl .framer-1my8voi, .framer-dGWdb.framer-v-1y0moxl .framer-zt4v1e, .framer-dGWdb.framer-v-1ss58ag .framer-dvrjo0, .framer-dGWdb.framer-v-1ss58ag .framer-1291yg6, .framer-dGWdb.framer-v-1ss58ag .framer-lnmo9s, .framer-dGWdb.framer-v-1ss58ag .framer-1my8voi, .framer-dGWdb.framer-v-1ss58ag .framer-zt4v1e, .framer-dGWdb.framer-v-bbhyg .framer-dvrjo0, .framer-dGWdb.framer-v-bbhyg .framer-1291yg6, .framer-dGWdb.framer-v-bbhyg .framer-lnmo9s, .framer-dGWdb.framer-v-bbhyg .framer-1my8voi, .framer-dGWdb.framer-v-bbhyg .framer-zt4v1e, .framer-dGWdb.framer-v-l6ph4u .framer-dvrjo0, .framer-dGWdb.framer-v-l6ph4u .framer-1291yg6, .framer-dGWdb.framer-v-l6ph4u .framer-lnmo9s, .framer-dGWdb.framer-v-l6ph4u .framer-1my8voi, .framer-dGWdb.framer-v-l6ph4u .framer-zt4v1e { overflow: visible; }",
	".framer-dGWdb.framer-v-111x1sn .framer-12de1be, .framer-dGWdb.framer-v-1ss58ag .framer-12de1be, .framer-dGWdb.framer-v-bbhyg .framer-12de1be { flex: none; height: var(--framer-aspect-ratio-supported, 360px); order: 0; width: 100%; }",
	".framer-dGWdb.framer-v-1y0moxl .framer-12de1be { flex: none; height: var(--framer-aspect-ratio-supported, 360px); order: 0; overflow: visible; width: 100%; will-change: unset; }",
	".framer-dGWdb.framer-v-l6ph4u .framer-12de1be { align-content: center; align-items: center; aspect-ratio: unset; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; order: 0; padding: 0px; width: 100%; }",
	".framer-dGWdb.framer-v-l6ph4u .framer-m6iyeu-container { height: 194px; left: unset; position: relative; right: unset; top: unset; width: 100%; }",
	'.framer-dGWdb[data-border="true"]::after, .framer-dGWdb [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framertp4Kaxcmd = withCSS(Component, css, "framer-dGWdb");
var stdin_default = Framertp4Kaxcmd;
Framertp4Kaxcmd.displayName = "ProductPage/Product Image";
Framertp4Kaxcmd.defaultProps = {
	height: 616,
	width: 768,
};
addPropertyControls(Framertp4Kaxcmd, {
	variant: {
		options: [
			"s1ONweXGT",
			"eeFrNHiVk",
			"saIUKax4u",
			"H7K23EGHP",
			"ZvGlI3KKF",
			"wFN1Jul_Y",
			"fXDGUhWJc",
			"Jr1xBuoZR",
			"Eff06zvGR",
			"eCkwqOzn0",
		],
		optionTitles: [
			"Desktop1",
			"Desktop2",
			"Desktop3",
			"Desktop4",
			"Desktop - Video",
			"Mobile 1",
			"Mobile 2",
			"Mobile 3",
			"Mobile 4",
			"Mobile - Video",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	NDAAlnFoJ: {
		description: "",
		title: "Image1",
		type: ControlType.ResponsiveImage,
	},
	UVBHb43fo: {
		title: "Image2",
		type: ControlType.ResponsiveImage,
	},
	KRT89CsEf: {
		title: "Image3",
		type: ControlType.ResponsiveImage,
	},
	dMdqsKCdd: {
		description: "",
		title: "Image4",
		type: ControlType.ResponsiveImage,
	},
	BaWCWxrWG: {
		__defaultAssetReference:
			"data:framer/asset-reference,9c3b2KgMhKtlS5vXwTbyHVZbMw.png?originalFilename=image.png&preferredSize=auto",
		description: "",
		title: "Image Video",
		type: ControlType.ResponsiveImage,
	},
	J4_BLkspo: {
		defaultValue: "",
		description: "",
		placeholder: "",
		title: "Video URL",
		type: ControlType.String,
	},
});
addFonts(
	Framertp4Kaxcmd,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...YouTubeFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:product-page/product-image
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "fpVdyfuAw",
		name: "Chinese",
		slug: "yue",
		code: "yue-Hant-HK",
	},
];
var defaultResponsiveVariants = {
	base: "wFN1Jul_Y",
	"2xl": "s1ONweXGT",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProductImageFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var product_image_default = ComponentWithRoot;
export { product_image_default as default };
