// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 826eadcfe2264c6d "Mantra Lingua", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'yue'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Open' | 'Close' // Variant
 * title?: string // Title
 * description?: string // Description
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-FIG2JAJT.js";
import { className, css, fonts } from "./chunks/chunk-PXDCO22G.js";
import { routes } from "./chunks/chunk-74LWP5VC.js";

// virtual:accordion
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/zIyCAgYQ9JXTwChzY814/KqXtrdRoyoJR7PvcvjSJ/Nuvilql_F.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var enabledGestures = {
	T0bdpDiMm: {
		hover: true,
	},
};
var cycleOrder = ["CjfEHaCau", "T0bdpDiMm"];
var serializationHash = "framer-pu8MN";
var variantClassNames = {
	CjfEHaCau: "framer-v-1m0wdrp",
	T0bdpDiMm: "framer-v-91prhc",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1.4,
	stiffness: 500,
	type: "spring",
};
var transition2 = {
	bounce: 0,
	delay: 0,
	duration: 0.8,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 150,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Close: "T0bdpDiMm",
	Open: "CjfEHaCau",
};
var getProps = ({ description, height, id, title, width, ...props }) => {
	return {
		...props,
		DR_6QqGeh: description ?? props.DR_6QqGeh ?? "Description",
		qQefXa5XK: title ?? props.qQefXa5XK ?? "Main Title",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "CjfEHaCau",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		qQefXa5XK,
		DR_6QqGeh,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "CjfEHaCau",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapdr8qo1 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("T0bdpDiMm");
	});
	const onTap1aojsk8 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("CjfEHaCau");
	});
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (gestureVariant === "T0bdpDiMm-hover") return false;
		if (baseVariant === "T0bdpDiMm") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					{...addPropertyOverrides(
						{
							T0bdpDiMm: {
								value: transition1,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1m0wdrp",
							className3,
							classNames,
						)}
						data-framer-name={"Open"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"CjfEHaCau"}
						onTap={onTapdr8qo1}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-18be8aa1-22e1-42de-b67c-9a9ba653a88c, rgb(245, 249, 255))",
							...style,
						}}
						variants={{
							"T0bdpDiMm-hover": {
								backgroundColor:
									"var(--token-18be8aa1-22e1-42de-b67c-9a9ba653a88c, rgb(245, 249, 255))",
							},
							T0bdpDiMm: {
								backgroundColor:
									"var(--token-ce07de20-7c9b-41ae-9f55-cb83b1e44e45, rgba(255, 255, 255, 0.03))",
							},
						}}
						{...addPropertyOverrides(
							{
								"T0bdpDiMm-hover": {
									"data-framer-name": void 0,
								},
								T0bdpDiMm: {
									"data-framer-name": "Close",
									onTap: onTap1aojsk8,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-mod649"}
							data-framer-name={"innderContainer"}
							layoutDependency={layoutDependency}
							layoutId={"PicwEx_3v"}
							style={{
								backgroundColor:
									"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
								boxShadow:
									"0px 0.6021873017743928px 2.52918666745245px -0.5px rgba(0, 0, 0, 0.1), 0px 2.288533303243457px 9.61183987362252px -1px rgba(0, 0, 0, 0.12), 0px 10px 42px -1.5px rgba(0, 0, 0, 0.21)",
							}}
						>
							<motion.div
								className={"framer-bgvyly"}
								data-framer-name={"Question"}
								layoutDependency={layoutDependency}
								layoutId={"D801NbDB7"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-g7jgt6"}
									data-framer-name={"Question"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"skIDeYIkL"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										"--framer-paragraph-spacing": "0px",
									}}
									text={qQefXa5XK}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-4h5sx8"}
											data-styles-preset={"Mh0iQ0jmw"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
											}}
										>
											{"Mantra Lingua"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<motion.button
									className={"framer-1gtf2lp"}
									data-framer-name={"Icon"}
									data-reset={"button"}
									layoutDependency={layoutDependency}
									layoutId={"uhPJN39EG"}
									style={{
										backgroundColor:
											"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
										borderBottomLeftRadius: 100,
										borderBottomRightRadius: 100,
										borderTopLeftRadius: 100,
										borderTopRightRadius: 100,
									}}
								>
									<motion.div
										className={"framer-qx7gqc"}
										data-framer-name={"Line 2"}
										layoutDependency={layoutDependency}
										layoutId={"td2AIyU8M"}
										style={{
											backgroundColor:
												"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
											rotate: 270,
										}}
									/>
									<motion.div
										className={"framer-1w5t4f4"}
										data-framer-name={"Line 1"}
										layoutDependency={layoutDependency}
										layoutId={"N9kvMyO33"}
										style={{
											backgroundColor:
												"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
											rotate: 90,
										}}
										variants={{
											T0bdpDiMm: {
												rotate: 0,
											},
										}}
									/>
								</motion.button>
							</motion.div>
							{isDisplayed() && (
								<motion.div
									className={"framer-nmjhnp"}
									data-framer-name={"Divider"}
									layoutDependency={layoutDependency}
									layoutId={"YCjqadoy8"}
									style={{
										background:
											"linear-gradient(90deg, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)) 0%, rgba(0, 0, 0, 0) 100%)",
									}}
								/>
							)}
							{isDisplayed() && (
								<MotionDivWithFXWithOptimizedAppearEffect
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation}
									className={"framer-il9975"}
									data-framer-appear-id={"il9975"}
									data-framer-name={"Asnwer"}
									initial={animation1}
									layoutDependency={layoutDependency}
									layoutId={"ngLogfcvG"}
									optimized={true}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-17gflxz"}
										data-framer-name={"Answer"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"a8I3pJS44"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
											"--framer-paragraph-spacing": "0px",
										}}
										text={DR_6QqGeh}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-12vbl8y"}
												data-styles-preset={"SDB9Xu_eE"}
												style={{
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
												}}
											>
												{"Mantra Lingua"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</MotionDivWithFXWithOptimizedAppearEffect>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-pu8MN.framer-1ui412z, .framer-pu8MN .framer-1ui412z { display: block; }",
	".framer-pu8MN.framer-1m0wdrp { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 8px; position: relative; width: 391px; }",
	".framer-pu8MN .framer-mod649 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 18px 12px 18px 18px; position: relative; width: 100%; }",
	".framer-pu8MN .framer-bgvyly { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 0px 48px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-pu8MN .framer-g7jgt6, .framer-pu8MN .framer-17gflxz { flex: 1 0 0px; height: auto; overflow: visible; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-pu8MN .framer-1gtf2lp { aspect-ratio: 1 / 1; cursor: pointer; flex: none; height: var(--framer-aspect-ratio-supported, 28px); overflow: hidden; position: relative; width: 28px; will-change: var(--framer-will-change-override, transform); }",
	".framer-pu8MN .framer-qx7gqc, .framer-pu8MN .framer-1w5t4f4 { flex: none; height: 12px; left: calc(50.00000000000002% - 2px / 2); overflow: hidden; position: absolute; top: calc(50.00000000000002% - 12px / 2); width: 2px; }",
	".framer-pu8MN .framer-nmjhnp { flex: none; height: 1px; overflow: hidden; position: relative; width: 100%; }",
	".framer-pu8MN .framer-il9975 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 0px 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-pu8MN.framer-v-91prhc .framer-bgvyly { height: 28px; }",
	".framer-pu8MN.framer-v-91prhc.hover .framer-1gtf2lp { height: var(--framer-aspect-ratio-supported, 34px); width: 34px; }",
	...css,
	...css2,
];
var FramerNuvilql_F = withCSS(Component, css3, "framer-pu8MN");
var stdin_default = FramerNuvilql_F;
FramerNuvilql_F.displayName = "accordion";
FramerNuvilql_F.defaultProps = {
	height: 140.5,
	width: 391,
};
addPropertyControls(FramerNuvilql_F, {
	variant: {
		options: ["CjfEHaCau", "T0bdpDiMm"],
		optionTitles: ["Open", "Close"],
		title: "Variant",
		type: ControlType.Enum,
	},
	qQefXa5XK: {
		defaultValue: "Main Title",
		description: "",
		displayTextArea: false,
		placeholder: "",
		title: "Title",
		type: ControlType.String,
	},
	DR_6QqGeh: {
		defaultValue: "Description",
		displayTextArea: false,
		placeholder: "",
		title: "Description",
		type: ControlType.String,
	},
});
addFonts(
	FramerNuvilql_F,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:accordion
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "fpVdyfuAw",
		name: "Chinese",
		slug: "yue",
		code: "yue-Hant-HK",
	},
];
var defaultResponsiveVariants = {
	base: "T0bdpDiMm",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AccordionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var accordion_default = ComponentWithRoot;
export { accordion_default as default };
