// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 826eadcfe2264c6d "Mantra Lingua", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'yue'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Blue' | 'Yellow' | 'Black' | 'Ghost' | 'Clear' | 'Payment Buttons' | 'Custom' | 'pay-Active-hover' | 'custom-Active-hover' // Variant
 * title?: string // Title
 * click?: Function // Click
 * iconVisible?: boolean // Icon Visible
 * iconSelect?: undefined // Icon Select
 * iconColour?: string // Icon Colour
 * ghostBackground?: string // Ghost Background
 * ghostHoverColour?: string // Ghost Hover Colour
 * visibleApplePay?: boolean // Visible - Apple Pay
 * visibleGooglePay?: boolean // Visible - Google Pay
 * radiusButton?: undefined // Radius - Button
 * customColourActive?: string // Custom Colour Active
 * customColourHover?: string // Custom Colour Hover
 * colorText?: string // Color - Text
 * borderButton?: undefined // Border - Button
}} Props

 */
import { stdin_default } from "./chunks/chunk-VHWSTUA5.js";
import "./chunks/chunk-L3O2CTIU.js";
import "./chunks/chunk-U2J7FPUL.js";
import "./chunks/chunk-VZARCJE6.js";
import { routes } from "./chunks/chunk-74LWP5VC.js";

// virtual:button-rounded
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "fpVdyfuAw",
		name: "Chinese",
		slug: "yue",
		code: "yue-Hant-HK",
	},
];
var defaultResponsiveVariants = {
	base: "F4eeMnvJh",
	xl: "JGaVNRjFz",
	"2xl": "R2ILBd3lt",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonRoundedFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_rounded_default = ComponentWithRoot;
export { button_rounded_default as default };
