// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 826eadcfe2264c6d "Mantra Lingua", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'yue'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Spinning' | 'Complete' | 'FAB' | 'Pressed' // Variant
 * title?: string // Title
 * titleComplete?: string // Title - Complete
 * background?: string // Background
 * backgroundHover?: string // Background Hover
 * backgroundSelected?: string // Background Selected
 * backgroundShadowBox?: string // Background shadowBox
 * textColour?: string // Text Colour
 * click?: Function // Click
 * iconSelect?: undefined // Icon Select
 * iconColour?: string // Icon Colour
 * visibleLogoXLArge?: boolean // Visible - Logo XLarge
 * visibleLogoLarge?: boolean // Visible - Logo Large
 * visibleLogoMedium?: boolean // Visible - Logo Medium
 * visibleLogoSmall?: boolean // Visible - Logo Small
 * fABPadding?: undefined // FAB - Padding
}} Props

 */
import { stdin_default } from "./chunks/chunk-GM5ZJE4B.js";
import "./chunks/chunk-YLTGU2H6.js";
import "./chunks/chunk-QWKSH5UA.js";
import { routes } from "./chunks/chunk-74LWP5VC.js";

// virtual:button-submit
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "fpVdyfuAw",
		name: "Chinese",
		slug: "yue",
		code: "yue-Hant-HK",
	},
];
var defaultResponsiveVariants = {
	base: "oxFU6K266",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonSubmitFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_submit_default = ComponentWithRoot;
export { button_submit_default as default };
