// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 826eadcfe2264c6d "Mantra Lingua", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'yue'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'PickUp' | 'Complete' | 'PickUp Complete' // Variant
 * click?: Function // Click
 * click2?: Function // Click 2
 * click3?: Function // Click 3
}} Props

 */
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-HPY77AVG.js";
import { GoogleMaps } from "./chunks/chunk-5NP77DXV.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-C6MNZJBI.js";
import "./chunks/chunk-NUFRM6SI.js";
import "./chunks/chunk-KL3BYY5R.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
	stdin_default,
} from "./chunks/chunk-KKE5BSS4.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-LSDZCXQW.js";
import { className, css, fonts } from "./chunks/chunk-VZARCJE6.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-D53GR4VG.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-QWKSH5UA.js";
import { routes } from "./chunks/chunk-74LWP5VC.js";

// virtual:delivery-options-enter
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/pmqOpJxQOoemE7c411Jr/nGUI7SEiLS9sAeOpwUxg/aLodg8Q9_.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	FormContainer,
	FormPlainTextInput,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/iT2hcu8Vjk3HALh13prb/qxg2lUgQovnuZaF4Jpq5/omuXEWvnZ.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;General Sans-regular",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts6 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "General Sans",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/MFQT7HFGCR2L5ULQTW6YXYZXXHMPKLJ3/YWQ244D6TACUX5JBKATPOW5I5MGJ3G73/7YY3ZAAE3TRV2LANYOLXNHTPHLXVWTKH.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css6 = [
	`.framer-RT88p .framer-styles-preset-1i8utav:not(.rich-text-wrapper), .framer-RT88p .framer-styles-preset-1i8utav.rich-text-wrapper p { --framer-font-family: "General Sans", "General Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 0.78); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-ff6489d4-75ce-4cd5-b9b8-ecb94f728f08, #979797); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1439px) and (min-width: 1200px) { .framer-RT88p .framer-styles-preset-1i8utav:not(.rich-text-wrapper), .framer-RT88p .framer-styles-preset-1i8utav.rich-text-wrapper p { --framer-font-family: "General Sans", "General Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 0.75); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-ff6489d4-75ce-4cd5-b9b8-ecb94f728f08, #979797); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 1199px) and (min-width: 0px) { .framer-RT88p .framer-styles-preset-1i8utav:not(.rich-text-wrapper), .framer-RT88p .framer-styles-preset-1i8utav.rich-text-wrapper p { --framer-font-family: "General Sans", "General Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 0.72); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-ff6489d4-75ce-4cd5-b9b8-ecb94f728f08, #979797); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className6 = "framer-RT88p";

// /:https://framerusercontent.com/modules/pmqOpJxQOoemE7c411Jr/nGUI7SEiLS9sAeOpwUxg/aLodg8Q9_.js
var ButtonCartoonFonts = getFonts(stdin_default3);
var DeliveryOptionsCompleteFonts = getFonts(stdin_default);
var GoogleMapsFonts = getFonts(GoogleMaps);
var cycleOrder = ["EjLhfMBMO", "vUZJEEYbi", "F6L4KtJMy", "b1EZjqTWN"];
var serializationHash = "framer-PG5QP";
var variantClassNames = {
	b1EZjqTWN: "framer-v-17tgl1i",
	EjLhfMBMO: "framer-v-1ryf61t",
	F6L4KtJMy: "framer-v-8mvaes",
	vUZJEEYbi: "framer-v-ebt9u0",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"PickUp Complete": "b1EZjqTWN",
	Complete: "F6L4KtJMy",
	Default: "EjLhfMBMO",
	PickUp: "vUZJEEYbi",
};
var getProps = ({ click, click2, click3, height, id, width, ...props }) => {
	return {
		...props,
		eIIezbLOr: click2 ?? props.eIIezbLOr,
		EVVgSZbMs: click3 ?? props.EVVgSZbMs,
		frReFa6Yb: click ?? props.frReFa6Yb,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "EjLhfMBMO",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className7,
		layoutId,
		variant,
		frReFa6Yb,
		eIIezbLOr,
		EVVgSZbMs,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "EjLhfMBMO",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapvbb3wp = activeVariantCallback(async (...args) => {
		if (frReFa6Yb) {
			const res = await frReFa6Yb(...args);
			if (res === false) return false;
		}
		setVariant("EjLhfMBMO");
	});
	const rmHujUjggder1e3 = activeVariantCallback(async (...args) => {
		if (eIIezbLOr) {
			const res = await eIIezbLOr(...args);
			if (res === false) return false;
		}
		setVariant("EjLhfMBMO");
	});
	const rmHujUjgg2ta747 = activeVariantCallback(async (...args) => {
		if (EVVgSZbMs) {
			const res = await EVVgSZbMs(...args);
			if (res === false) return false;
		}
		setVariant("vUZJEEYbi");
	});
	const onTap1kbixcr = activeVariantCallback(async (...args) => {
		setVariant("F6L4KtJMy");
	});
	const onTaplhkh91 = activeVariantCallback(async (...args) => {
		setVariant("b1EZjqTWN");
	});
	const rmHujUjgg16h1ckt = activeVariantCallback(async (...args) => {
		if (frReFa6Yb) {
			const res = await frReFa6Yb(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [
		className5,
		className3,
		className4,
		className2,
		className,
		className6,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["F6L4KtJMy", "b1EZjqTWN"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (["F6L4KtJMy", "b1EZjqTWN"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "vUZJEEYbi") return false;
		return true;
	};
	const isDisplayed3 = () => {
		if (["vUZJEEYbi", "F6L4KtJMy", "b1EZjqTWN"].includes(baseVariant))
			return false;
		return true;
	};
	const isDisplayed4 = () => {
		if (baseVariant === "b1EZjqTWN") return false;
		return true;
	};
	const isDisplayed5 = () => {
		if (baseVariant === "vUZJEEYbi") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1ryf61t",
							className7,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"EjLhfMBMO"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								b1EZjqTWN: {
									"data-framer-name": "PickUp Complete",
								},
								F6L4KtJMy: {
									"data-framer-name": "Complete",
								},
								vUZJEEYbi: {
									"data-framer-name": "PickUp",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1s5eqls"}
							data-framer-name={"Main Title - 1"}
							layoutDependency={layoutDependency}
							layoutId={"H8Vmz9Wnh"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-o2va84"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"nUF1jbFd7"}
								style={{
									"--extracted-a0htzi":
										"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-1scm8hv"}
										data-styles-preset={"NBxYw7UgC"}
										style={{
											"--framer-text-color":
												"var(--extracted-a0htzi, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
										}}
									>
										{"Delivery Options"}
									</motion.h3>
								</React.Fragment>
							</RichText>
							{isDisplayed() && (
								<RichText
									__fromCanvasComponent={true}
									className={"framer-17nan4i"}
									data-highlight={true}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"YHM_dCG22"}
									onTap={onTapvbb3wp}
									style={{
										"--extracted-r6o4lv":
											"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-17y2nrb"}
											data-styles-preset={"wQhpXtb8F"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
											}}
										>
											{"Edit"}
										</motion.p>
									</React.Fragment>
								</RichText>
							)}
						</motion.div>
						{isDisplayed1() && (
							<motion.div
								className={"framer-15amh8r"}
								data-framer-name={"Section 1 - Buttons"}
								layoutDependency={layoutDependency}
								layoutId={"NmIZSNCu9"}
							>
								<ComponentViewportProvider
									height={60}
									width={`max((${componentViewport?.width || "100vw"} - 16px) / 2, 1px)`}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 736) - 36 - 810.6) / 2 +
											57.6 +
											16) +
										0
									}
									{...addPropertyOverrides(
										{
											vUZJEEYbi: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 861.5) - 36 - 825.6) /
														2 +
														57.6 +
														16) +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-13k2lym-container"}
										layoutDependency={layoutDependency}
										layoutId={"fzv9zJpet-container"}
										nodeId={"fzv9zJpet"}
										rendersWithMotion={true}
										scopeId={"aLodg8Q9_"}
									>
										{_jsx(stdin_default3, {
											AhxkQCIUK:
												"var(--token-b16f50dd-11da-447e-b6e0-1de4e41e94cc, rgb(87, 128, 235))",
											Bs7Kfyol3: "Sign up",
											bvHLWpZgR: false,
											GbG6B20dD:
												"var(--token-da79aab1-7975-42cb-a714-582054b64ae5, rgb(41, 94, 230))",
											gHUOQVyAX: false,
											height: "100%",
											id: "fzv9zJpet",
											KIs7LET4E:
												"var(--token-82c2ba29-5908-4d7f-a6b2-a07af22347c1, rgba(255, 255, 255, 0.9))",
											layoutId: "fzv9zJpet",
											NILxoTyW_: false,
											PVX37ezAj:
												"var(--token-b8caeba6-5a35-4a04-8419-705e033e94ff, rgb(12, 39, 106))",
											rmHujUjgg: rmHujUjggder1e3,
											Si2TgLaT3:
												"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "d_dQwBXKY",
											width: "100%",
											wnNedC3i2:
												"var(--token-da79aab1-7975-42cb-a714-582054b64ae5, rgb(41, 94, 230))",
											XGMS85IRk: stdin_default2,
											xni3gMFPB: false,
											zatm_emhi: "8px",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ComponentViewportProvider
									height={60}
									width={`max((${componentViewport?.width || "100vw"} - 16px) / 2, 1px)`}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 736) - 36 - 810.6) / 2 +
											57.6 +
											16) +
										0
									}
									{...addPropertyOverrides(
										{
											vUZJEEYbi: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 861.5) - 36 - 825.6) /
														2 +
														57.6 +
														16) +
													0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1eehkdy-container"}
										layoutDependency={layoutDependency}
										layoutId={"tuDjkm81R-container"}
										nodeId={"tuDjkm81R"}
										rendersWithMotion={true}
										scopeId={"aLodg8Q9_"}
									>
										{_jsx(stdin_default3, {
											AhxkQCIUK:
												"var(--token-b16f50dd-11da-447e-b6e0-1de4e41e94cc, rgb(87, 128, 235))",
											Bs7Kfyol3: "Sign up",
											bvHLWpZgR: false,
											GbG6B20dD:
												"var(--token-da79aab1-7975-42cb-a714-582054b64ae5, rgb(41, 94, 230))",
											gHUOQVyAX: false,
											height: "100%",
											id: "tuDjkm81R",
											KIs7LET4E:
												"var(--token-82c2ba29-5908-4d7f-a6b2-a07af22347c1, rgba(255, 255, 255, 0.9))",
											layoutId: "tuDjkm81R",
											NILxoTyW_: false,
											PVX37ezAj:
												"var(--token-b8caeba6-5a35-4a04-8419-705e033e94ff, rgb(12, 39, 106))",
											rmHujUjgg: rmHujUjgg2ta747,
											Si2TgLaT3:
												"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: "d_dQwBXKY",
											width: "100%",
											wnNedC3i2:
												"var(--token-da79aab1-7975-42cb-a714-582054b64ae5, rgb(41, 94, 230))",
											XGMS85IRk: stdin_default2,
											xni3gMFPB: false,
											zatm_emhi: "8px",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
						)}
						{isDisplayed1() && (
							<FormContainer
								className={"framer-8xaa8r"}
								layoutDependency={layoutDependency}
								layoutId={"DkyHawBwI"}
								nodeId={"DkyHawBwI"}
							>
								{(formState) => (
									<_Fragment>
										<motion.label
											className={"framer-1to5qoi"}
											data-framer-name={"Label - Email"}
											layoutDependency={layoutDependency}
											layoutId={"woF_iJaIq"}
										>
											<FormPlainTextInput
												className={"framer-1k74xt8"}
												inputName={"Email"}
												layoutDependency={layoutDependency}
												layoutId={"qzZUy2snO"}
												placeholder={"jane@framer.com"}
												required={true}
												style={{
													"--framer-input-background":
														"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
													"--framer-input-border-bottom-width": "1px",
													"--framer-input-border-color":
														"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
													"--framer-input-border-left-width": "1px",
													"--framer-input-border-radius-bottom-left": "4px",
													"--framer-input-border-radius-bottom-right": "4px",
													"--framer-input-border-radius-top-left": "4px",
													"--framer-input-border-radius-top-right": "4px",
													"--framer-input-border-right-width": "1px",
													"--framer-input-border-style": "solid",
													"--framer-input-border-top-width": "1px",
													"--framer-input-font-color": "rgb(153, 153, 153)",
													"--framer-input-icon-color": "rgb(153, 153, 153)",
													"--framer-input-placeholder-color":
														"rgb(153, 153, 153)",
												}}
												type={"email"}
											/>
										</motion.label>
										<motion.label
											className={"framer-fkbwgt"}
											data-framer-name={"Label - First Name"}
											layoutDependency={layoutDependency}
											layoutId={"RyzxUEPiK"}
										>
											<FormPlainTextInput
												className={"framer-1e9640q"}
												inputName={"first name"}
												layoutDependency={layoutDependency}
												layoutId={"RnrSdb028"}
												placeholder={"First Name"}
												required={true}
												style={{
													"--framer-input-background":
														"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
													"--framer-input-border-bottom-width": "1px",
													"--framer-input-border-color":
														"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
													"--framer-input-border-left-width": "1px",
													"--framer-input-border-radius-bottom-left": "4px",
													"--framer-input-border-radius-bottom-right": "4px",
													"--framer-input-border-radius-top-left": "4px",
													"--framer-input-border-radius-top-right": "4px",
													"--framer-input-border-right-width": "1px",
													"--framer-input-border-style": "solid",
													"--framer-input-border-top-width": "1px",
													"--framer-input-font-color": "rgb(153, 153, 153)",
													"--framer-input-icon-color": "rgb(153, 153, 153)",
													"--framer-input-placeholder-color":
														"rgb(153, 153, 153)",
												}}
												type={"text"}
											/>
										</motion.label>
										<motion.label
											className={"framer-d1q12"}
											data-framer-name={"Label - Last Name"}
											layoutDependency={layoutDependency}
											layoutId={"C7FzOINl6"}
										>
											<FormPlainTextInput
												className={"framer-1neu0hk"}
												inputName={"last name"}
												layoutDependency={layoutDependency}
												layoutId={"IZ4plhZLe"}
												placeholder={"Last Name"}
												required={true}
												style={{
													"--framer-input-background":
														"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
													"--framer-input-border-bottom-width": "1px",
													"--framer-input-border-color":
														"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
													"--framer-input-border-left-width": "1px",
													"--framer-input-border-radius-bottom-left": "4px",
													"--framer-input-border-radius-bottom-right": "4px",
													"--framer-input-border-radius-top-left": "4px",
													"--framer-input-border-radius-top-right": "4px",
													"--framer-input-border-right-width": "1px",
													"--framer-input-border-style": "solid",
													"--framer-input-border-top-width": "1px",
													"--framer-input-font-color": "rgb(153, 153, 153)",
													"--framer-input-icon-color": "rgb(153, 153, 153)",
													"--framer-input-placeholder-color":
														"rgb(153, 153, 153)",
												}}
												type={"text"}
											/>
										</motion.label>
										{isDisplayed2() && (
											<motion.div
												className={"framer-ua2p5b"}
												data-border={true}
												data-framer-name={"Search Address"}
												layoutDependency={layoutDependency}
												layoutId={"I741_aRRb"}
												style={{
													"--border-bottom-width": "1px",
													"--border-color":
														"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
													"--border-left-width": "1px",
													"--border-right-width": "1px",
													"--border-style": "solid",
													"--border-top-width": "1px",
													backgroundColor:
														"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
													borderBottomLeftRadius: 4,
													borderBottomRightRadius: 4,
													borderTopLeftRadius: 4,
													borderTopRightRadius: 4,
												}}
											/>
										)}
										{isDisplayed2() && (
											<motion.div
												className={"framer-1excfws"}
												data-framer-name={"Title"}
												layoutDependency={layoutDependency}
												layoutId={"x5XeffRqS"}
											>
												<RichText
													__fromCanvasComponent={true}
													className={"framer-fv0ny7"}
													fonts={["Inter"]}
													layoutDependency={layoutDependency}
													layoutId={"BwxlpbghZ"}
													style={{
														"--extracted-r6o4lv":
															"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
														"--framer-link-text-color": "rgb(0, 153, 255)",
														"--framer-link-text-decoration": "underline",
													}}
													verticalAlignment={"top"}
													withExternalLayout={true}
												>
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-vx06ga"}
															data-styles-preset={"iPyXfMAgt"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
															}}
														>
															{"Enter address manually"}
														</motion.p>
													</React.Fragment>
												</RichText>
											</motion.div>
										)}
										{isDisplayed2() && (
											<motion.label
												className={"framer-t37jpn"}
												data-framer-name={"Label - Enter Address"}
												layoutDependency={layoutDependency}
												layoutId={"YO4haHkpZ"}
											>
												<FormPlainTextInput
													className={"framer-1egc8dn"}
													inputName={"Address"}
													layoutDependency={layoutDependency}
													layoutId={"l6He9TZRd"}
													placeholder={"Enter Postcode"}
													style={{
														"--framer-input-background":
															"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
														"--framer-input-border-bottom-width": "1px",
														"--framer-input-border-color":
															"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
														"--framer-input-border-left-width": "1px",
														"--framer-input-border-radius-bottom-left": "4px",
														"--framer-input-border-radius-bottom-right": "4px",
														"--framer-input-border-radius-top-left": "4px",
														"--framer-input-border-radius-top-right": "4px",
														"--framer-input-border-right-width": "1px",
														"--framer-input-border-style": "solid",
														"--framer-input-border-top-width": "1px",
														"--framer-input-font-color": "rgb(153, 153, 153)",
														"--framer-input-icon-color": "rgb(153, 153, 153)",
														"--framer-input-placeholder-color":
															"rgb(153, 153, 153)",
													}}
													type={"text"}
												/>
											</motion.label>
										)}
									</_Fragment>
								)}
							</FormContainer>
						)}
						{isDisplayed3() && (
							<ComponentViewportProvider
								height={163}
								width={componentViewport?.width || "100vw"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 736) - 36 - 810.6) / 2 +
										499.6 +
										48)
								}
							>
								<SmartComponentScopedContainer
									className={"framer-yf0xdd-container"}
									layoutDependency={layoutDependency}
									layoutId={"alsdFusC_-container"}
									nodeId={"alsdFusC_"}
									rendersWithMotion={true}
									scopeId={"aLodg8Q9_"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "alsdFusC_",
										layoutId: "alsdFusC_",
										style: {
											width: "100%",
										},
										variant: "pzg73CgrL",
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						)}
						{isDisplayed() && (
							<motion.div
								className={"framer-wskgkb"}
								data-framer-name={"Delivery Details - Complete"}
								layoutDependency={layoutDependency}
								layoutId={"xUfkkoA9I"}
								style={{
									backgroundColor: "rgb(245, 254, 225)",
									borderBottomLeftRadius: 4,
									borderBottomRightRadius: 4,
									borderTopLeftRadius: 4,
									borderTopRightRadius: 4,
								}}
							>
								<motion.div
									className={"framer-18gjy7h"}
									data-framer-name={"Section - 2"}
									layoutDependency={layoutDependency}
									layoutId={"GJ_W8PkIt"}
									style={{
										borderBottomLeftRadius: 4,
										borderBottomRightRadius: 4,
										borderTopLeftRadius: 4,
										borderTopRightRadius: 4,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1r26tht"}
										data-framer-name={"Select a payment method"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"ak0JPX3Qq"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"center"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-rrwhkf"}
												data-styles-preset={"VjAW3nFsc"}
												style={{
													"--framer-text-alignment": "left",
												}}
											>
												{"Delivery Address"}
											</motion.p>
										</React.Fragment>
									</RichText>
									{isDisplayed4() && (
										<motion.div
											className={"framer-zlqxtc"}
											data-framer-name={"Region"}
											layoutDependency={layoutDependency}
											layoutId={"DrxFwo0SJ"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-1btvtpg"}
												data-framer-name={"Region"}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"j_bE1Loir"}
												style={{
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
												}}
												verticalAlignment={"center"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1lsmrgt"}
														data-styles-preset={"gdtsaRKtH"}
													>
														{
															"Robert Corley  4 Pickering Court  Wrexham LL14 4DR  rob.corley@mantralingua.com  447850172056"
														}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									)}
									<motion.div
										className={"framer-ytpifv"}
										data-border={true}
										data-framer-name={"Region"}
										layoutDependency={layoutDependency}
										layoutId={"ow29q_8HQ"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color":
												"var(--token-5d7f1098-ba6b-4ff0-a2c8-e98b8b287a71, rgb(115, 115, 115))",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											borderBottomLeftRadius: 4,
											borderBottomRightRadius: 4,
											borderTopLeftRadius: 4,
											borderTopRightRadius: 4,
										}}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-17yjilj"}
											data-framer-name={"Region"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"iEPTq_i5C"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											variants={{
												b1EZjqTWN: {
													"--extracted-r6o4lv":
														"var(--token-5d7f1098-ba6b-4ff0-a2c8-e98b8b287a71, rgb(115, 115, 115))",
												},
												F6L4KtJMy: {
													"--extracted-r6o4lv":
														"var(--token-5d7f1098-ba6b-4ff0-a2c8-e98b8b287a71, rgb(115, 115, 115))",
												},
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													b1EZjqTWN: {
														children: (
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-1lsmrgt"}
																	data-styles-preset={"gdtsaRKtH"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-5d7f1098-ba6b-4ff0-a2c8-e98b8b287a71, rgb(115, 115, 115)))",
																	}}
																>
																	{"Pick Up"}
																</motion.p>
															</React.Fragment>
														),
													},
													F6L4KtJMy: {
														children: (
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-1lsmrgt"}
																	data-styles-preset={"gdtsaRKtH"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-5d7f1098-ba6b-4ff0-a2c8-e98b8b287a71, rgb(115, 115, 115)))",
																	}}
																>
																	{"Free"}
																</motion.p>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-1lsmrgt"}
													data-styles-preset={"gdtsaRKtH"}
												>
													{"Free"}
												</motion.p>
											</React.Fragment>
										</RichText>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1x6qma7"}
											data-framer-name={"Region"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"eRqZCXJYP"}
											style={{
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											variants={{
												b1EZjqTWN: {
													"--extracted-1xy48n3":
														"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
													"--extracted-5dqwso":
														"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
													"--extracted-ai2n6u":
														"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
													"--extracted-r6o4lv":
														"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
													"--extracted-t0vbzb":
														"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
													"--extracted-z6xut3":
														"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
												},
												F6L4KtJMy: {
													"--extracted-r6o4lv":
														"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
												},
											}}
											verticalAlignment={"center"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													b1EZjqTWN: {
														children: (
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-17y2nrb"}
																	data-styles-preset={"wQhpXtb8F"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
																	}}
																>
																	{"Printed Easy Limited,"}
																</motion.p>
																<motion.p
																	className={"framer-styles-preset-1lsmrgt"}
																	data-styles-preset={"gdtsaRKtH"}
																>
																	<motion.span
																		style={{
																			"--framer-text-color":
																				"var(--extracted-5dqwso, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
																		}}
																	>
																		{"1 Meredews"}
																	</motion.span>
																	<motion.br />
																	<motion.span
																		style={{
																			"--framer-text-color":
																				"var(--extracted-1xy48n3, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
																		}}
																	>
																		{"Works Road"}
																	</motion.span>
																	<motion.br />
																	<motion.span
																		style={{
																			"--framer-text-color":
																				"var(--extracted-ai2n6u, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
																		}}
																	>
																		{"Letchworth Garden City"}
																	</motion.span>
																	<motion.br />
																	<motion.span
																		style={{
																			"--framer-text-color":
																				"var(--extracted-z6xut3, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
																		}}
																	>
																		{"Hertfordshire"}
																	</motion.span>
																	<motion.br />
																	<motion.span
																		style={{
																			"--framer-text-color":
																				"var(--extracted-t0vbzb, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
																		}}
																	>
																		{"SG6 1WH"}
																	</motion.span>
																</motion.p>
															</React.Fragment>
														),
													},
													F6L4KtJMy: {
														children: (
															<React.Fragment>
																<motion.p
																	className={"framer-styles-preset-1lsmrgt"}
																	data-styles-preset={"gdtsaRKtH"}
																	style={{
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
																	}}
																>
																	{"Arrives by Monday, 10 March"}
																</motion.p>
															</React.Fragment>
														),
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-vx06ga"}
													data-styles-preset={"iPyXfMAgt"}
												>
													{"Arrives by Monday, 10 March"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
							</motion.div>
						)}
						{isDisplayed1() && (
							<motion.div
								className={"framer-1vtyv8c"}
								data-framer-name={"Save & Continue"}
								data-highlight={true}
								layoutDependency={layoutDependency}
								layoutId={"TTvlLeKKE"}
								onTap={onTap1kbixcr}
								{...addPropertyOverrides(
									{
										vUZJEEYbi: {
											onTap: onTaplhkh91,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<ComponentViewportProvider
									height={60}
									width={"360px"}
									y={
										(componentViewport?.y || 0) +
										0 +
										(((componentViewport?.height || 736) - 36 - 810.6) / 2 +
											662.6 +
											64) +
										24
									}
									{...addPropertyOverrides(
										{
											vUZJEEYbi: {
												y:
													(componentViewport?.y || 0) +
													0 +
													(((componentViewport?.height || 861.5) - 36 - 825.6) /
														2 +
														677.6 +
														64) +
													24,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-69a1j9-container"}
										layoutDependency={layoutDependency}
										layoutId={"vHAhMemVX-container"}
										nodeId={"vHAhMemVX"}
										rendersWithMotion={true}
										scopeId={"aLodg8Q9_"}
									>
										{_jsx(stdin_default3, {
											AhxkQCIUK:
												"var(--token-b16f50dd-11da-447e-b6e0-1de4e41e94cc, rgb(87, 128, 235))",
											Bs7Kfyol3: "Sign up",
											bvHLWpZgR: false,
											GbG6B20dD:
												"var(--token-da79aab1-7975-42cb-a714-582054b64ae5, rgb(41, 94, 230))",
											gHUOQVyAX: false,
											height: "100%",
											id: "vHAhMemVX",
											KIs7LET4E:
												"var(--token-82c2ba29-5908-4d7f-a6b2-a07af22347c1, rgba(255, 255, 255, 0.9))",
											layoutId: "vHAhMemVX",
											NILxoTyW_: false,
											PVX37ezAj:
												"var(--token-b8caeba6-5a35-4a04-8419-705e033e94ff, rgb(12, 39, 106))",
											rmHujUjgg: rmHujUjgg16h1ckt,
											Si2TgLaT3:
												"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
											style: {
												height: "100%",
												maxWidth: "100%",
												width: "100%",
											},
											variant: "d_dQwBXKY",
											width: "100%",
											wnNedC3i2:
												"var(--token-da79aab1-7975-42cb-a714-582054b64ae5, rgb(41, 94, 230))",
											XGMS85IRk: stdin_default2,
											xni3gMFPB: false,
											zatm_emhi: "8px",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
						)}
						{isDisplayed5() && (
							<motion.div
								className={"framer-8o2hi5"}
								data-border={true}
								data-framer-name={"Address - 1"}
								layoutDependency={layoutDependency}
								layoutId={"RSZqvTrPJ"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									borderBottomLeftRadius: 4,
									borderBottomRightRadius: 4,
									borderTopLeftRadius: 4,
									borderTopRightRadius: 4,
								}}
							>
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-1x659bj-container"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"eVF0D40lx-container"}
										nodeId={"eVF0D40lx"}
										rendersWithMotion={true}
										scopeId={"aLodg8Q9_"}
									>
										<GoogleMaps
											borderRadius={0}
											bottomLeftRadius={0}
											bottomRightRadius={0}
											coordinates={"51.98434377599761, -0.21274760651552269"}
											height={"100%"}
											id={"eVF0D40lx"}
											isMixedBorderRadius={false}
											layoutId={"eVF0D40lx"}
											style={{
												height: "100%",
												width: "100%",
											}}
											topLeftRadius={0}
											topRightRadius={0}
											width={"100%"}
											zoom={15}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1ruqlfc"}
									data-framer-name={"Address"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"dgPeH7Jhm"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"center"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1i8utav"}
											data-styles-preset={"omuXEWvnZ"}
											style={{
												"--framer-text-alignment": "center",
											}}
										>
											{"Mantra Lingua Limited"}
										</motion.p>
										<motion.p
											className={"framer-styles-preset-1i8utav"}
											data-styles-preset={"omuXEWvnZ"}
											style={{
												"--framer-text-alignment": "center",
											}}
										>
											{"1 Meredews"}
											<motion.br />
											{"Works Road"}
											<motion.br />
											{"Letchworth Garden City"}
											<motion.br />
											{"Hertfordshire"}
											<motion.br />
											{"SG6 1WH"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css7 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-PG5QP.framer-1wr53og, .framer-PG5QP .framer-1wr53og { display: block; }",
	".framer-PG5QP.framer-1ryf61t { align-content: flex-end; align-items: flex-end; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 36px 0px; position: relative; width: 1099px; }",
	".framer-PG5QP .framer-1s5eqls { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-PG5QP .framer-o2va84, .framer-PG5QP .framer-1btvtpg, .framer-PG5QP .framer-17yjilj, .framer-PG5QP .framer-1x6qma7 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-PG5QP .framer-17nan4i { cursor: pointer; flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-PG5QP .framer-15amh8r { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-PG5QP .framer-13k2lym-container, .framer-PG5QP .framer-1eehkdy-container { flex: 1 0 0px; height: 60px; position: relative; width: 1px; }",
	".framer-PG5QP .framer-8xaa8r { display: grid; flex: none; gap: 16px; grid-auto-rows: min-content; grid-template-columns: repeat(2, minmax(50px, 1fr)); grid-template-rows: repeat(2, min-content); height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-PG5QP .framer-1to5qoi { align-content: flex-start; align-items: flex-start; align-self: start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; grid-column: span 2; height: min-content; justify-content: flex-start; justify-self: start; padding: 0px; position: relative; width: 100%; }",
	'.framer-PG5QP .framer-1k74xt8, .framer-PG5QP .framer-1e9640q, .framer-PG5QP .framer-1neu0hk, .framer-PG5QP .framer-1egc8dn { --framer-input-focused-border-color: #0099ff; --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-font-family: "Inter"; --framer-input-font-letter-spacing: 0em; --framer-input-font-line-height: 1.2em; --framer-input-font-size: 14px; --framer-input-font-weight: 400; --framer-input-padding: 12px; flex: none; height: 48px; position: relative; width: 100%; }',
	".framer-PG5QP .framer-fkbwgt, .framer-PG5QP .framer-d1q12, .framer-PG5QP .framer-t37jpn { align-content: flex-start; align-items: flex-start; align-self: start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; justify-self: start; padding: 0px; position: relative; width: 100%; }",
	".framer-PG5QP .framer-ua2p5b { align-content: center; align-items: center; align-self: start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; grid-column: span 2; height: 48px; justify-content: flex-start; justify-self: start; overflow: visible; padding: 0px 0px 0px 24px; position: relative; width: 100%; }",
	".framer-PG5QP .framer-1excfws { align-content: center; align-items: center; align-self: start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; grid-column: span 2; height: min-content; justify-content: space-between; justify-self: start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-PG5QP .framer-fv0ny7, .framer-PG5QP .framer-1ruqlfc { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-PG5QP .framer-yf0xdd-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-PG5QP .framer-wskgkb { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 12px; position: relative; width: 100%; }",
	".framer-PG5QP .framer-18gjy7h { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-PG5QP .framer-1r26tht { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-PG5QP .framer-zlqxtc { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-PG5QP .framer-ytpifv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: flex-start; overflow: visible; padding: 8px 16px 8px 16px; position: relative; width: 100%; }",
	".framer-PG5QP .framer-1vtyv8c { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; overflow: visible; padding: 24px 0px 0px 0px; position: relative; width: min-content; }",
	".framer-PG5QP .framer-69a1j9-container { flex: none; height: 60px; max-width: 360px; position: relative; width: 360px; }",
	".framer-PG5QP .framer-8o2hi5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 24px; position: relative; width: 100%; }",
	".framer-PG5QP .framer-1x659bj-container { flex: none; height: 400px; position: relative; width: 600px; }",
	".framer-PG5QP.framer-v-ebt9u0 .framer-1s5eqls { order: 0; }",
	".framer-PG5QP.framer-v-ebt9u0 .framer-15amh8r { order: 1; }",
	".framer-PG5QP.framer-v-ebt9u0 .framer-8xaa8r { order: 2; }",
	".framer-PG5QP.framer-v-ebt9u0 .framer-1vtyv8c { order: 6; }",
	".framer-PG5QP.framer-v-ebt9u0 .framer-8o2hi5 { order: 5; }",
	".framer-PG5QP.framer-v-17tgl1i .framer-ytpifv { align-content: flex-start; align-items: flex-start; }",
	".framer-PG5QP.framer-v-17tgl1i .framer-1x6qma7 { flex: 1 0 0px; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	...css5,
	...css3,
	...css4,
	...css2,
	...css,
	...css6,
	'.framer-PG5QP[data-border="true"]::after, .framer-PG5QP [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FrameraLodg8Q9_ = withCSS(Component, css7, "framer-PG5QP");
var stdin_default4 = FrameraLodg8Q9_;
FrameraLodg8Q9_.displayName = "deliveryOptions-Enter";
FrameraLodg8Q9_.defaultProps = {
	height: 736,
	width: 1099,
};
addPropertyControls(FrameraLodg8Q9_, {
	variant: {
		options: ["EjLhfMBMO", "vUZJEEYbi", "F6L4KtJMy", "b1EZjqTWN"],
		optionTitles: ["Default", "PickUp", "Complete", "PickUp Complete"],
		title: "Variant",
		type: ControlType.Enum,
	},
	frReFa6Yb: {
		title: "Click",
		type: ControlType.EventHandler,
	},
	eIIezbLOr: {
		title: "Click 2",
		type: ControlType.EventHandler,
	},
	EVVgSZbMs: {
		title: "Click 3",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FrameraLodg8Q9_,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonCartoonFonts,
		...DeliveryOptionsCompleteFonts,
		...GoogleMapsFonts,
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts6),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:delivery-options-enter
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "fpVdyfuAw",
		name: "Chinese",
		slug: "yue",
		code: "yue-Hant-HK",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders DeliveryOptionsEnterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var delivery_options_enter_default = ComponentWithRoot;
export { delivery_options_enter_default as default };
