// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 826eadcfe2264c6d "Mantra Lingua", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'yue'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Laptop' | 'Tablet' | 'Mobile' // Variant
 * newsletterCTAVisible?: boolean // Newsletter CTA - Visible
 * newsletterCTAColour?: string // Newsletter CTA - Colour
 * footerVisible?: boolean // Footer - Visible
 * colourFooter?: string // Colour - Footer
}} Props

 */
import { stdin_default as stdin_default3 } from "./chunks/chunk-ZW6BU3HM.js";
import "./chunks/chunk-CW34Y26P.js";
import "./chunks/chunk-GU6EMNIV.js";
import "./chunks/chunk-LSDZCXQW.js";
import "./chunks/chunk-NZN6TVQV.js";
import "./chunks/chunk-VZARCJE6.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-KY4VFX4R.js";
import { stdin_default } from "./chunks/chunk-QWKSH5UA.js";
import "./chunks/chunk-YLTGU2H6.js";
import "./chunks/chunk-PXDCO22G.js";
import { routes } from "./chunks/chunk-74LWP5VC.js";

// virtual:footer-cta
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/prkvo5DZnKoQnbUuFolL/Zl3v9RJPW1CZGwaPNU8l/y1Avdx6t1.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	FormContainer,
	FormPlainTextInput,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/P4O4XdQVxNtKyruXlaSH/srErZZYROblJp55f2nTz/lzuW5FMMt.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;General Sans-regular",
	"Inter-Black",
	"Inter-BlackItalic",
	"Inter-BoldItalic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "General Sans",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/MFQT7HFGCR2L5ULQTW6YXYZXXHMPKLJ3/YWQ244D6TACUX5JBKATPOW5I5MGJ3G73/7YY3ZAAE3TRV2LANYOLXNHTPHLXVWTKH.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/mkY5Sgyq51ik0AMrSBwhm9DJg.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/X5hj6qzcHUYv7h1390c8Rhm6550.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/gQhNpS3tN86g8RcVKYUUaKt2oMQ.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cugnVhSraaRyANCaUtI5FV17wk.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/5HcVoGak8k5agFJSaKa4floXVu0.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/rZ5DdENNqIdFTIyQQiP5isO7M.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/P2Bw01CtL0b9wqygO0sSVogWbo.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/05KsVHGDmqXSBXM4yRZ65P8i0s.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/ky8ovPukK4dJ1Pxq74qGhOqCYI.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/vvNSqIj42qeQ2bvCRBIWKHscrc.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/3ZmXbBKToJifDV9gwcifVd1tEY.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/FNfhX3dt4ChuLJq2PwdlxHO7PU.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/gcnfba68tfm7qAyrWRCf9r34jg.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/efTfQcBJ53kM2pB1hezSZ3RDUFs.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
		],
	},
];
var css = [
	`.framer-d0JQL .framer-styles-preset-1hlwkvj:not(.rich-text-wrapper), .framer-d0JQL .framer-styles-preset-1hlwkvj.rich-text-wrapper h4 { --framer-font-family: "General Sans", "General Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", sans-serif; --framer-font-family-bold-italic: "Inter", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 2.25); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1439px) and (min-width: 1200px) { .framer-d0JQL .framer-styles-preset-1hlwkvj:not(.rich-text-wrapper), .framer-d0JQL .framer-styles-preset-1hlwkvj.rich-text-wrapper h4 { --framer-font-family: "General Sans", "General Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", sans-serif; --framer-font-family-bold-italic: "Inter", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 1.8); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 1199px) and (min-width: 0px) { .framer-d0JQL .framer-styles-preset-1hlwkvj:not(.rich-text-wrapper), .framer-d0JQL .framer-styles-preset-1hlwkvj.rich-text-wrapper h4 { --framer-font-family: "General Sans", "General Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", sans-serif; --framer-font-family-bold-italic: "Inter", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 1.58); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: 0em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className = "framer-d0JQL";

// /:https://framerusercontent.com/modules/l7M1Z0Bou65XnntepBFQ/BVzo4fN8fYQpmU2d8TLc/u3ziZcSPf.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"FS;General Sans-semibold",
	"Inter-Black",
	"Inter-BlackItalic",
	"Inter-BoldItalic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "General Sans",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/K46YRH762FH3QJ25IQM3VAXAKCHEXXW4/ISLWQPUZHZF33LRIOTBMFOJL57GBGQ4B/3ZLMEXZEQPLTEPMHTQDAUXP5ZZXCZAEN.woff2",
				weight: "600",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/mkY5Sgyq51ik0AMrSBwhm9DJg.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/X5hj6qzcHUYv7h1390c8Rhm6550.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/gQhNpS3tN86g8RcVKYUUaKt2oMQ.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cugnVhSraaRyANCaUtI5FV17wk.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/5HcVoGak8k5agFJSaKa4floXVu0.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/rZ5DdENNqIdFTIyQQiP5isO7M.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/P2Bw01CtL0b9wqygO0sSVogWbo.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/05KsVHGDmqXSBXM4yRZ65P8i0s.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/ky8ovPukK4dJ1Pxq74qGhOqCYI.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/vvNSqIj42qeQ2bvCRBIWKHscrc.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/3ZmXbBKToJifDV9gwcifVd1tEY.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/FNfhX3dt4ChuLJq2PwdlxHO7PU.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/gcnfba68tfm7qAyrWRCf9r34jg.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/efTfQcBJ53kM2pB1hezSZ3RDUFs.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
		],
	},
];
var css2 = [
	`.framer-Jvch2 .framer-styles-preset-kxlc3y:not(.rich-text-wrapper), .framer-Jvch2 .framer-styles-preset-kxlc3y.rich-text-wrapper h4 { --framer-font-family: "General Sans", "General Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", sans-serif; --framer-font-family-bold-italic: "Inter", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 2.25); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1439px) and (min-width: 1200px) { .framer-Jvch2 .framer-styles-preset-kxlc3y:not(.rich-text-wrapper), .framer-Jvch2 .framer-styles-preset-kxlc3y.rich-text-wrapper h4 { --framer-font-family: "General Sans", "General Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", sans-serif; --framer-font-family-bold-italic: "Inter", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 1.8); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 1199px) and (min-width: 0px) { .framer-Jvch2 .framer-styles-preset-kxlc3y:not(.rich-text-wrapper), .framer-Jvch2 .framer-styles-preset-kxlc3y.rich-text-wrapper h4 { --framer-font-family: "General Sans", "General Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", sans-serif; --framer-font-family-bold-italic: "Inter", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 1.58); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.02em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className2 = "framer-Jvch2";

// /:https://framerusercontent.com/modules/prkvo5DZnKoQnbUuFolL/Zl3v9RJPW1CZGwaPNU8l/y1Avdx6t1.js
var ButtonCartoonFonts = getFonts(stdin_default2);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var FooterFonts = getFonts(stdin_default3);
var cycleOrder = ["loRUXaFM5", "S0c3uHoWI", "aS8Q0mV1a", "ijCI2CRO_"];
var serializationHash = "framer-W6RLr";
var variantClassNames = {
	aS8Q0mV1a: "framer-v-1v0o8jl",
	ijCI2CRO_: "framer-v-5lu3sa",
	loRUXaFM5: "framer-v-ntarmn",
	S0c3uHoWI: "framer-v-12fx8km",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 150,
};
var animation2 = {
	opacity: 1e-3,
	rotate: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition2 = {
	bounce: 0,
	delay: 0.075,
	duration: 0.4,
	type: "spring",
};
var textEffect = {
	effect: animation2,
	tokenization: "word",
	transition: transition2,
	trigger: "onMount",
	type: "appear",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "loRUXaFM5",
	Laptop: "S0c3uHoWI",
	Mobile: "ijCI2CRO_",
	Tablet: "aS8Q0mV1a",
};
var getProps = ({
	colourFooter,
	footerVisible,
	height,
	id,
	newsletterCTAColour,
	newsletterCTAVisible,
	width,
	...props
}) => {
	return {
		...props,
		BiYGHebtf:
			colourFooter ??
			props.BiYGHebtf ??
			"var(--token-18be8aa1-22e1-42de-b67c-9a9ba653a88c, rgb(245, 249, 255))",
		eTP0h26DB: footerVisible ?? props.eTP0h26DB ?? true,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "loRUXaFM5",
		xwSt_T2Ln:
			newsletterCTAColour ??
			props.xwSt_T2Ln ??
			"var(--token-18be8aa1-22e1-42de-b67c-9a9ba653a88c, rgb(245, 249, 255))",
		xx_kfXyoI: newsletterCTAVisible ?? props.xx_kfXyoI ?? true,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		xx_kfXyoI,
		xwSt_T2Ln,
		eTP0h26DB,
		BiYGHebtf,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "loRUXaFM5",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-ntarmn",
							className3,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"loRUXaFM5"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								aS8Q0mV1a: {
									"data-framer-name": "Tablet",
								},
								ijCI2CRO_: {
									"data-framer-name": "Mobile",
								},
								S0c3uHoWI: {
									"data-framer-name": "Laptop",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{xx_kfXyoI && (
							<motion.div
								className={"framer-kf6kfa"}
								data-framer-name={"CTA - Section"}
								layoutDependency={layoutDependency}
								layoutId={"jdymIotLM"}
								style={{
									backgroundColor: xwSt_T2Ln,
								}}
							>
								<motion.div
									className={"framer-1jzmpny"}
									layoutDependency={layoutDependency}
									layoutId={"hAYWSbsPp"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1yq152e"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"hKnoGUYLp"}
										style={{
											"--extracted-1eung3n":
												"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
											"--framer-paragraph-spacing": "0px",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												ijCI2CRO_: {
													children: (
														<React.Fragment>
															<motion.h4
																style={{
																	"--font-selector": "R0Y7Tm90byBTYW5zLTcwMA==",
																	"--framer-font-family":
																		'"Noto Sans", "Noto Sans Placeholder", sans-serif',
																	"--framer-font-size": "24px",
																	"--framer-font-weight": "700",
																	"--framer-letter-spacing": "-0.04em",
																	"--framer-line-height": "120%",
																	"--framer-text-alignment": "center",
																	"--framer-text-color":
																		"var(--extracted-1eung3n, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
																}}
															>
																{
																	"Personalise your Book with any combination of our 75+ Languages"
																}
															</motion.h4>
														</React.Fragment>
													),
													fonts: ["GF;Noto Sans-700"],
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.h4
												className={"framer-styles-preset-1hlwkvj"}
												data-styles-preset={"lzuW5FMMt"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-1eung3n, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
												}}
											>
												{
													"Personalise your Book with any combination of our 75+ Languages"
												}
											</motion.h4>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-17vk0lo"}
									data-framer-name={"Subscribe Section"}
									layoutDependency={layoutDependency}
									layoutId={"MvczNTYN0"}
									style={{
										backgroundColor:
											"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
										borderBottomLeftRadius: 4,
										borderBottomRightRadius: 4,
										borderTopLeftRadius: 4,
										borderTopRightRadius: 4,
									}}
								>
									<MotionDivWithFXWithOptimizedAppearEffect
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										animate={animation}
										className={"framer-1nfe4wp"}
										data-framer-appear-id={"1nfe4wp"}
										data-framer-name={"Content Container"}
										initial={animation1}
										layoutDependency={layoutDependency}
										layoutId={"yW5XeMjBR"}
										optimized={true}
									>
										<motion.div
											className={"framer-1mio3hz"}
											data-framer-name={"Text Content"}
											layoutDependency={layoutDependency}
											layoutId={"gAh5tCc83"}
										>
											<RichText
												__fromCanvasComponent={true}
												className={"framer-l64f63"}
												effect={textEffect}
												fonts={["Inter"]}
												layoutDependency={layoutDependency}
												layoutId={"eIioSB_yV"}
												style={{
													"--extracted-1eung3n":
														"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
													"--framer-link-text-color": "rgb(0, 153, 255)",
													"--framer-link-text-decoration": "underline",
													"--framer-paragraph-spacing": "0px",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.h4
														className={"framer-styles-preset-kxlc3y"}
														data-styles-preset={"u3ziZcSPf"}
														style={{
															"--framer-text-alignment": "center",
															"--framer-text-color":
																"var(--extracted-1eung3n, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
														}}
													>
														{
															"Sign up to our newsletter and get 10% off your first order"
														}
													</motion.h4>
												</React.Fragment>
											</RichText>
										</motion.div>
										<FormContainer
											className={"framer-1kx3ag9"}
											layoutDependency={layoutDependency}
											layoutId={"neVG8t73B"}
											nodeId={"neVG8t73B"}
										>
											{(formState) => (
												<_Fragment>
													<motion.label
														className={"framer-1y58bag"}
														layoutDependency={layoutDependency}
														layoutId={"jBaFDhiVw"}
														style={{
															backgroundColor:
																"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
															borderBottomLeftRadius: 4,
															borderBottomRightRadius: 4,
															borderTopLeftRadius: 4,
															borderTopRightRadius: 4,
														}}
													>
														<FormPlainTextInput
															className={"framer-gph2l5"}
															inputName={"Email"}
															layoutDependency={layoutDependency}
															layoutId={"T1UlI8w22"}
															placeholder={"jane@gmail.com"}
															style={{
																"--framer-input-background":
																	"var(--token-18be8aa1-22e1-42de-b67c-9a9ba653a88c, rgb(242, 246, 255))",
																"--framer-input-border-bottom-width": "1px",
																"--framer-input-border-color":
																	"var(--token-da79aab1-7975-42cb-a714-582054b64ae5, rgb(41, 94, 230))",
																"--framer-input-border-left-width": "1px",
																"--framer-input-border-radius-bottom-left":
																	"4px",
																"--framer-input-border-radius-bottom-right":
																	"4px",
																"--framer-input-border-radius-top-left": "4px",
																"--framer-input-border-radius-top-right": "4px",
																"--framer-input-border-right-width": "1px",
																"--framer-input-border-style": "solid",
																"--framer-input-border-top-width": "1px",
																"--framer-input-font-color":
																	"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
																"--framer-input-icon-color":
																	"rgb(153, 153, 153)",
																"--framer-input-placeholder-color":
																	"var(--token-ff6489d4-75ce-4cd5-b9b8-ecb94f728f08, rgb(151, 151, 151))",
															}}
															type={"email"}
														/>
													</motion.label>
													<ComponentViewportProvider
														height={60}
														width={`calc(min(min(${componentViewport?.width || "100vw"} - 120px, 1920px) - 80px, 1200px) * 0.3)`}
														y={
															(componentViewport?.y || 0) +
															0 +
															(((componentViewport?.height || 920.5) -
																0 -
																450) /
																2 +
																0 +
																0) +
															48 +
															115.2 +
															60 +
															0 +
															0 +
															79.2 +
															0
														}
														{...addPropertyOverrides(
															{
																aS8Q0mV1a: {
																	y:
																		(componentViewport?.y || 0) +
																		0 +
																		(((componentViewport?.height || 1342.5) -
																			0 -
																			450) /
																			2 +
																			0 +
																			0) +
																		48 +
																		115.2 +
																		60 +
																		0 +
																		0 +
																		79.2 +
																		0,
																},
																ijCI2CRO_: {
																	width: `min(min(${componentViewport?.width || "100vw"} - 40px, 1920px) - 80px, 1200px)`,
																	y:
																		(componentViewport?.y || 0) +
																		0 +
																		(((componentViewport?.height || 1945.5) -
																			0 -
																			450) /
																			2 +
																			0 +
																			0) +
																		20 +
																		100.8 +
																		60 +
																		0 +
																		0 +
																		79.2 +
																		0 +
																		80,
																},
																S0c3uHoWI: {
																	y:
																		(componentViewport?.y || 0) +
																		0 +
																		(((componentViewport?.height || 908.5) -
																			0 -
																			450) /
																			2 +
																			0 +
																			0) +
																		48 +
																		115.2 +
																		60 +
																		0 +
																		0 +
																		79.2 +
																		0,
																},
															},
															baseVariant,
															gestureVariant,
														)}
													>
														<SmartComponentScopedContainer
															className={"framer-2f0r9h-container"}
															layoutDependency={layoutDependency}
															layoutId={"x1l7NATIx-container"}
															nodeId={"x1l7NATIx"}
															rendersWithMotion={true}
															scopeId={"y1Avdx6t1"}
														>
															{_jsx(stdin_default2, {
																AhxkQCIUK:
																	"var(--token-b16f50dd-11da-447e-b6e0-1de4e41e94cc, rgb(87, 128, 235))",
																Bs7Kfyol3: "Subscribe",
																bvHLWpZgR: false,
																GbG6B20dD:
																	"var(--token-da79aab1-7975-42cb-a714-582054b64ae5, rgb(41, 94, 230))",
																gHUOQVyAX: false,
																height: "100%",
																id: "x1l7NATIx",
																KIs7LET4E:
																	"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
																layoutId: "x1l7NATIx",
																NILxoTyW_: false,
																PVX37ezAj:
																	"var(--token-39039f4d-55d7-486e-aa29-db8a7c60cd3e, rgb(18, 55, 151))",
																Si2TgLaT3:
																	"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
																style: {
																	height: "100%",
																	width: "100%",
																},
																variant: "d_dQwBXKY",
																width: "100%",
																wnNedC3i2:
																	"var(--token-da79aab1-7975-42cb-a714-582054b64ae5, rgb(41, 94, 230))",
																XGMS85IRk: stdin_default,
																xni3gMFPB: false,
																zatm_emhi: "8px",
															})}
														</SmartComponentScopedContainer>
													</ComponentViewportProvider>
												</_Fragment>
											)}
										</FormContainer>
									</MotionDivWithFXWithOptimizedAppearEffect>
								</motion.div>
							</motion.div>
						)}
						<ComponentViewportProvider
							height={450}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 920.5) - 0 - 450) / 2 + 0 + 0)
							}
							{...addPropertyOverrides(
								{
									aS8Q0mV1a: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 1342.5) - 0 - 450) / 2 +
												0 +
												0),
									},
									ijCI2CRO_: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 1945.5) - 0 - 450) / 2 +
												0 +
												0),
									},
									S0c3uHoWI: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 908.5) - 0 - 450) / 2 +
												0 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainer
								className={"framer-1q043py-container"}
								layoutDependency={layoutDependency}
								layoutId={"v3TfgRKHw-container"}
								nodeId={"v3TfgRKHw"}
								rendersWithMotion={true}
								scopeId={"y1Avdx6t1"}
							>
								{_jsx(stdin_default3, {
									e_6P4xDsy: eTP0h26DB,
									height: "100%",
									id: "v3TfgRKHw",
									layoutId: "v3TfgRKHw",
									style: {
										width: "100%",
									},
									tkjMaCE80: BiYGHebtf,
									variant: "fWysSVmoN",
									width: "100%",
									...addPropertyOverrides(
										{
											aS8Q0mV1a: {
												variant: "DahCfmT91",
											},
											ijCI2CRO_: {
												variant: "IrbMKKnit",
											},
											S0c3uHoWI: {
												variant: "Ecp8qLasM",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-W6RLr.framer-a3jwc7, .framer-W6RLr .framer-a3jwc7 { display: block; }",
	".framer-W6RLr.framer-ntarmn { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 2560px; }",
	".framer-W6RLr .framer-kf6kfa { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: hidden; padding: 48px 60px 48px 60px; position: relative; width: 100%; }",
	".framer-W6RLr .framer-1jzmpny { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; mix-blend-mode: darken; overflow: visible; padding: 24px 40px 24px 40px; position: relative; width: 100%; }",
	".framer-W6RLr .framer-1yq152e, .framer-W6RLr .framer-l64f63 { flex: none; height: auto; overflow: visible; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-W6RLr .framer-17vk0lo { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; max-width: 1920px; overflow: hidden; padding: 60px 40px 60px 40px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-W6RLr .framer-1nfe4wp { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 36px; height: min-content; justify-content: center; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-W6RLr .framer-1mio3hz { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-W6RLr .framer-1kx3ag9 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-W6RLr .framer-1y58bag { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 60px; justify-content: flex-start; padding: 0px; position: relative; width: 1px; }",
	'.framer-W6RLr .framer-gph2l5 { --framer-input-focused-border-color: #0099ff; --framer-input-focused-border-style: solid; --framer-input-focused-border-width: 1px; --framer-input-focused-transition: all 0.3s cubic-bezier(0.44,0,0.56,1) 0s; --framer-input-font-family: "General Sans"; --framer-input-font-letter-spacing: 0em; --framer-input-font-line-height: 1.2em; --framer-input-font-size: 1.13rem; --framer-input-font-weight: 500; --framer-input-padding: 12px; flex: none; height: 60px; position: relative; width: 100%; }',
	".framer-W6RLr .framer-2f0r9h-container { flex: none; height: 60px; position: relative; width: 30%; }",
	".framer-W6RLr .framer-1q043py-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-W6RLr.framer-v-12fx8km.framer-ntarmn { width: 1440px; }",
	".framer-W6RLr.framer-v-1v0o8jl.framer-ntarmn { width: 810px; }",
	".framer-W6RLr.framer-v-5lu3sa.framer-ntarmn { width: 360px; }",
	".framer-W6RLr.framer-v-5lu3sa .framer-kf6kfa { padding: 20px; }",
	".framer-W6RLr.framer-v-5lu3sa .framer-1kx3ag9 { align-content: center; align-items: center; flex-direction: column; }",
	".framer-W6RLr.framer-v-5lu3sa .framer-1y58bag { flex: none; width: 100%; }",
	".framer-W6RLr.framer-v-5lu3sa .framer-2f0r9h-container { width: 100%; }",
	...css,
	...css2,
];
var Framery1Avdx6t1 = withCSS(Component, css3, "framer-W6RLr");
var stdin_default4 = Framery1Avdx6t1;
Framery1Avdx6t1.displayName = "footer+cta";
Framery1Avdx6t1.defaultProps = {
	height: 920.5,
	width: 2560,
};
addPropertyControls(Framery1Avdx6t1, {
	variant: {
		options: ["loRUXaFM5", "S0c3uHoWI", "aS8Q0mV1a", "ijCI2CRO_"],
		optionTitles: ["Desktop", "Laptop", "Tablet", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	xx_kfXyoI: {
		defaultValue: true,
		description: "",
		title: "Newsletter CTA - Visible",
		type: ControlType.Boolean,
	},
	xwSt_T2Ln: {
		defaultValue:
			'var(--token-18be8aa1-22e1-42de-b67c-9a9ba653a88c, rgb(245, 249, 255)) /* {"name":"25"} */',
		title: "Newsletter CTA - Colour",
		type: ControlType.Color,
	},
	eTP0h26DB: {
		defaultValue: true,
		title: "Footer - Visible",
		type: ControlType.Boolean,
	},
	BiYGHebtf: {
		defaultValue:
			'var(--token-18be8aa1-22e1-42de-b67c-9a9ba653a88c, rgb(245, 249, 255)) /* {"name":"25"} */',
		description: "",
		title: "Colour - Footer",
		type: ControlType.Color,
	},
});
addFonts(
	Framery1Avdx6t1,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "Noto Sans",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/notosans/v39/o-0mIpQlx3QUlC5A4PNB6Ryti20_6n1iPHjcz6L1SoM-jCpoiyAaBN9Y41P6zHtY.woff2",
					weight: "700",
				},
				{
					family: "General Sans",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/3RZHWSNONLLWJK3RLPEKUZOMM56GO4LJ/BPDRY7AHVI3MCDXXVXTQQ76H3UXA63S3/SB2OEB6IKZPRR6JT4GFJ2TFT6HBB6AZN.woff2",
					weight: "500",
				},
			],
		},
		...ButtonCartoonFonts,
		...FooterFonts,
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer-cta
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "fpVdyfuAw",
		name: "Chinese",
		slug: "yue",
		code: "yue-Hant-HK",
	},
];
var defaultResponsiveVariants = {
	base: "ijCI2CRO_",
	md: "aS8Q0mV1a",
	xl: "S0c3uHoWI",
	"2xl": "loRUXaFM5",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default4, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterCtaFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default4}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default4);
var footer_cta_default = ComponentWithRoot;
export { footer_cta_default as default };
