// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 826eadcfe2264c6d "Mantra Lingua", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'yue'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Nav Menu' | 'Desktop - Minimal Navbar' | 'Tablet' | 'Tablet - Minimal Navbar' | 'Mobile Closed' | 'Mobile Opended' // Variant
 * linkBooks?: string // Link - Books
 * linkTradeCustomers?: string // Link - Trade Customers
 * linkAuthors?: string // Link - Authors
 * linkBlog?: string // Link - Blog
 * linkBasket?: string // Link - Basket
 * tabNavMenuVariableBooks?: 'Default' | 'Static' // Tab Nav Menu - Variable - Books
 * tabNavMenuVariableExtras?: 'Default' | 'Static' // Tab Nav Menu Variable - Extras
 * tabNavMenuVariableAuthors?: 'Default' | 'Static' // Tab Nav Menu - Variable - Authors
 * tabNavMenuVariableTrade?: 'Default' | 'Static' // Tab Nav Menu - Variable - Trade
 * tabNavMenuVariableBlog?: 'Default' | 'Static' // Tab Nav Menu - Variable - Blog
 * tabNavMenuVariableProfile?: 'Default' | 'Static' // Tab Nav Menu Variable - Profile
}} Props

 */
import { stdin_default as stdin_default4 } from "./chunks/chunk-XKZ7II5O.js";
import "./chunks/chunk-UC6EBGSA.js";
import "./chunks/chunk-SFO5DWNP.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-CW34Y26P.js";
import "./chunks/chunk-C6MNZJBI.js";
import { stdin_default } from "./chunks/chunk-JPUHUUAZ.js";
import "./chunks/chunk-BBXSTD3N.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-KY4VFX4R.js";
import "./chunks/chunk-QWKSH5UA.js";
import "./chunks/chunk-YLTGU2H6.js";
import "./chunks/chunk-PXDCO22G.js";
import { routes } from "./chunks/chunk-74LWP5VC.js";

// virtual:navigation-bar
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/lo37UaHb1c1ezv4N4xiJ/Z8WnrN6h3Dw0ouLDd2hz/e4FBVnf_K.js
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls3,
	ComponentViewportProvider,
	ControlType as ControlType7,
	cx as cx2,
	getFonts,
	getPropertyControls,
	ResolveLinks,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo as useLocaleInfo2,
	useRouter,
	useVariantState,
	withCSS as withCSS3,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/57FhkldN9P7x88MqAEaR/fW26mCIOTpHHBOBnf7GZ/LocaleSelector.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType as ControlType5,
	useLocaleInfo,
	useLocalesForCurrentRoute,
	withCSS,
} from "unframer";
import { useId, useState } from "react";

// /:https://framerusercontent.com/modules/cuKUFdzXlhvw8OVOBeAc/T08RxQJ4qrs7LLc8wx4E/border.js
import { ControlType as e } from "unframer";
function getBorderStyle({
	color: e2,
	width: t = 0,
	widthPerSide: o = false,
	widthTop: d = 0,
	widthRight: r = 0,
	widthBottom: i = 0,
	widthLeft: l = 0,
	style: h = "none",
} = {}) {
	let b = {};
	return (
		e2
			? ((b["--framer-border-color"] = e2),
				(b.borderStyle = h),
				o
					? ((b.borderTopWidth = d),
						(b.borderRightWidth = r),
						(b.borderBottomWidth = i),
						(b.borderLeftWidth = l))
					: ((b.borderTopWidth = t),
						(b.borderRightWidth = t),
						(b.borderBottomWidth = t),
						(b.borderLeftWidth = t)))
			: (b.border = "none"),
		b
	);
}
var borderControls = {
	color: {
		type: e.Color,
		defaultValue: "#444",
	},
	width: {
		type: e.FusedNumber,
		toggleKey: "widthPerSide",
		toggleTitles: ["Width", "Width per side"],
		valueKeys: ["widthTop", "widthRight", "widthBottom", "widthLeft"],
		valueLabels: ["T", "R", "B", "L"],
		defaultValue: 1,
		min: 0,
	},
	style: {
		type: e.Enum,
		options: ["solid", "dashed", "dotted", "double"],
		optionTitles: ["Solid", "Dashed", "Dotted", "double"],
		defaultValue: "solid",
	},
};

// /:https://framerusercontent.com/modules/9muYaW1MvHoRQJ0P7dkP/V2GVvLqiMxXRSxszkCSa/focus.js
import { ControlType } from "unframer";
function getFocusStyle({ color, width, style, offset } = {}) {
	const result = {};
	if (color) {
		result["--framer-focus-outline"] = `${width}px ${style} ${color}`;
		result["--framer-focus-outline-offset"] = `${offset}px`;
	}
	return result;
}
var focusControls = {
	color: {
		type: ControlType.Color,
		defaultValue: "#09f",
	},
	width: {
		type: ControlType.Number,
		displayStepper: true,
		defaultValue: 1,
		min: 0,
	},
	style: {
		type: ControlType.Enum,
		options: ["solid", "dashed", "dotted", "double"],
		optionTitles: ["Solid", "Dashed", "Dotted", "double"],
		defaultValue: "solid",
	},
	offset: {
		type: ControlType.Number,
		displayStepper: true,
	},
};

// /:https://framerusercontent.com/modules/YfmtnpWjJrP37sQ18QUZ/9Y2P24U2SBIbf2fPVsOX/hover.js
import { ControlType as ControlType2 } from "unframer";
function getHoverStyle({ fillColor, textColor, borderColor } = {}) {
	return {
		"--framer-hover-background-color": fillColor,
		"--framer-hover-color": textColor,
		"--framer-hover-border-color": borderColor,
	};
}
var hoverControls = {
	fillColor: {
		type: ControlType2.Color,
		title: "Fill",
		optional: true,
	},
	textColor: {
		type: ControlType2.Color,
		title: "Text",
		optional: true,
	},
	borderColor: {
		type: ControlType2.Color,
		title: "Border",
		optional: true,
	},
};

// /:https://framerusercontent.com/modules/wjZLfSMaP1TvJDu5PCwr/XQ1GMXuIqYrEN1c0R6E5/padding.js
import { ControlType as ControlType3 } from "unframer";
function getPaddingStyle({
	padding = 0,
	paddingPerSide = false,
	paddingTop = 0,
	paddingRight = 0,
	paddingBottom = 0,
	paddingLeft = 0,
} = {}) {
	if (typeof padding === "string") {
		return {
			padding,
		};
	}
	if (paddingPerSide) {
		return {
			paddingTop,
			paddingRight,
			paddingBottom,
			paddingLeft,
		};
	} else {
		return {
			paddingTop: padding,
			paddingRight: padding,
			paddingBottom: padding,
			paddingLeft: padding,
		};
	}
}
var paddingControls = {
	padding: {
		type: ControlType3.Padding,
		defaultValue: "10px",
	},
};

// /:https://framerusercontent.com/modules/N6MwtHbWoiZJNn1xpqxu/ZEWmVGYDUhL44tluQO5y/radius.js
import { ControlType as ControlType4 } from "unframer";
function getRadiusStyle({
	radius = 0,
	radiusPerCorner = false,
	radiusTopLeft = 0,
	radiusTopRight = 0,
	radiusBottomRight = 0,
	radiusBottomLeft = 0,
} = {}) {
	if (typeof radius === "string") {
		return {
			borderRadius: radius,
		};
	}
	const result = {};
	if (radiusPerCorner) {
		result.borderTopLeftRadius = radiusTopLeft;
		result.borderTopRightRadius = radiusTopRight;
		result.borderBottomRightRadius = radiusBottomRight;
		result.borderBottomLeftRadius = radiusBottomLeft;
	} else {
		result.borderTopLeftRadius = radius;
		result.borderTopRightRadius = radius;
		result.borderBottomRightRadius = radius;
		result.borderBottomLeftRadius = radius;
	}
	return result;
}
var radiusControls = {
	radius: {
		type: ControlType4.BorderRadius,
		defaultValue: "10px",
	},
};

// /:https://framerusercontent.com/modules/57FhkldN9P7x88MqAEaR/fW26mCIOTpHHBOBnf7GZ/LocaleSelector.js
var className = "framer-locale-picker";
var IconType;
(function (IconType2) {
	IconType2["Default"] = "default";
	IconType2["Custom"] = "custom";
})(IconType || (IconType = {}));
function Icon({ type, color, image, size }) {
	if (type === "custom" && image) {
		return <img {...image} width={size} height={size} />;
	}
	return (
		<svg
			xmlns={"http://www.w3.org/2000/svg"}
			viewBox={"0 0 256 256"}
			width={size}
			height={size}
			fill={color}
		>
			<path
				d={
					"M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm87.63,96H175.8c-1.41-28.46-10.27-55.47-25.12-77A88.2,88.2,0,0,1,215.63,120ZM128,215.89c-18.73-20.27-30.09-49-31.77-79.89h63.54C158.09,166.87,146.73,195.62,128,215.89ZM96.23,120c1.68-30.87,13-59.62,31.77-79.89,18.73,20.27,30.09,49,31.77,79.89Zm9.09-77C90.47,64.53,81.61,91.54,80.2,120H40.37A88.2,88.2,0,0,1,105.32,43ZM40.37,136H80.2c1.41,28.46,10.27,55.47,25.12,77A88.2,88.2,0,0,1,40.37,136Zm110.31,77c14.85-21.56,23.71-48.57,25.12-77h39.83A88.2,88.2,0,0,1,150.68,213Z"
				}
			/>
		</svg>
	);
}
var CaretType;
(function (CaretType2) {
	CaretType2["Default"] = "default";
	CaretType2["Custom"] = "custom";
})(CaretType || (CaretType = {}));
function Caret({ type, color, image, size }) {
	if (type === "custom" && image) {
		return <img {...image} width={size} height={size} />;
	}
	return (
		<svg
			xmlns={"http://www.w3.org/2000/svg"}
			viewBox={"0 0 12 12"}
			width={size}
			height={size}
		>
			<path
				d={"M 2 4.5 L 6 8.5 L 10 4.5"}
				fill={"none"}
				stroke={color}
				strokeWidth={1.5}
				strokeLinecap={"round"}
				strokeLinejoin={"round"}
			/>
		</svg>
	);
}
var LocaleSelector = withCSS(
	({
		font,
		fillColor,
		textColor,
		icon,
		caret,
		options: { title, gap, border, hover, focus },
		style,
		...props
	}) => {
		const id = useId();
		const { activeLocale, locales: locales2, setLocale } = useLocaleInfo();
		const localesForCurrentRoute = useLocalesForCurrentRoute();
		const activeLocaleId = activeLocale?.id ?? "default";
		const [lastActiveLocaleId, setLastActiveLocaleId] =
			useState(activeLocaleId);
		const [selectedLocaleId, setSelectedLocaleId] = useState(activeLocaleId);
		const selectedLocale = locales2.find(
			(locale) => locale.id === selectedLocaleId,
		);
		if (lastActiveLocaleId !== activeLocaleId) {
			setLastActiveLocaleId(activeLocaleId);
			if (selectedLocaleId !== activeLocaleId) {
				setSelectedLocaleId(activeLocaleId);
			}
		}
		function handleChange(event) {
			const localeId = event.target.value;
			setSelectedLocaleId(localeId);
			const locale = locales2.find((locale2) => locale2.id === localeId);
			setLocale(locale);
		}
		return (
			<div className={className} style={style}>
				<label htmlFor={id}>{"Select Language"}</label>
				<select
					id={id}
					value={selectedLocaleId}
					onChange={handleChange}
					autoComplete={"off"}
				>
					{localesForCurrentRoute.map((locale) => (
						<option value={locale.id}>{locale.name}</option>
					))}
				</select>
				<div
					className={"input"}
					style={{
						...font,
						"--framer-background-color": fillColor,
						"--framer-color": textColor,
						...getPaddingStyle(props),
						...getRadiusStyle(props),
						...getBorderStyle(border),
						...getHoverStyle(hover),
						...getFocusStyle(focus),
						gap,
					}}
				>
					{icon && (
						<div className={"icon"}>
							<Icon {...icon} />
						</div>
					)}
					{title && (
						<div className={"title"}>{selectedLocale?.name ?? "English"}</div>
					)}
					{caret && (
						<div className={"caret"}>
							<Caret {...caret} />
						</div>
					)}
				</div>
			</div>
		);
	},
	[
		`
            .${className} {
                position: relative;
            }
        `,
		`
            .${className} label {
                position: absolute;
                width: 1px;
                height: 1px;
                margin: -1px;
                overflow: hidden;
                white-space: nowrap;
                clip: rect(0 0 0 0);
                clip-path: inset(50%);
            }
        `,
		`
            .${className} select {
                appearance: none;
                position: absolute;
                opacity: 0;
                top: 0;
                right: 0;
                bottom: 0;
                left: 0;
                cursor: inherit;
                width: 100%;
            }
        `,
		`
            .${className} .input {
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100%;
                pointer-events: none;
                overflow: hidden;
                background-color: var(--framer-background-color);
                color: var(--framer-color);
                border-color: var(--framer-border-color);
            }
        `,
		`
            .${className} select:focus-visible + .input  {
                outline: var(--framer-focus-outline, none);
                outline-offset: var(--framer-focus-outline-offset);
            }
        `,
		`
            .${className}:hover .input {
                background-color: var(--framer-hover-background-color, var(--framer-background-color));
                color: var(--framer-hover-color, var(--framer-color));
                border-color: var(--framer-hover-border-color, var(--framer-border-color));
            }
        `,
		`
            .${className} .title {
                flex: 1 1 auto;
                white-space: nowrap;
                text-overflow: ellipsis;
                overflow: hidden;
            }
        `,
		`
            .${className} .icon, .${className} .caret {
                display: flex;
                align-items: center;
            }
        `,
	],
	"framer-library-LocalePicker",
);
LocaleSelector.displayName = "Locale Selector";
addPropertyControls(LocaleSelector, {
	font: {
		// @ts-ignore
		type: ControlType5.Font,
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			fontSize: 14,
			lineHeight: "1.5em",
		},
	},
	fillColor: {
		type: ControlType5.Color,
		title: "Fill",
		optional: true,
		defaultValue: "#eee",
	},
	textColor: {
		type: ControlType5.Color,
		title: "Text",
		defaultValue: "#000",
	},
	...paddingControls,
	...radiusControls,
	icon: {
		type: ControlType5.Object,
		buttonTitle: "Size, Color",
		optional: true,
		controls: {
			type: {
				type: ControlType5.Enum,
				title: "Icon",
				options: Object.values(IconType),
				optionTitles: ["Default", "Custom"],
				displaySegmentedControl: true,
				defaultValue: "default",
			},
			color: {
				type: ControlType5.Color,
				defaultValue: "#000",
				hidden: (props) => props.type !== "default",
			},
			image: {
				type: ControlType5.ResponsiveImage,
				title: "File",
				hidden: (props) => props.type !== "custom",
			},
			size: {
				type: ControlType5.Number,
				displayStepper: true,
				defaultValue: 18,
			},
		},
	},
	caret: {
		type: ControlType5.Object,
		buttonTitle: "Size, Color",
		optional: true,
		controls: {
			type: {
				type: ControlType5.Enum,
				title: "Icon",
				options: Object.values(CaretType),
				optionTitles: ["Default", "Custom"],
				displaySegmentedControl: true,
				defaultValue: "default",
			},
			color: {
				type: ControlType5.Color,
				defaultValue: "#000",
				hidden: (props) => props.type !== "default",
			},
			image: {
				type: ControlType5.ResponsiveImage,
				title: "File",
				hidden: (props) => props.type !== "custom",
			},
			size: {
				type: ControlType5.Number,
				displayStepper: true,
				defaultValue: 12,
			},
		},
		defaultValue: {},
	},
	options: {
		type: ControlType5.Object,
		title: "Options",
		buttonTitle: "Border, Hover",
		controls: {
			title: {
				type: ControlType5.Boolean,
				defaultValue: true,
			},
			gap: {
				type: ControlType5.Number,
				displayStepper: true,
				defaultValue: 5,
			},
			border: {
				type: ControlType5.Object,
				buttonTitle: "Color, Width",
				optional: true,
				controls: borderControls,
			},
			hover: {
				type: ControlType5.Object,
				buttonTitle: "Fill, Border",
				optional: true,
				controls: hoverControls,
			},
			focus: {
				type: ControlType5.Object,
				buttonTitle: "Color, Width",
				controls: focusControls,
			},
		},
	},
});
var stdin_default5 = LocaleSelector;

// /:https://framerusercontent.com/modules/zlQedlx75OSE58IxDEdP/1582OQ5guWePVbagR1aF/r7WsnqDc4.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType6,
	cx,
	motion,
	useSVGTemplate,
	withCSS as withCSS2,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 0 L 19.5 0 L 18.087 10.599 C 18.037 10.972 17.72 11.25 17.344 11.25 L 2.156 11.25 C 1.78 11.25 1.463 10.972 1.413 10.599 Z" fill-opacity="var(--1m6trwb, 0)" fill="var(--21h8s6, rgb(0, 0, 0))" height="11.250000001709282px" id="IfYMh8suP" transform="translate(2.25 8.25)" width="19.5px"/><path d="M 0 0 L 0 5.25" fill="transparent" height="5.25px" id="KqyRRitC_" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(12 11.25)" width="1px"/><path d="M 10.5 6 L 5.25 0 L 0 6" fill="transparent" height="6px" id="t6GnWTUnN" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(6.75 2.25)" width="10.5px"/><path d="M 0.525 0 L 0 5.25" fill="transparent" height="5.25px" id="FXeQ3aroo" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(16.425 11.25)" width="1px"/><path d="M 0 0 L 0.525 5.25" fill="transparent" height="5.25px" id="rWzQnXGxP" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(7.05 11.25)" width="1px"/><path d="M 0 0 L 19.5 0 L 18.087 10.599 C 18.037 10.972 17.72 11.25 17.344 11.25 L 2.156 11.25 C 1.78 11.25 1.463 10.972 1.413 10.599 Z" fill="transparent" height="11.250000001709282px" id="gfZWy625K" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--pgex8v, 1.5)" stroke="var(--21h8s6, rgb(0, 0, 0))" transform="translate(2.25 8.25)" width="19.5px"/></svg>';
var getProps = ({ alpha, color, height, id, width, width1, ...props }) => {
	return {
		...props,
		ezTt3ayMo: color ?? props.ezTt3ayMo ?? "rgb(0, 0, 0)",
		lschgej4H: width1 ?? props.lschgej4H ?? 1.5,
		qxTvv_EBh: alpha ?? props.qxTvv_EBh,
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className2,
		layoutId,
		variant,
		ezTt3ayMo,
		lschgej4H,
		qxTvv_EBh,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("3154016545", svg);
	return (
		<SVG
			{...restProps}
			className={cx("framer-u5zx7", className2)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m6trwb": qxTvv_EBh,
				"--21h8s6": ezTt3ayMo,
				"--pgex8v": lschgej4H,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG>
	);
});
var css = [
	`.framer-u5zx7 { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon2 = withCSS2(Component, css, "framer-u5zx7");
Icon2.displayName = "Basket";
var stdin_default6 = Icon2;
addPropertyControls2(Icon2, {
	ezTt3ayMo: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType6.Color,
	},
	lschgej4H: {
		defaultValue: 1.5,
		displayStepper: true,
		hidden: false,
		max: 6,
		min: 0,
		step: 0.5,
		title: "Width",
		type: ControlType6.Number,
	},
	qxTvv_EBh: {
		defaultValue: 0,
		displayStepper: true,
		hidden: false,
		max: 1,
		min: 0,
		step: 0.1,
		title: "Alpha",
		type: ControlType6.Number,
	},
});

// /:https://framerusercontent.com/modules/lo37UaHb1c1ezv4N4xiJ/Z8WnrN6h3Dw0ouLDd2hz/e4FBVnf_K.js
var MLLogoFonts = getFonts(stdin_default3);
var InlineLinkClickFonts = getFonts(stdin_default);
var NavigationMenusFonts = getFonts(stdin_default4);
var ButtonCartoonFonts = getFonts(stdin_default2);
var LocaleSelectorFonts = getFonts(stdin_default5);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion2.div),
);
var InlineLinkClickControls = getPropertyControls(stdin_default);
var NavigationMenusControls = getPropertyControls(stdin_default4);
var cycleOrder = [
	"PD1ooEsws",
	"bikesCezC",
	"mQQNPh_jO",
	"VeN_Jp3qK",
	"wsAP5oC2k",
	"LjGNQhY3h",
];
var serializationHash = "framer-MISJL";
var variantClassNames = {
	bikesCezC: "framer-v-13uxkkn",
	LjGNQhY3h: "framer-v-8teys4",
	mQQNPh_jO: "framer-v-1cb4tht",
	PD1ooEsws: "framer-v-3gndu3",
	VeN_Jp3qK: "framer-v-15yxel7",
	wsAP5oC2k: "framer-v-1fbfbtd",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 30,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transition2 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: -150,
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var humanReadableEnumMap = {
	Default: "WZmdcxJ14",
	Static: "PdudadWMy",
};
var humanReadableVariantMap = {
	"Desktop - Minimal Navbar": "bikesCezC",
	"Mobile Closed": "wsAP5oC2k",
	"Mobile Opended": "LjGNQhY3h",
	"Nav Menu": "PD1ooEsws",
	"Tablet - Minimal Navbar": "VeN_Jp3qK",
	Tablet: "mQQNPh_jO",
};
var getProps2 = ({
	height,
	id,
	linkAuthors,
	linkBasket,
	linkBlog,
	linkBooks,
	linkTradeCustomers,
	tabNavMenuVariableAuthors,
	tabNavMenuVariableBlog,
	tabNavMenuVariableBooks,
	tabNavMenuVariableExtras,
	tabNavMenuVariableProfile,
	tabNavMenuVariableTrade,
	width,
	...props
}) => {
	return {
		...props,
		aQuSpk5a7:
			humanReadableEnumMap[tabNavMenuVariableBooks] ??
			tabNavMenuVariableBooks ??
			props.aQuSpk5a7 ??
			"WZmdcxJ14",
		beN1GajZe:
			humanReadableEnumMap[tabNavMenuVariableBlog] ??
			tabNavMenuVariableBlog ??
			props.beN1GajZe ??
			"WZmdcxJ14",
		CpPtAzzP_:
			humanReadableEnumMap[tabNavMenuVariableTrade] ??
			tabNavMenuVariableTrade ??
			props.CpPtAzzP_ ??
			"WZmdcxJ14",
		crNNWaxWT: linkBlog ?? props.crNNWaxWT,
		EJgun34j6: linkBasket ?? props.EJgun34j6,
		jZZEViFdv: linkBooks ?? props.jZZEViFdv,
		oRZksPc_V: linkAuthors ?? props.oRZksPc_V,
		TJE92AGBS: linkTradeCustomers ?? props.TJE92AGBS,
		u8ZDGM47N:
			humanReadableEnumMap[tabNavMenuVariableProfile] ??
			tabNavMenuVariableProfile ??
			props.u8ZDGM47N ??
			"WZmdcxJ14",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "PD1ooEsws",
		vD4b3QxhJ:
			humanReadableEnumMap[tabNavMenuVariableAuthors] ??
			tabNavMenuVariableAuthors ??
			props.vD4b3QxhJ ??
			"WZmdcxJ14",
		Xwh4ULfgB:
			humanReadableEnumMap[tabNavMenuVariableExtras] ??
			tabNavMenuVariableExtras ??
			props.Xwh4ULfgB ??
			"WZmdcxJ14",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		jZZEViFdv,
		TJE92AGBS,
		oRZksPc_V,
		crNNWaxWT,
		EJgun34j6,
		aQuSpk5a7,
		Xwh4ULfgB,
		vD4b3QxhJ,
		CpPtAzzP_,
		beN1GajZe,
		u8ZDGM47N,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "PD1ooEsws",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const WYl7gagHB147z8n2 = activeVariantCallback(async (...args) => {
		setVariant("cxxNLFPx7");
	});
	const onTapfthikp = activeVariantCallback(async (...args) => {
		setVariant("LjGNQhY3h");
	});
	const onTap61pj9v = activeVariantCallback(async (...args) => {
		setVariant("wsAP5oC2k");
	});
	const WYl7gagHB61pj9v = activeVariantCallback(async (...args) => {
		setVariant("wsAP5oC2k");
	});
	const KssbMN7jw61pj9v = activeVariantCallback(async (...args) => {
		setVariant("wsAP5oC2k");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (
			["bikesCezC", "VeN_Jp3qK", "wsAP5oC2k", "LjGNQhY3h"].includes(baseVariant)
		)
			return false;
		return true;
	};
	const router = useRouter();
	const isDisplayed1 = () => {
		if (["wsAP5oC2k", "LjGNQhY3h"].includes(baseVariant)) return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "LjGNQhY3h") return true;
		return false;
	};
	const isDisplayed3 = () => {
		if (baseVariant === "LjGNQhY3h") return false;
		return true;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.nav
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-3gndu3",
							className2,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Nav Menu"}
						layoutDependency={layoutDependency}
						layoutId={"PD1ooEsws"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color": "rgba(0, 0, 0, 0.07)",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							backgroundColor:
								"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								bikesCezC: {
									"data-framer-name": "Desktop - Minimal Navbar",
								},
								LjGNQhY3h: {
									"data-framer-name": "Mobile Opended",
								},
								mQQNPh_jO: {
									"data-framer-name": "Tablet",
								},
								VeN_Jp3qK: {
									"data-framer-name": "Tablet - Minimal Navbar",
								},
								wsAP5oC2k: {
									"data-framer-name": "Mobile Closed",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<MotionDivWithFXWithOptimizedAppearEffect
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							animate={animation}
							className={"framer-1k0428"}
							data-framer-appear-id={"1k0428"}
							data-framer-name={"NavBar-Container"}
							initial={animation1}
							layoutDependency={layoutDependency}
							layoutId={"cu8B0of6M"}
							optimized={true}
						>
							<motion2.div
								className={"framer-1q5mjqd"}
								data-framer-name={"ML-Logo-Navigation"}
								layoutDependency={layoutDependency}
								layoutId={"rCJulew6F"}
							>
								<ComponentViewportProvider
									height={75}
									y={(componentViewport?.y || 0) + 24 + 0 + 0}
									{...addPropertyOverrides(
										{
											bikesCezC: {
												y: (componentViewport?.y || 0) + 6 + 6 + 0,
											},
											LjGNQhY3h: {
												y: (componentViewport?.y || 0) + 12 + 0 + 0 + 0,
											},
											mQQNPh_jO: {
												y:
													(componentViewport?.y || 0) +
													12 +
													(((componentViewport?.height || 165) - 24 - 141) / 2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											VeN_Jp3qK: {
												y:
													(componentViewport?.y || 0) +
													12 +
													(((componentViewport?.height || 68) - 24 - 75) / 2 +
														0 +
														0) +
													0 +
													0,
											},
											wsAP5oC2k: {
												y: (componentViewport?.y || 0) + 12 + 0 + 0 + 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1ny6khc-container"}
										layoutDependency={layoutDependency}
										layoutId={"PNpDp2kh6-container"}
										nodeId={"PNpDp2kh6"}
										rendersWithMotion={true}
										scopeId={"e4FBVnf_K"}
									>
										{_jsx3(stdin_default3, {
											height: "100%",
											id: "PNpDp2kh6",
											layoutId: "PNpDp2kh6",
											variant: "E8YMLb30Z",
											width: "100%",
											...addPropertyOverrides(
												{
													bikesCezC: {
														variant: "K8ZcuhBQ8",
													},
													VeN_Jp3qK: {
														variant: "K8ZcuhBQ8",
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion2.div>
							{isDisplayed() && (
								<motion2.div
									className={"framer-11cxlqg"}
									data-framer-name={"Desktop Menu Items"}
									layoutDependency={layoutDependency}
									layoutId={"f53MJwlAF"}
								>
									<ComponentViewportProvider
										height={60}
										width={"180px"}
										{...addPropertyOverrides(
											{
												mQQNPh_jO: {
													width: "120px",
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-35ax9w-container"}
											data-framer-name={"Menu 1"}
											layoutDependency={layoutDependency}
											layoutId={"DS_YbEuP4-container"}
											name={"Menu 1"}
											nodeId={"DS_YbEuP4"}
											rendersWithMotion={true}
											scopeId={"e4FBVnf_K"}
										>
											{_jsx3(stdin_default, {
												cFKLTW2ui:
													"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
												cV3SK9NpK: "Shop Books",
												DFtZVcHAy: jZZEViFdv,
												height: "100%",
												id: "DS_YbEuP4",
												layoutId: "DS_YbEuP4",
												name: "Menu 1",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: aQuSpk5a7,
												width: "100%",
												WYl7gagHB: WYl7gagHB147z8n2,
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "a_wN11s5T",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "dJmVMXVLk",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "xULIHOQdR",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "uZCetkBpX",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "P_tZ17YJt",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "a_wN11s5T",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "dJmVMXVLk",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "xULIHOQdR",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "uZCetkBpX",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "P_tZ17YJt",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks) => (
											<ComponentViewportProvider
												height={60}
												width={"180px"}
												{...addPropertyOverrides(
													{
														mQQNPh_jO: {
															width: "120px",
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-zyxy8u-container"}
													data-framer-name={"Menu 2"}
													layoutDependency={layoutDependency}
													layoutId={"V_42tgFxK-container"}
													name={"Menu 2"}
													nodeId={"V_42tgFxK"}
													rendersWithMotion={true}
													scopeId={"e4FBVnf_K"}
												>
													{_jsx3(stdin_default4, {
														cCecgwObC: "Posters",
														FygszmOKq: false,
														GmLuBCZ1J: "YBJBqrPUT",
														hcrbRRy6x: "Labels",
														height: "100%",
														id: "V_42tgFxK",
														kuqUmwQ1M: "Talking Pack",
														layoutId: "V_42tgFxK",
														lV0evejea: resolvedLinks[3],
														MvJBBGFpV: Xwh4ULfgB,
														name: "Menu 2",
														NjbaehLb0: "flex-start",
														nTw1IW9jW: resolvedLinks[2],
														nyR3FJrim: "Flip Chart Book",
														P7M8M_IoH: "",
														p869_BAhf: resolvedLinks[0],
														R0a3p540D: resolvedLinks[1],
														style: {
															width: "100%",
														},
														V4BcSRkiv: "Shop Extras",
														variant: "jOyNnStFG",
														WFt40b2N0: true,
														width: "100%",
														xp83dGRp3: "Talking Device",
														yrY5D61oV: resolvedLinks[4],
														...addPropertyOverrides(
															{
																mQQNPh_jO: {
																	lV0evejea: resolvedLinks[8],
																	nTw1IW9jW: resolvedLinks[7],
																	p869_BAhf: resolvedLinks[5],
																	R0a3p540D: resolvedLinks[6],
																	yrY5D61oV: resolvedLinks[9],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "S0tss8oiG",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "S0tss8oiG",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks1) => (
											<ComponentViewportProvider
												height={60}
												width={"180px"}
												{...addPropertyOverrides(
													{
														mQQNPh_jO: {
															width: void 0,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<SmartComponentScopedContainer
													className={"framer-qjdlgp-container"}
													data-framer-name={"Menu 4"}
													layoutDependency={layoutDependency}
													layoutId={"IxwOQdUH1-container"}
													name={"Menu 4"}
													nodeId={"IxwOQdUH1"}
													rendersWithMotion={true}
													scopeId={"e4FBVnf_K"}
												>
													{_jsx3(stdin_default, {
														cFKLTW2ui:
															"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
														cV3SK9NpK: "Authors",
														DFtZVcHAy: resolvedLinks1[0],
														height: "100%",
														id: "IxwOQdUH1",
														layoutId: "IxwOQdUH1",
														name: "Menu 4",
														style: {
															height: "100%",
															width: "100%",
														},
														variant: vD4b3QxhJ,
														width: "100%",
														WYl7gagHB: WYl7gagHB147z8n2,
														...addPropertyOverrides(
															{
																mQQNPh_jO: {
																	DFtZVcHAy: resolvedLinks1[1],
																	style: {
																		height: "100%",
																	},
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</SmartComponentScopedContainer>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<ComponentViewportProvider
										height={60}
										width={"180px"}
										{...addPropertyOverrides(
											{
												mQQNPh_jO: {
													width: void 0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-6fm7is-container"}
											data-framer-name={"Menu 3"}
											layoutDependency={layoutDependency}
											layoutId={"bHxkMClav-container"}
											name={"Menu 3"}
											nodeId={"bHxkMClav"}
											rendersWithMotion={true}
											scopeId={"e4FBVnf_K"}
										>
											{_jsx3(stdin_default, {
												cFKLTW2ui:
													"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
												cV3SK9NpK: "Trade Customers",
												DFtZVcHAy: TJE92AGBS,
												height: "100%",
												id: "bHxkMClav",
												layoutId: "bHxkMClav",
												name: "Menu 3",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: CpPtAzzP_,
												width: "100%",
												WYl7gagHB: WYl7gagHB147z8n2,
												...addPropertyOverrides(
													{
														mQQNPh_jO: {
															style: {
																height: "100%",
															},
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={60}
										width={"180px"}
										{...addPropertyOverrides(
											{
												mQQNPh_jO: {
													width: "120px",
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1jmndif-container"}
											data-framer-name={"Menu 5"}
											layoutDependency={layoutDependency}
											layoutId={"wMFTti2Qn-container"}
											name={"Menu 5"}
											nodeId={"wMFTti2Qn"}
											rendersWithMotion={true}
											scopeId={"e4FBVnf_K"}
										>
											{_jsx3(stdin_default, {
												cFKLTW2ui:
													"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
												cV3SK9NpK: "Blog",
												DFtZVcHAy: crNNWaxWT,
												height: "100%",
												id: "wMFTti2Qn",
												layoutId: "wMFTti2Qn",
												name: "Menu 5",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: beN1GajZe,
												width: "100%",
												WYl7gagHB: WYl7gagHB147z8n2,
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion2.div>
							)}
							<motion2.div
								className={"framer-9i0xj"}
								data-framer-name={"Account Section"}
								layoutDependency={layoutDependency}
								layoutId={"bwm5vNcfJ"}
							>
								<ComponentViewportProvider
									height={60}
									y={(componentViewport?.y || 0) + 24 + 15.5 + 0}
									{...addPropertyOverrides(
										{
											bikesCezC: {
												y: (componentViewport?.y || 0) + 6 + 13.5 + 0,
											},
											LjGNQhY3h: {
												y: (componentViewport?.y || 0) + 12 + 0 + 87 + 0,
											},
											mQQNPh_jO: {
												y:
													(componentViewport?.y || 0) +
													12 +
													(((componentViewport?.height || 165) - 24 - 141) / 2 +
														0 +
														0) +
													0 +
													0 +
													0,
											},
											VeN_Jp3qK: {
												y:
													(componentViewport?.y || 0) +
													12 +
													(((componentViewport?.height || 68) - 24 - 75) / 2 +
														0 +
														0) +
													15.5 +
													0,
											},
											wsAP5oC2k: {
												y: (componentViewport?.y || 0) + 12 + 0 + 87 + 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1vkjim8-container"}
										layoutDependency={layoutDependency}
										layoutId={"BUpVSiwCL-container"}
										nodeId={"BUpVSiwCL"}
										rendersWithMotion={true}
										scopeId={"e4FBVnf_K"}
									>
										{_jsx3(stdin_default2, {
											AhxkQCIUK:
												"var(--token-6f8e4360-63dc-4e1a-a557-8cda94b24d0b, rgb(178, 197, 246))",
											Bs7Kfyol3: "Sign up",
											bvHLWpZgR: false,
											GbG6B20dD:
												"var(--token-da79aab1-7975-42cb-a714-582054b64ae5, rgb(41, 94, 230))",
											gHUOQVyAX: true,
											height: "100%",
											id: "BUpVSiwCL",
											kfX7vOPu0: EJgun34j6,
											KIs7LET4E:
												"var(--token-82c2ba29-5908-4d7f-a6b2-a07af22347c1, rgba(255, 255, 255, 0.9))",
											layoutId: "BUpVSiwCL",
											NILxoTyW_: false,
											PVX37ezAj:
												"var(--token-b8caeba6-5a35-4a04-8419-705e033e94ff, rgb(12, 39, 106))",
											Si2TgLaT3:
												"var(--token-82c2ba29-5908-4d7f-a6b2-a07af22347c1, rgba(255, 255, 255, 0.9))",
											variant: "BjleR_aPM",
											width: "100%",
											wnNedC3i2:
												"var(--token-a9ae1342-5a48-44e6-9b22-3ac8d5578f25, rgb(132, 163, 241))",
											XGMS85IRk: stdin_default6,
											xni3gMFPB: false,
											zatm_emhi: "8px",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
								<ResolveLinks
									links={[
										{
											href: {
												webPageId: "AlkZ_qjIz",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "fRm27mBOE",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "x8NnPuh9m",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "AlkZ_qjIz",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "fRm27mBOE",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "x8NnPuh9m",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "AlkZ_qjIz",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "fRm27mBOE",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "x8NnPuh9m",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "AlkZ_qjIz",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "fRm27mBOE",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "x8NnPuh9m",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "AlkZ_qjIz",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "fRm27mBOE",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "x8NnPuh9m",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "AlkZ_qjIz",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "fRm27mBOE",
											},
											implicitPathVariables: void 0,
										},
										{
											href: {
												webPageId: "x8NnPuh9m",
											},
											implicitPathVariables: void 0,
										},
									]}
								>
									{(resolvedLinks2) => (
										<ComponentViewportProvider
											height={60}
											width={"44px"}
											y={(componentViewport?.y || 0) + 24 + 15.5 + 0}
											{...addPropertyOverrides(
												{
													bikesCezC: {
														y: (componentViewport?.y || 0) + 6 + 13.5 + 0,
													},
													LjGNQhY3h: {
														y: (componentViewport?.y || 0) + 12 + 0 + 87 + 0,
													},
													mQQNPh_jO: {
														y:
															(componentViewport?.y || 0) +
															12 +
															(((componentViewport?.height || 165) - 24 - 141) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0,
													},
													VeN_Jp3qK: {
														y:
															(componentViewport?.y || 0) +
															12 +
															(((componentViewport?.height || 68) - 24 - 75) /
																2 +
																0 +
																0) +
															15.5 +
															0,
													},
													wsAP5oC2k: {
														y: (componentViewport?.y || 0) + 12 + 0 + 87 + 0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-1c0lt5-container"}
												data-framer-name={"My Account"}
												layoutDependency={layoutDependency}
												layoutId={"Gbzxv17s_-container"}
												name={"My Account"}
												nodeId={"Gbzxv17s_"}
												rendersWithMotion={true}
												scopeId={"e4FBVnf_K"}
											>
												{_jsx3(stdin_default4, {
													cCecgwObC: "Address Book",
													FygszmOKq: false,
													GmLuBCZ1J: "vtnvGtQyI",
													hcrbRRy6x: "Orders",
													height: "100%",
													id: "Gbzxv17s_",
													kuqUmwQ1M: "",
													layoutId: "Gbzxv17s_",
													MvJBBGFpV: Xwh4ULfgB,
													name: "My Account",
													NjbaehLb0: "flex-start",
													nTw1IW9jW: resolvedLinks2[2],
													nyR3FJrim: "",
													P7M8M_IoH: "",
													p869_BAhf: resolvedLinks2[0],
													R0a3p540D: resolvedLinks2[1],
													style: {
														width: "100%",
													},
													V4BcSRkiv: "My Account",
													variant: "Bot6U51_g",
													WFt40b2N0: true,
													width: "100%",
													xp83dGRp3: "Profile",
													...addPropertyOverrides(
														{
															bikesCezC: {
																nTw1IW9jW: resolvedLinks2[5],
																p869_BAhf: resolvedLinks2[3],
																R0a3p540D: resolvedLinks2[4],
															},
															LjGNQhY3h: {
																KssbMN7jw: void 0,
																nTw1IW9jW: resolvedLinks2[17],
																p869_BAhf: resolvedLinks2[15],
																R0a3p540D: resolvedLinks2[16],
															},
															mQQNPh_jO: {
																NjbaehLb0: "flex-end",
																nTw1IW9jW: resolvedLinks2[8],
																p869_BAhf: resolvedLinks2[6],
																R0a3p540D: resolvedLinks2[7],
															},
															VeN_Jp3qK: {
																NjbaehLb0: "flex-end",
																nTw1IW9jW: resolvedLinks2[11],
																p869_BAhf: resolvedLinks2[9],
																R0a3p540D: resolvedLinks2[10],
															},
															wsAP5oC2k: {
																KssbMN7jw: void 0,
																nTw1IW9jW: resolvedLinks2[14],
																p869_BAhf: resolvedLinks2[12],
																R0a3p540D: resolvedLinks2[13],
															},
														},
														baseVariant,
														gestureVariant,
													),
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</ResolveLinks>
								{isDisplayed1() && (
									<motion2.div
										className={"framer-6w4f9v"}
										data-framer-name={"Mobile - Hamburger"}
										layoutDependency={layoutDependency}
										layoutId={"YN47zqCUF"}
										{...addPropertyOverrides(
											{
												LjGNQhY3h: {
													"data-highlight": true,
													onTap: onTap61pj9v,
												},
												wsAP5oC2k: {
													"data-highlight": true,
													onTap: onTapfthikp,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<motion2.div
											className={"framer-1uz4jxz"}
											data-framer-name={"Icon"}
											layoutDependency={layoutDependency}
											layoutId={"HrAonZfnp"}
										>
											<motion2.div
												className={"framer-l7w3o7"}
												data-framer-name={"Bottom"}
												layoutDependency={layoutDependency}
												layoutId={"saNmgiqUY"}
												style={{
													backgroundColor:
														"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
													borderBottomLeftRadius: 10,
													borderBottomRightRadius: 10,
													borderTopLeftRadius: 10,
													borderTopRightRadius: 10,
												}}
											/>
											<motion2.div
												className={"framer-1xnmtvk"}
												data-framer-name={"Top"}
												layoutDependency={layoutDependency}
												layoutId={"aR3p2wbNx"}
												style={{
													backgroundColor:
														"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
													borderBottomLeftRadius: 10,
													borderBottomRightRadius: 10,
													borderTopLeftRadius: 10,
													borderTopRightRadius: 10,
												}}
											/>
										</motion2.div>
									</motion2.div>
								)}
							</motion2.div>
							{isDisplayed2() && (
								<motion2.div
									className={"framer-1cx0r8s"}
									data-framer-name={"Mobile Menu Items"}
									layoutDependency={layoutDependency}
									layoutId={"QDO8BVn_h"}
								>
									<ComponentViewportProvider
										height={60}
										{...addPropertyOverrides(
											{
												LjGNQhY3h: {
													width: `calc((${componentViewport?.width || "100vw"} - 24px) * 0.9)`,
													y: (componentViewport?.y || 0) + 12 + 0 + 159 + 0 + 0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-izlemr-container"}
											layoutDependency={layoutDependency}
											layoutId={"AWXHihMFB-container"}
											nodeId={"AWXHihMFB"}
											rendersWithMotion={true}
											scopeId={"e4FBVnf_K"}
										>
											{_jsx3(stdin_default, {
												cFKLTW2ui:
													"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
												cV3SK9NpK: "Shop Books",
												DFtZVcHAy: jZZEViFdv,
												height: "100%",
												id: "AWXHihMFB",
												layoutId: "AWXHihMFB",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: aQuSpk5a7,
												width: "100%",
												WYl7gagHB: WYl7gagHB61pj9v,
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={60}
										{...addPropertyOverrides(
											{
												LjGNQhY3h: {
													width: `calc((${componentViewport?.width || "100vw"} - 24px) * 0.9)`,
													y:
														(componentViewport?.y || 0) + 12 + 0 + 159 + 0 + 60,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-n8kt2r-container"}
											data-framer-name={"Shop Extras"}
											layoutDependency={layoutDependency}
											layoutId={"OvFV8uyEn-container"}
											name={"Shop Extras"}
											nodeId={"OvFV8uyEn"}
											rendersWithMotion={true}
											scopeId={"e4FBVnf_K"}
										>
											{_jsx3(stdin_default4, {
												cCecgwObC: "Posters",
												FygszmOKq: false,
												GmLuBCZ1J: "f6DMA4Nq_",
												hcrbRRy6x: "Labels",
												height: "100%",
												id: "OvFV8uyEn",
												KssbMN7jw: KssbMN7jw61pj9v,
												kuqUmwQ1M: "Talking Pack",
												layoutId: "OvFV8uyEn",
												MvJBBGFpV: u8ZDGM47N,
												name: "Shop Extras",
												NjbaehLb0: "flex-start",
												nyR3FJrim: "Flip Chart Book",
												P7M8M_IoH: "-",
												style: {
													width: "100%",
												},
												V4BcSRkiv: "Shop Extras",
												variant: "jOyNnStFG",
												WFt40b2N0: true,
												width: "100%",
												xp83dGRp3: "Talking Device",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={60}
										{...addPropertyOverrides(
											{
												LjGNQhY3h: {
													width: `calc((${componentViewport?.width || "100vw"} - 24px) * 0.9)`,
													y:
														(componentViewport?.y || 0) +
														12 +
														0 +
														159 +
														0 +
														120,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1cqrpq-container"}
											layoutDependency={layoutDependency}
											layoutId={"WD0mNi_Sf-container"}
											nodeId={"WD0mNi_Sf"}
											rendersWithMotion={true}
											scopeId={"e4FBVnf_K"}
										>
											{_jsx3(stdin_default, {
												cFKLTW2ui:
													"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
												cV3SK9NpK: "Learning Resources",
												DFtZVcHAy: oRZksPc_V,
												height: "100%",
												id: "WD0mNi_Sf",
												layoutId: "WD0mNi_Sf",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: vD4b3QxhJ,
												width: "100%",
												WYl7gagHB: WYl7gagHB61pj9v,
												...addPropertyOverrides(
													{
														LjGNQhY3h: {
															cV3SK9NpK: "Authors",
														},
													},
													baseVariant,
													gestureVariant,
												),
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={60}
										{...addPropertyOverrides(
											{
												LjGNQhY3h: {
													width: `calc((${componentViewport?.width || "100vw"} - 24px) * 0.9)`,
													y:
														(componentViewport?.y || 0) +
														12 +
														0 +
														159 +
														0 +
														180,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-o7dgpo-container"}
											layoutDependency={layoutDependency}
											layoutId={"Rn6cvgWhu-container"}
											nodeId={"Rn6cvgWhu"}
											rendersWithMotion={true}
											scopeId={"e4FBVnf_K"}
										>
											{_jsx3(stdin_default, {
												cFKLTW2ui:
													"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
												cV3SK9NpK: "Trade Customers",
												DFtZVcHAy: TJE92AGBS,
												height: "100%",
												id: "Rn6cvgWhu",
												layoutId: "Rn6cvgWhu",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: CpPtAzzP_,
												width: "100%",
												WYl7gagHB: WYl7gagHB61pj9v,
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<ComponentViewportProvider
										height={60}
										{...addPropertyOverrides(
											{
												LjGNQhY3h: {
													width: `calc((${componentViewport?.width || "100vw"} - 24px) * 0.9)`,
													y:
														(componentViewport?.y || 0) +
														12 +
														0 +
														159 +
														0 +
														240,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-1jhqm0o-container"}
											layoutDependency={layoutDependency}
											layoutId={"uJ6LlkVmh-container"}
											nodeId={"uJ6LlkVmh"}
											rendersWithMotion={true}
											scopeId={"e4FBVnf_K"}
										>
											{_jsx3(stdin_default, {
												cFKLTW2ui:
													"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
												cV3SK9NpK: "Blog",
												DFtZVcHAy: crNNWaxWT,
												height: "100%",
												id: "uJ6LlkVmh",
												layoutId: "uJ6LlkVmh",
												style: {
													height: "100%",
													width: "100%",
												},
												variant: beN1GajZe,
												width: "100%",
												WYl7gagHB: WYl7gagHB61pj9v,
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									{isDisplayed3() && (
										<ComponentViewportProvider>
											<SmartComponentScopedContainer
												className={"framer-99v3vf-container"}
												isAuthoredByUser={true}
												isModuleExternal={true}
												layoutDependency={layoutDependency}
												layoutId={"xj3Jj_zZf-container"}
												nodeId={"xj3Jj_zZf"}
												rendersWithMotion={true}
												scopeId={"e4FBVnf_K"}
											>
												{_jsx3(stdin_default5, {
													caret: {
														color: "rgb(0, 0, 0)",
														size: 12,
														type: "default",
													},
													fillColor: "rgb(238, 238, 238)",
													font: {
														fontFamily:
															'"General Sans", "General Sans Placeholder", sans-serif',
														fontSize: "14px",
														fontStyle: "normal",
														fontWeight: 600,
														letterSpacing: "0em",
														lineHeight: "1.5em",
													},
													height: "100%",
													icon: {
														color: "rgb(0, 0, 0)",
														size: 18,
														type: "custom",
													},
													id: "xj3Jj_zZf",
													layoutId: "xj3Jj_zZf",
													options: {
														border: {
															color: "rgb(68, 68, 68)",
															style: "solid",
															width: 1,
															widthBottom: 1,
															widthLeft: 1,
															widthPerSide: false,
															widthRight: 1,
															widthTop: 1,
														},
														focus: {
															color: "rgb(0, 153, 255)",
															offset: 0,
															style: "solid",
															width: 1,
														},
														gap: 5,
														hover: {},
														title: true,
													},
													padding: "10px",
													radius: "4px",
													style: {
														width: "100%",
													},
													textColor: "rgb(0, 0, 0)",
													width: "100%",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									)}
								</motion2.div>
							)}
						</MotionDivWithFXWithOptimizedAppearEffect>
					</motion2.nav>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-MISJL.framer-dz6aml, .framer-MISJL .framer-dz6aml { display: block; }",
	".framer-MISJL.framer-3gndu3 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 24px; position: relative; width: 1600px; }",
	".framer-MISJL .framer-1k0428 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 90%; z-index: 9; }",
	".framer-MISJL .framer-1q5mjqd { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-MISJL .framer-1ny6khc-container, .framer-MISJL .framer-1vkjim8-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-MISJL .framer-11cxlqg { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: wrap; gap: 36px 12px; height: 60px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; z-index: 9; }",
	".framer-MISJL .framer-35ax9w-container, .framer-MISJL .framer-qjdlgp-container, .framer-MISJL .framer-6fm7is-container, .framer-MISJL .framer-1jmndif-container { flex: none; height: 60px; position: relative; width: 180px; }",
	".framer-MISJL .framer-zyxy8u-container { flex: none; height: auto; position: relative; width: 180px; }",
	".framer-MISJL .framer-9i0xj { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: 44px; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 128px; z-index: 10; }",
	".framer-MISJL .framer-1c0lt5-container { flex: none; height: auto; position: relative; width: 44px; }",
	".framer-MISJL .framer-6w4f9v { flex: none; height: 200px; overflow: visible; position: relative; width: 40px; }",
	".framer-MISJL .framer-1uz4jxz { flex: none; height: 34px; left: 0px; overflow: hidden; position: absolute; right: 0px; top: calc(50.00000000000002% - 34px / 2); }",
	".framer-MISJL .framer-l7w3o7 { flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: hidden; position: absolute; top: calc(62.50000000000002% - 2px / 2); width: 20px; will-change: var(--framer-will-change-override, transform); }",
	".framer-MISJL .framer-1xnmtvk { flex: none; height: 2px; left: calc(50.00000000000002% - 20px / 2); overflow: hidden; position: absolute; top: calc(37.50000000000002% - 2px / 2); width: 20px; will-change: var(--framer-will-change-override, transform); }",
	".framer-MISJL .framer-1cx0r8s { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: wrap; gap: 0px 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-MISJL .framer-izlemr-container, .framer-MISJL .framer-1cqrpq-container, .framer-MISJL .framer-o7dgpo-container, .framer-MISJL .framer-1jhqm0o-container { flex: none; height: 60px; position: relative; width: 100%; }",
	".framer-MISJL .framer-n8kt2r-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-MISJL .framer-99v3vf-container { flex: none; height: auto; position: relative; width: 140px; }",
	".framer-MISJL.framer-v-13uxkkn.framer-3gndu3, .framer-MISJL.framer-v-13uxkkn .framer-1k0428 { padding: 6px; }",
	".framer-MISJL.framer-v-13uxkkn .framer-9i0xj { height: min-content; }",
	".framer-MISJL.framer-v-1cb4tht.framer-3gndu3, .framer-MISJL.framer-v-15yxel7.framer-3gndu3 { flex-direction: column; padding: 12px 24px 12px 24px; width: 810px; }",
	".framer-MISJL.framer-v-1cb4tht .framer-1k0428 { align-content: unset; align-items: unset; display: grid; gap: 6px 12px; grid-auto-rows: min-content; grid-template-columns: repeat(3, minmax(50px, 1fr)); grid-template-rows: repeat(2, min-content); justify-content: center; width: 100%; }",
	".framer-MISJL.framer-v-1cb4tht .framer-1q5mjqd { align-self: start; justify-self: start; order: 0; width: 100%; }",
	".framer-MISJL.framer-v-1cb4tht .framer-11cxlqg { align-self: start; flex: none; gap: 24px 24px; grid-column: span 3; justify-self: start; order: 2; width: 100%; }",
	".framer-MISJL.framer-v-1cb4tht .framer-35ax9w-container, .framer-MISJL.framer-v-1cb4tht .framer-zyxy8u-container, .framer-MISJL.framer-v-1cb4tht .framer-1jmndif-container { width: 120px; }",
	".framer-MISJL.framer-v-1cb4tht .framer-qjdlgp-container, .framer-MISJL.framer-v-1cb4tht .framer-6fm7is-container { width: auto; }",
	".framer-MISJL.framer-v-1cb4tht .framer-9i0xj { align-self: start; grid-column: span 2; justify-self: start; order: 1; width: 100%; }",
	".framer-MISJL.framer-v-15yxel7 .framer-1k0428 { width: 100%; }",
	".framer-MISJL.framer-v-15yxel7 .framer-1q5mjqd { order: 0; }",
	".framer-MISJL.framer-v-15yxel7 .framer-9i0xj, .framer-MISJL.framer-v-1fbfbtd .framer-1c0lt5-container, .framer-MISJL.framer-v-8teys4 .framer-1c0lt5-container { order: 2; }",
	".framer-MISJL.framer-v-1fbfbtd.framer-3gndu3, .framer-MISJL.framer-v-8teys4.framer-3gndu3 { padding: 12px; width: 360px; }",
	".framer-MISJL.framer-v-1fbfbtd .framer-1k0428, .framer-MISJL.framer-v-8teys4 .framer-1k0428 { flex-direction: column; gap: 12px; justify-content: flex-start; }",
	".framer-MISJL.framer-v-1fbfbtd .framer-9i0xj, .framer-MISJL.framer-v-8teys4 .framer-9i0xj { height: min-content; justify-content: flex-start; width: 100%; }",
	".framer-MISJL.framer-v-1fbfbtd .framer-1vkjim8-container, .framer-MISJL.framer-v-8teys4 .framer-1vkjim8-container { order: 1; }",
	".framer-MISJL.framer-v-1fbfbtd .framer-6w4f9v, .framer-MISJL.framer-v-8teys4 .framer-6w4f9v { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; order: 0; padding: 8px; width: 1px; }",
	".framer-MISJL.framer-v-1fbfbtd .framer-1uz4jxz, .framer-MISJL.framer-v-8teys4 .framer-1uz4jxz { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; justify-content: center; left: unset; padding: 0px; position: relative; right: unset; top: unset; width: min-content; }",
	".framer-MISJL.framer-v-1fbfbtd .framer-l7w3o7, .framer-MISJL.framer-v-1fbfbtd .framer-1xnmtvk, .framer-MISJL.framer-v-8teys4 .framer-l7w3o7, .framer-MISJL.framer-v-8teys4 .framer-1xnmtvk { left: unset; position: relative; top: unset; }",
	".framer-MISJL.framer-v-8teys4 .framer-1cx0r8s { flex: none; width: 100%; }",
	'.framer-MISJL[data-border="true"]::after, .framer-MISJL [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framere4FBVnf_K = withCSS3(Component2, css2, "framer-MISJL");
var stdin_default7 = Framere4FBVnf_K;
Framere4FBVnf_K.displayName = "navigation-bar";
Framere4FBVnf_K.defaultProps = {
	height: 123,
	width: 1600,
};
addPropertyControls3(Framere4FBVnf_K, {
	variant: {
		options: [
			"PD1ooEsws",
			"bikesCezC",
			"mQQNPh_jO",
			"VeN_Jp3qK",
			"wsAP5oC2k",
			"LjGNQhY3h",
		],
		optionTitles: [
			"Nav Menu",
			"Desktop - Minimal Navbar",
			"Tablet",
			"Tablet - Minimal Navbar",
			"Mobile Closed",
			"Mobile Opended",
		],
		title: "Variant",
		type: ControlType7.Enum,
	},
	jZZEViFdv: {
		description: "",
		title: "Link - Books",
		type: ControlType7.Link,
	},
	TJE92AGBS: {
		description: "",
		title: "Link - Trade Customers",
		type: ControlType7.Link,
	},
	oRZksPc_V: {
		description: "",
		title: "Link - Authors",
		type: ControlType7.Link,
	},
	crNNWaxWT: {
		description: "",
		title: "Link - Blog",
		type: ControlType7.Link,
	},
	EJgun34j6: {
		description: "",
		title: "Link - Basket",
		type: ControlType7.Link,
	},
	aQuSpk5a7: InlineLinkClickControls?.["variant"] && {
		...InlineLinkClickControls["variant"],
		defaultValue: "WZmdcxJ14",
		description: "",
		hidden: void 0,
		title: "Tab Nav Menu - Variable - Books",
	},
	Xwh4ULfgB: NavigationMenusControls?.["MvJBBGFpV"] && {
		...NavigationMenusControls["MvJBBGFpV"],
		defaultValue: "WZmdcxJ14",
		description: "",
		hidden: void 0,
		title: "Tab Nav Menu Variable - Extras",
	},
	vD4b3QxhJ: InlineLinkClickControls?.["variant"] && {
		...InlineLinkClickControls["variant"],
		defaultValue: "WZmdcxJ14",
		description: "",
		hidden: void 0,
		title: "Tab Nav Menu - Variable - Authors",
	},
	CpPtAzzP_: InlineLinkClickControls?.["variant"] && {
		...InlineLinkClickControls["variant"],
		defaultValue: "WZmdcxJ14",
		description: "",
		hidden: void 0,
		title: "Tab Nav Menu - Variable - Trade",
	},
	beN1GajZe: InlineLinkClickControls?.["variant"] && {
		...InlineLinkClickControls["variant"],
		defaultValue: "WZmdcxJ14",
		description: "",
		hidden: void 0,
		title: "Tab Nav Menu - Variable - Blog",
	},
	u8ZDGM47N: NavigationMenusControls?.["MvJBBGFpV"] && {
		...NavigationMenusControls["MvJBBGFpV"],
		defaultValue: "WZmdcxJ14",
		description: void 0,
		hidden: void 0,
		title: "Tab Nav Menu Variable - Profile",
	},
});
addFonts(
	Framere4FBVnf_K,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "General Sans",
					source: "fontshare",
					style: "normal",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/K46YRH762FH3QJ25IQM3VAXAKCHEXXW4/ISLWQPUZHZF33LRIOTBMFOJL57GBGQ4B/3ZLMEXZEQPLTEPMHTQDAUXP5ZZXCZAEN.woff2",
					weight: "600",
				},
			],
		},
		...MLLogoFonts,
		...InlineLinkClickFonts,
		...NavigationMenusFonts,
		...ButtonCartoonFonts,
		...LocaleSelectorFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navigation-bar
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "fpVdyfuAw",
		name: "Chinese",
		slug: "yue",
		code: "yue-Hant-HK",
	},
];
var defaultResponsiveVariants = {
	base: "wsAP5oC2k",
	xl: "mQQNPh_jO",
	"2xl": "PD1ooEsws",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default7, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavigationBarFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default7}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default7);
var navigation_bar_default = ComponentWithRoot;
export { navigation_bar_default as default };
