// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 826eadcfe2264c6d "Mantra Lingua", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'yue'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Closed' | 'Complete - Credit - Debit Card' | 'PayPal' | 'Klarna' | 'Google Pay' | 'Apple Pay' | 'Purchase Order' // Variant
 * visibleTitle?: boolean // Visible - Title
 * buttonLink?: string // Button Link
}} Props

 */
import { stdin_default } from "./chunks/chunk-SYCZ2TZT.js";
import "./chunks/chunk-XE3MKJUU.js";
import "./chunks/chunk-573CM56T.js";
import "./chunks/chunk-IZG75K3H.js";
import "./chunks/chunk-QC5WWKQK.js";
import "./chunks/chunk-VHWSTUA5.js";
import "./chunks/chunk-L3O2CTIU.js";
import "./chunks/chunk-LSDZCXQW.js";
import "./chunks/chunk-UNUFCDMP.js";
import "./chunks/chunk-U2J7FPUL.js";
import "./chunks/chunk-NZN6TVQV.js";
import "./chunks/chunk-VZARCJE6.js";
import "./chunks/chunk-KY4VFX4R.js";
import "./chunks/chunk-QWKSH5UA.js";
import "./chunks/chunk-YLTGU2H6.js";
import { routes } from "./chunks/chunk-74LWP5VC.js";

// virtual:payment
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "fpVdyfuAw",
		name: "Chinese",
		slug: "yue",
		code: "yue-Hant-HK",
	},
];
var defaultResponsiveVariants = {
	base: "htT9bSQ1J",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PaymentFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var payment_default = ComponentWithRoot;
export { payment_default as default };
