// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 826eadcfe2264c6d "Mantra Lingua", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'yue'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Large' | 'Medium' | 'Small' // Variant
 * title?: string // Title
 * briefDescription?: string // Brief Description
 * age?: string // Age
 * visibleAge?: boolean // Visible - Age
 * topics?: string // Topics
 * visibleTopics?: boolean // Visible - Topics
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * backgroundColour?: string // Background Colour
 * link?: string // Link
 * tagFill?: string // Tag Fill
 * tagBorder?: undefined // Tag Border
 * filterAge?: boolean // filterAge
}} Props

 */
import {
	className as className5,
	css as css5,
	fonts as fonts5,
} from "./chunks/chunk-KNVR2RS6.js";
import { stdin_default } from "./chunks/chunk-6GVUBC7U.js";
import { className, css, fonts } from "./chunks/chunk-LA4LVRRP.js";
import {
	className as className4,
	css as css4,
	fonts as fonts4,
} from "./chunks/chunk-U2J7FPUL.js";
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-S2CJ3MVF.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-FIG2JAJT.js";
import { routes } from "./chunks/chunk-74LWP5VC.js";

// virtual:product-card-index
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/JPc8mn5FHIok8FkdCRRO/GKlf5Ouq3O3pNV7f0B98/riM9gEvcB.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ChildrenCanSuspend,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	PathVariablesContext,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useQueryData,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/Cafs7ydN1i1QHqXASlE9/eSyEBQIBNbPfQL6VtODl/YFeffC2MA.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;General Sans-semibold",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts6 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "General Sans",
				source: "fontshare",
				style: "normal",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/K46YRH762FH3QJ25IQM3VAXAKCHEXXW4/ISLWQPUZHZF33LRIOTBMFOJL57GBGQ4B/3ZLMEXZEQPLTEPMHTQDAUXP5ZZXCZAEN.woff2",
				weight: "600",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css6 = [
	`.framer-X1mUH .framer-styles-preset-x6sind:not(.rich-text-wrapper), .framer-X1mUH .framer-styles-preset-x6sind.rich-text-wrapper p { --framer-font-family: "General Sans", "General Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 0.78); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-ff6489d4-75ce-4cd5-b9b8-ecb94f728f08, #979797); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1439px) and (min-width: 1200px) { .framer-X1mUH .framer-styles-preset-x6sind:not(.rich-text-wrapper), .framer-X1mUH .framer-styles-preset-x6sind.rich-text-wrapper p { --framer-font-family: "General Sans", "General Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 0.75); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-ff6489d4-75ce-4cd5-b9b8-ecb94f728f08, #979797); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 1199px) and (min-width: 0px) { .framer-X1mUH .framer-styles-preset-x6sind:not(.rich-text-wrapper), .framer-X1mUH .framer-styles-preset-x6sind.rich-text-wrapper p { --framer-font-family: "General Sans", "General Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: calc(var(--framer-root-font-size, 1rem) * 0.72); --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-ff6489d4-75ce-4cd5-b9b8-ecb94f728f08, #979797); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className6 = "framer-X1mUH";

// /:https://framerusercontent.com/modules/JPc8mn5FHIok8FkdCRRO/GKlf5Ouq3O3pNV7f0B98/riM9gEvcB.js
var enabledGestures = {
	FtYYp1zKd: {
		hover: true,
	},
	qCwPkORfH: {
		hover: true,
	},
	UkkQ5mnct: {
		hover: true,
	},
};
var cycleOrder = ["UkkQ5mnct", "qCwPkORfH", "FtYYp1zKd"];
var serializationHash = "framer-hjeeM";
var variantClassNames = {
	FtYYp1zKd: "framer-v-1tjme3p",
	qCwPkORfH: "framer-v-14hasmi",
	UkkQ5mnct: "framer-v-2vdbav",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1.4,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var QueryData = ({ query: query2, pageSize, children }) => {
	const data = useQueryData(query2);
	return children(data);
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Large: "UkkQ5mnct",
	Medium: "qCwPkORfH",
	Small: "FtYYp1zKd",
};
var getProps = ({
	age,
	backgroundColour,
	briefDescription,
	filterAge,
	height,
	id,
	image,
	link,
	tagBorder,
	tagFill,
	title,
	topics,
	visibleAge,
	visibleTopics,
	width,
	...props
}) => {
	return {
		...props,
		BJGMFF0Yt:
			backgroundColour ??
			props.BJGMFF0Yt ??
			"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
		CfANcg3kG: visibleTopics ?? props.CfANcg3kG ?? true,
		dEa9QjnL8: topics ?? props.dEa9QjnL8 ?? "Topics Categories",
		fBVIunMbr: briefDescription ?? props.fBVIunMbr ?? "Brief Description",
		gjSqcv8GW: filterAge ?? props.gjSqcv8GW ?? true,
		JizR4YgaY: link ?? props.JizR4YgaY,
		lvLi6sMY3:
			tagFill ??
			props.lvLi6sMY3 ??
			"var(--token-a3f7a2b1-5e3b-43d9-b557-1bed23ee7f99, rgb(249, 255, 237))",
		RbZUFrLby: title ?? props.RbZUFrLby ?? "Title",
		RM_E1PZxj: tagBorder ??
			props.RM_E1PZxj ?? {
				borderColor:
					'var(--token-442f1038-441c-4962-9882-2797ec32afe2, rgb(170, 255, 2)) /* {"name":"500"} */',
				borderStyle: "solid",
				borderWidth: 1,
			},
		tON3zOnaK: image ??
			props.tON3zOnaK ?? {
				pixelHeight: 1200,
				pixelWidth: 1200,
				src: "https://framerusercontent.com/images/pXiz6XdnarxuNMBPIg73DnJ9PFA.png?scale-down-to=1024&width=1200&height=1200",
				srcSet:
					"https://framerusercontent.com/images/pXiz6XdnarxuNMBPIg73DnJ9PFA.png?scale-down-to=512&width=1200&height=1200 512w,https://framerusercontent.com/images/pXiz6XdnarxuNMBPIg73DnJ9PFA.png?scale-down-to=1024&width=1200&height=1200 1024w,https://framerusercontent.com/images/pXiz6XdnarxuNMBPIg73DnJ9PFA.png?width=1200&height=1200 1200w",
			},
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "UkkQ5mnct",
		xWxrG2D2W: age ?? props.xWxrG2D2W ?? "Age Categories",
		xYy2xh612: visibleAge ?? props.xYy2xh612 ?? true,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className7,
		layoutId,
		variant,
		RbZUFrLby,
		fBVIunMbr,
		xWxrG2D2W,
		xYy2xh612,
		dEa9QjnL8,
		CfANcg3kG,
		tON3zOnaK,
		BJGMFF0Yt,
		JizR4YgaY,
		lvLi6sMY3,
		RM_E1PZxj,
		gjSqcv8GW,
		av1szNueUt6DFCFPuJ,
		idt6DFCFPuJ,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "UkkQ5mnct",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [
		className3,
		className2,
		className5,
		className4,
		className6,
		className,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={JizR4YgaY}
						motionChild={true}
						nodeId={"UkkQ5mnct"}
						openInNewTab={false}
						preserveParams={gjSqcv8GW}
						scopeId={"riM9gEvcB"}
						smoothScroll={true}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-2vdbav", className7, classNames)} framer-87l8hv`}
							data-framer-name={"Large"}
							layoutDependency={layoutDependency}
							layoutId={"UkkQ5mnct"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "0px",
								"--border-color": "rgba(0, 0, 0, 0)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
								backgroundColor:
									"var(--token-c0a3f8ff-3974-4f67-8022-41338a61d2c3, rgb(250, 250, 250))",
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								borderTopLeftRadius: 0,
								borderTopRightRadius: 0,
								boxShadow: "none",
								...style,
							}}
							variants={{
								"FtYYp1zKd-hover": {
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									borderBottomLeftRadius: 4,
									borderBottomRightRadius: 4,
									borderTopLeftRadius: 4,
									borderTopRightRadius: 4,
									boxShadow:
										"0px 0.6021873017743928px 0.6021873017743928px -1.25px rgba(0, 0, 0, 0.43), 0px 2.288533303243457px 2.288533303243457px -2.5px rgba(0, 0, 0, 0.38), 0px 10px 10px -3.75px rgba(0, 0, 0, 0.15)",
								},
								"qCwPkORfH-hover": {
									"--border-bottom-width": "1px",
									"--border-color":
										"var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255))",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									borderBottomLeftRadius: 4,
									borderBottomRightRadius: 4,
									borderTopLeftRadius: 4,
									borderTopRightRadius: 4,
									boxShadow:
										"0px 0.6021873017743928px 0.6021873017743928px -1.25px rgba(0, 0, 0, 0.43), 0px 2.288533303243457px 2.288533303243457px -2.5px rgba(0, 0, 0, 0.38), 0px 10px 10px -3.75px rgba(0, 0, 0, 0.15)",
								},
								"UkkQ5mnct-hover": {
									backgroundColor:
										"var(--token-ea70bd31-55d0-4593-b38d-3fd8489cd06d, rgb(240, 240, 240))",
								},
							}}
							{...addPropertyOverrides(
								{
									"FtYYp1zKd-hover": {
										"data-border": true,
										"data-framer-name": void 0,
									},
									"qCwPkORfH-hover": {
										"data-border": true,
										"data-framer-name": void 0,
									},
									"UkkQ5mnct-hover": {
										"data-framer-name": void 0,
									},
									FtYYp1zKd: {
										"data-framer-name": "Small",
									},
									qCwPkORfH: {
										"data-framer-name": "Medium",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-ga7zva"}
								layoutDependency={layoutDependency}
								layoutId={"t6DFCFPuJ"}
							>
								<ChildrenCanSuspend>
									<QueryData
										query={{
											from: {
												alias: "t6DFCFPuJ",
												data: stdin_default,
												type: "Collection",
											},
											limit: {
												type: "LiteralValue",
												value: 1,
											},
											select: [
												{
													collection: "t6DFCFPuJ",
													name: "av1szNueU",
													type: "Identifier",
												},
												{
													collection: "t6DFCFPuJ",
													name: "id",
													type: "Identifier",
												},
											],
										}}
									>
										{(collection, paginationInfo, loadMore) => (
											<_Fragment>
												{collection?.map(
													(
														{
															av1szNueU: av1szNueUt6DFCFPuJ2,
															id: idt6DFCFPuJ2,
														},
														index,
													) => {
														av1szNueUt6DFCFPuJ2 ??= "";
														return (
															<LayoutGroup id={`t6DFCFPuJ-${idt6DFCFPuJ2}`}>
																<PathVariablesContext.Provider
																	value={{
																		av1szNueU: av1szNueUt6DFCFPuJ2,
																	}}
																>
																	<motion.div
																		className={"framer-jxwqbo"}
																		layoutDependency={layoutDependency}
																		layoutId={"BTW3TFvCe"}
																		style={{
																			boxShadow:
																				"0px 0.6021873017743928px 2.52918666745245px -0.5px rgba(0, 0, 0, 0.1), 0px 2.288533303243457px 9.61183987362252px -1px rgba(0, 0, 0, 0.12), 0px 10px 42px -1.5px rgba(0, 0, 0, 0.21)",
																		}}
																	>
																		<Image
																			background={{
																				alt: "",
																				fit: "fill",
																				sizes: `calc(${componentViewport?.width || "100vw"} - 24px)`,
																				...toResponsiveImage(tON3zOnaK),
																			}}
																			className={"framer-1u3koj4"}
																			layoutDependency={layoutDependency}
																			layoutId={"vOCAO8oj_"}
																			style={{
																				filter: "none",
																				WebkitFilter: "none",
																			}}
																			variants={{
																				"FtYYp1zKd-hover": {
																					filter: "saturate(1.5)",
																					WebkitFilter: "saturate(1.5)",
																				},
																				"qCwPkORfH-hover": {
																					filter: "saturate(1.5)",
																					WebkitFilter: "saturate(1.5)",
																				},
																				"UkkQ5mnct-hover": {
																					filter: "saturate(1.5)",
																					WebkitFilter: "saturate(1.5)",
																				},
																			}}
																			{...addPropertyOverrides(
																				{
																					"FtYYp1zKd-hover": {
																						background: {
																							alt: "",
																							fit: "fill",
																							loading:
																								getLoadingLazyAtYPosition(
																									(componentViewport?.y || 0) +
																										12 +
																										(((componentViewport?.height ||
																											387) -
																											24 -
																											435.8) /
																											2 +
																											0 +
																											0) +
																										0 +
																										0 +
																										0 +
																										0,
																								),
																							sizes: `calc(${componentViewport?.width || "100vw"} - 24px)`,
																							...toResponsiveImage(tON3zOnaK),
																						},
																					},
																					FtYYp1zKd: {
																						background: {
																							alt: "",
																							fit: "fill",
																							loading:
																								getLoadingLazyAtYPosition(
																									(componentViewport?.y || 0) +
																										12 +
																										(((componentViewport?.height ||
																											385.5) -
																											24 -
																											428.8) /
																											2 +
																											0 +
																											0) +
																										0 +
																										0 +
																										0 +
																										0,
																								),
																							sizes: `calc(${componentViewport?.width || "100vw"} - 24px)`,
																							...toResponsiveImage(tON3zOnaK),
																						},
																					},
																				},
																				baseVariant,
																				gestureVariant,
																			)}
																		/>
																		<motion.div
																			className={"framer-ozx6sh"}
																			data-framer-name={"Content"}
																			layoutDependency={layoutDependency}
																			layoutId={"CkGKmAaWh"}
																			style={{
																				backgroundColor: BJGMFF0Yt,
																			}}
																		>
																			<motion.div
																				className={"framer-hba8bj"}
																				data-framer-name={"Titles"}
																				layoutDependency={layoutDependency}
																				layoutId={"sTpwc3AOo"}
																			>
																				<RichText
																					__fromCanvasComponent={true}
																					className={"framer-1xje61h"}
																					data-framer-name={"Category"}
																					fonts={["Inter"]}
																					layoutDependency={layoutDependency}
																					layoutId={"oM4w12O7q"}
																					style={{
																						"--framer-link-text-color":
																							"rgb(0, 153, 255)",
																						"--framer-link-text-decoration":
																							"underline",
																						"--framer-paragraph-spacing": "0px",
																					}}
																					text={RbZUFrLby}
																					verticalAlignment={"top"}
																					withExternalLayout={true}
																				>
																					<React.Fragment>
																						<motion.h6
																							className={
																								"framer-styles-preset-1ayxqe8"
																							}
																							data-styles-preset={"uOnz884gO"}
																						>
																							{"Title"}
																						</motion.h6>
																					</React.Fragment>
																				</RichText>
																				<RichText
																					__fromCanvasComponent={true}
																					className={"framer-1m8bft0"}
																					data-framer-name={"Category"}
																					fonts={["Inter"]}
																					layoutDependency={layoutDependency}
																					layoutId={"mdrKQ4VzE"}
																					style={{
																						"--framer-link-text-color":
																							"rgb(0, 153, 255)",
																						"--framer-link-text-decoration":
																							"underline",
																						"--framer-paragraph-spacing": "0px",
																					}}
																					text={fBVIunMbr}
																					variants={{
																						FtYYp1zKd: {
																							"--extracted-r6o4lv":
																								"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
																						},
																					}}
																					verticalAlignment={"top"}
																					withExternalLayout={true}
																					{...addPropertyOverrides(
																						{
																							"FtYYp1zKd-hover": {
																								children: (
																									<React.Fragment>
																										<motion.p
																											className={
																												"framer-styles-preset-cszyx0"
																											}
																											data-styles-preset={
																												"EsW1OLiyS"
																											}
																											style={{
																												"--framer-text-color":
																													"var(--extracted-r6o4lv, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
																											}}
																										>
																											{"Age Categories"}
																										</motion.p>
																									</React.Fragment>
																								),
																							},
																							FtYYp1zKd: {
																								children: (
																									<React.Fragment>
																										<motion.p
																											className={
																												"framer-styles-preset-d0omem"
																											}
																											data-styles-preset={
																												"KFDdGWegZ"
																											}
																											style={{
																												"--framer-text-color":
																													"var(--extracted-r6o4lv, var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0)))",
																											}}
																										>
																											{"Brief Description"}
																										</motion.p>
																									</React.Fragment>
																								),
																							},
																						},
																						baseVariant,
																						gestureVariant,
																					)}
																				>
																					<React.Fragment>
																						<motion.p
																							className={
																								"framer-styles-preset-12vbl8y"
																							}
																							data-styles-preset={"SDB9Xu_eE"}
																						>
																							{"Age Categories"}
																						</motion.p>
																					</React.Fragment>
																				</RichText>
																			</motion.div>
																			<motion.div
																				className={"framer-1rueraf"}
																				data-framer-name={"Tags"}
																				layoutDependency={layoutDependency}
																				layoutId={"ed4ahqom4"}
																			>
																				{xYy2xh612 && (
																					<motion.div
																						className={"framer-qetuw5"}
																						data-border={true}
																						data-framer-name={"Age Category 1"}
																						layoutDependency={layoutDependency}
																						layoutId={"VcmBottdD"}
																						style={{
																							"--border-bottom-width":
																								(RM_E1PZxj.borderBottomWidth ??
																									RM_E1PZxj.borderWidth) + "px",
																							"--border-color":
																								RM_E1PZxj.borderColor,
																							"--border-left-width":
																								(RM_E1PZxj.borderLeftWidth ??
																									RM_E1PZxj.borderWidth) + "px",
																							"--border-right-width":
																								(RM_E1PZxj.borderRightWidth ??
																									RM_E1PZxj.borderWidth) + "px",
																							"--border-style":
																								RM_E1PZxj.borderStyle,
																							"--border-top-width":
																								(RM_E1PZxj.borderTopWidth ??
																									RM_E1PZxj.borderWidth) + "px",
																							backgroundColor: lvLi6sMY3,
																							borderBottomLeftRadius: 100,
																							borderBottomRightRadius: 100,
																							borderTopLeftRadius: 100,
																							borderTopRightRadius: 100,
																						}}
																					>
																						<RichText
																							__fromCanvasComponent={true}
																							className={"framer-rg4ewe"}
																							data-framer-name={"Data"}
																							fonts={["Inter"]}
																							layoutDependency={
																								layoutDependency
																							}
																							layoutId={"bIasf4c8W"}
																							style={{
																								"--extracted-r6o4lv":
																									"var(--token-f1b3bf75-c360-438d-85f6-a8fea6ee37b9, rgb(68, 102, 0))",
																								"--framer-link-text-color":
																									"rgb(0, 153, 255)",
																								"--framer-link-text-decoration":
																									"underline",
																								"--framer-paragraph-spacing":
																									"0px",
																							}}
																							text={xWxrG2D2W}
																							verticalAlignment={"top"}
																							withExternalLayout={true}
																							{...addPropertyOverrides(
																								{
																									"FtYYp1zKd-hover": {
																										children: (
																											<React.Fragment>
																												<motion.p
																													className={
																														"framer-styles-preset-nuxwjb"
																													}
																													data-styles-preset={
																														"h0dXlAkFF"
																													}
																												>
																													{"Age Categories"}
																												</motion.p>
																											</React.Fragment>
																										),
																									},
																									FtYYp1zKd: {
																										children: (
																											<React.Fragment>
																												<motion.p
																													className={
																														"framer-styles-preset-nuxwjb"
																													}
																													data-styles-preset={
																														"h0dXlAkFF"
																													}
																													style={{
																														"--framer-text-color":
																															"var(--extracted-r6o4lv, var(--token-f1b3bf75-c360-438d-85f6-a8fea6ee37b9, rgb(68, 102, 0)))",
																													}}
																												>
																													{"Age Categories"}
																												</motion.p>
																											</React.Fragment>
																										),
																									},
																								},
																								baseVariant,
																								gestureVariant,
																							)}
																						>
																							<React.Fragment>
																								<motion.p
																									className={
																										"framer-styles-preset-x6sind"
																									}
																									data-styles-preset={
																										"YFeffC2MA"
																									}
																									style={{
																										"--framer-text-color":
																											"var(--extracted-r6o4lv, var(--token-f1b3bf75-c360-438d-85f6-a8fea6ee37b9, rgb(68, 102, 0)))",
																									}}
																								>
																									{"Age Categories"}
																								</motion.p>
																							</React.Fragment>
																						</RichText>
																					</motion.div>
																				)}
																				{CfANcg3kG && (
																					<motion.div
																						className={"framer-13j1pi5"}
																						data-border={true}
																						data-framer-name={
																							"Topic Category 1"
																						}
																						layoutDependency={layoutDependency}
																						layoutId={"o6gr4O1rv"}
																						style={{
																							"--border-bottom-width":
																								(RM_E1PZxj.borderBottomWidth ??
																									RM_E1PZxj.borderWidth) + "px",
																							"--border-color":
																								RM_E1PZxj.borderColor,
																							"--border-left-width":
																								(RM_E1PZxj.borderLeftWidth ??
																									RM_E1PZxj.borderWidth) + "px",
																							"--border-right-width":
																								(RM_E1PZxj.borderRightWidth ??
																									RM_E1PZxj.borderWidth) + "px",
																							"--border-style":
																								RM_E1PZxj.borderStyle,
																							"--border-top-width":
																								(RM_E1PZxj.borderTopWidth ??
																									RM_E1PZxj.borderWidth) + "px",
																							backgroundColor: lvLi6sMY3,
																							borderBottomLeftRadius: 100,
																							borderBottomRightRadius: 100,
																							borderTopLeftRadius: 100,
																							borderTopRightRadius: 100,
																						}}
																					>
																						<RichText
																							__fromCanvasComponent={true}
																							className={"framer-nm16jl"}
																							data-framer-name={"Data"}
																							fonts={["Inter"]}
																							layoutDependency={
																								layoutDependency
																							}
																							layoutId={"Vgqy8e_yO"}
																							style={{
																								"--extracted-r6o4lv":
																									"var(--token-f1b3bf75-c360-438d-85f6-a8fea6ee37b9, rgb(68, 102, 0))",
																								"--framer-link-text-color":
																									"rgb(0, 153, 255)",
																								"--framer-link-text-decoration":
																									"underline",
																								"--framer-paragraph-spacing":
																									"0px",
																							}}
																							text={dEa9QjnL8}
																							verticalAlignment={"top"}
																							withExternalLayout={true}
																							{...addPropertyOverrides(
																								{
																									"FtYYp1zKd-hover": {
																										children: (
																											<React.Fragment>
																												<motion.p
																													className={
																														"framer-styles-preset-nuxwjb"
																													}
																													data-styles-preset={
																														"h0dXlAkFF"
																													}
																												>
																													{"Topics Categories"}
																												</motion.p>
																											</React.Fragment>
																										),
																									},
																									FtYYp1zKd: {
																										children: (
																											<React.Fragment>
																												<motion.p
																													className={
																														"framer-styles-preset-nuxwjb"
																													}
																													data-styles-preset={
																														"h0dXlAkFF"
																													}
																													style={{
																														"--framer-text-color":
																															"var(--extracted-r6o4lv, var(--token-f1b3bf75-c360-438d-85f6-a8fea6ee37b9, rgb(68, 102, 0)))",
																													}}
																												>
																													{"Topics Categories"}
																												</motion.p>
																											</React.Fragment>
																										),
																									},
																								},
																								baseVariant,
																								gestureVariant,
																							)}
																						>
																							<React.Fragment>
																								<motion.p
																									className={
																										"framer-styles-preset-x6sind"
																									}
																									data-styles-preset={
																										"YFeffC2MA"
																									}
																									style={{
																										"--framer-text-color":
																											"var(--extracted-r6o4lv, var(--token-f1b3bf75-c360-438d-85f6-a8fea6ee37b9, rgb(68, 102, 0)))",
																									}}
																								>
																									{"Topics Categories"}
																								</motion.p>
																							</React.Fragment>
																						</RichText>
																					</motion.div>
																				)}
																			</motion.div>
																		</motion.div>
																	</motion.div>
																</PathVariablesContext.Provider>
															</LayoutGroup>
														);
													},
												)}
											</_Fragment>
										)}
									</QueryData>
								</ChildrenCanSuspend>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css7 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-hjeeM.framer-87l8hv, .framer-hjeeM .framer-87l8hv { display: block; }",
	".framer-hjeeM.framer-2vdbav { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 12px; position: relative; text-decoration: none; width: 480px; }",
	".framer-hjeeM .framer-ga7zva { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
	".framer-hjeeM .framer-jxwqbo { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: 100%; }",
	".framer-hjeeM .framer-1u3koj4 { flex: none; height: 380px; position: relative; width: 100%; }",
	".framer-hjeeM .framer-ozx6sh { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 14px; height: min-content; justify-content: flex-start; padding: 16px 24px 16px 24px; position: relative; width: 100%; }",
	".framer-hjeeM .framer-hba8bj { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-hjeeM .framer-1xje61h, .framer-hjeeM .framer-1m8bft0 { flex: none; height: auto; overflow: visible; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-hjeeM .framer-1rueraf { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: wrap; gap: 8px 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-hjeeM .framer-qetuw5, .framer-hjeeM .framer-13j1pi5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 3px 12px 3px 12px; position: relative; width: min-content; z-index: 1; }",
	".framer-hjeeM .framer-rg4ewe, .framer-hjeeM .framer-nm16jl { flex: none; height: auto; overflow: visible; position: relative; white-space: pre; width: auto; }",
	".framer-hjeeM.framer-v-14hasmi.framer-2vdbav { width: 360px; }",
	".framer-hjeeM.framer-v-14hasmi .framer-1u3koj4 { height: 330px; }",
	".framer-hjeeM.framer-v-14hasmi .framer-ozx6sh { padding: 16px; }",
	".framer-hjeeM.framer-v-1tjme3p.framer-2vdbav { width: 280px; }",
	".framer-hjeeM.framer-v-1tjme3p .framer-1u3koj4 { aspect-ratio: 1.2190476190476192 / 1; height: var(--framer-aspect-ratio-supported, 210px); }",
	".framer-hjeeM.framer-v-1tjme3p .framer-ozx6sh { padding: 18px; }",
	".framer-hjeeM.framer-v-1tjme3p .framer-1rueraf { flex-direction: column; }",
	...css3,
	...css2,
	...css5,
	...css4,
	...css6,
	...css,
	'.framer-hjeeM[data-border="true"]::after, .framer-hjeeM [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerriM9gEvcB = withCSS(Component, css7, "framer-hjeeM");
var stdin_default2 = FramerriM9gEvcB;
FramerriM9gEvcB.displayName = "productCard-Index";
FramerriM9gEvcB.defaultProps = {
	height: 527,
	width: 480,
};
addPropertyControls(FramerriM9gEvcB, {
	variant: {
		options: ["UkkQ5mnct", "qCwPkORfH", "FtYYp1zKd"],
		optionTitles: ["Large", "Medium", "Small"],
		title: "Variant",
		type: ControlType.Enum,
	},
	RbZUFrLby: {
		defaultValue: "Title",
		description: "",
		displayTextArea: false,
		placeholder: "",
		title: "Title",
		type: ControlType.String,
	},
	fBVIunMbr: {
		defaultValue: "Brief Description",
		description: "",
		displayTextArea: false,
		placeholder: "",
		title: "Brief Description",
		type: ControlType.String,
	},
	xWxrG2D2W: {
		defaultValue: "Age Categories",
		description: "",
		displayTextArea: false,
		placeholder: "",
		title: "Age",
		type: ControlType.String,
	},
	xYy2xh612: {
		defaultValue: true,
		description: "",
		title: "Visible - Age",
		type: ControlType.Boolean,
	},
	dEa9QjnL8: {
		defaultValue: "Topics Categories",
		description: "",
		displayTextArea: false,
		placeholder: "",
		title: "Topics",
		type: ControlType.String,
	},
	CfANcg3kG: {
		defaultValue: true,
		title: "Visible - Topics",
		type: ControlType.Boolean,
	},
	tON3zOnaK: {
		__defaultAssetReference:
			"data:framer/asset-reference,pXiz6XdnarxuNMBPIg73DnJ9PFA.png?originalFilename=QmUCSbYUXZEpgWwdDYNenS5XD4APUpXPbwCCeNx3ksaEGH%3Fauto%3Dformat%26h%3D1200.png&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	BJGMFF0Yt: {
		defaultValue:
			'var(--token-97eb4699-db62-4c1e-b48b-45bc7205d9de, rgb(255, 255, 255)) /* {"name":"25"} */',
		description: "",
		title: "Background Colour",
		type: ControlType.Color,
	},
	JizR4YgaY: {
		title: "Link",
		type: ControlType.Link,
	},
	lvLi6sMY3: {
		defaultValue:
			'var(--token-a3f7a2b1-5e3b-43d9-b557-1bed23ee7f99, rgb(249, 255, 237)) /* {"name":"25"} */',
		description: "",
		title: "Tag Fill",
		type: ControlType.Color,
	},
	RM_E1PZxj: {
		defaultValue: {
			borderColor:
				'var(--token-442f1038-441c-4962-9882-2797ec32afe2, rgb(170, 255, 2)) /* {"name":"500"} */',
			borderStyle: "solid",
			borderWidth: 1,
		},
		description: "",
		title: "Tag Border",
		type: ControlType.Border,
	},
	gjSqcv8GW: {
		defaultValue: true,
		description: "To Filter Ages",
		title: "filterAge",
		type: ControlType.Boolean,
	},
});
addFonts(
	FramerriM9gEvcB,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts6),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:product-card-index
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "fpVdyfuAw",
		name: "Chinese",
		slug: "yue",
		code: "yue-Hant-HK",
	},
];
var defaultResponsiveVariants = {
	base: "UkkQ5mnct",
	"2xl": "FtYYp1zKd",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProductCardIndexFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var product_card_index_default = ComponentWithRoot;
export { product_card_index_default as default };
