// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 826eadcfe2264c6d "Mantra Lingua", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'yue'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Large' | 'Medium' | 'Small' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * title?: string // Title
 * price?: string // Price
 * briefDescription?: string // Brief Description
 * buttonTitle?: string // Button Title
 * buttonVariant?: 'Defualt' | 'Pressed' | 'Option Static Click' | 'OPT2 - Pressed' // Button - Variant
 * iconVisible?: boolean // Icon Visible
 * iconSelect?: undefined // Icon Select
 * click?: Function // Click
 * titlePressed?: string // Title - Pressed
 * direction?: 'Horizontal' | 'Vertical' // Direction
}} Props

 */
import { stdin_default } from "./chunks/chunk-7H3DKY6Q.js";
import "./chunks/chunk-KNVR2RS6.js";
import "./chunks/chunk-6GVUBC7U.js";
import "./chunks/chunk-TTUKMUMC.js";
import "./chunks/chunk-NWJBMNYA.js";
import "./chunks/chunk-LSDZCXQW.js";
import "./chunks/chunk-S2CJ3MVF.js";
import { routes } from "./chunks/chunk-74LWP5VC.js";

// virtual:product-card-upsell
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "fpVdyfuAw",
		name: "Chinese",
		slug: "yue",
		code: "yue-Hant-HK",
	},
];
var defaultResponsiveVariants = {
	base: "ITWZyYxtW",
	"2xl": "S6ZSYF4Ih",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProductCardUpsellFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var product_card_upsell_default = ComponentWithRoot;
export { product_card_upsell_default as default };
