// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 826eadcfe2264c6d "Mantra Lingua", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'yue'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'On' | 'Off' | 'On / Disabled' | 'Off / Disabled' // Variant
 * color?: string // Color
 * background?: string // Background
}} Props

 */
import { routes } from "./chunks/chunk-74LWP5VC.js";

// virtual:radio-button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/0R2FOh4DOiJLwwS2IPxW/Ncn5MPIixNw3qQQGQhor/grs3mwIqr.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	VLuQPa8Od: {
		hover: true,
	},
	zMQKTR1pB: {
		hover: true,
	},
};
var cycleOrder = ["zMQKTR1pB", "VLuQPa8Od", "c_3lxgK3K", "e_pacDO43"];
var serializationHash = "framer-8RrLk";
var variantClassNames = {
	c_3lxgK3K: "framer-v-1jfu9ra",
	e_pacDO43: "framer-v-1n5ym60",
	VLuQPa8Od: "framer-v-1eptoi8",
	zMQKTR1pB: "framer-v-gfbvmj",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Off / Disabled": "e_pacDO43",
	"On / Disabled": "c_3lxgK3K",
	Off: "VLuQPa8Od",
	On: "zMQKTR1pB",
};
var getProps = ({ background, color, height, id, width, ...props }) => {
	return {
		...props,
		QLN6MPHwU:
			background ??
			props.QLN6MPHwU ??
			"var(--token-f463e262-e656-4699-9b0f-08f0bb459b35, rgb(250, 250, 250))",
		Rd347vBIu:
			color ??
			props.Rd347vBIu ??
			"var(--token-334ec294-103c-4e28-a9b8-6b5039fe5924, rgb(0, 153, 255))",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "zMQKTR1pB",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		Rd347vBIu,
		QLN6MPHwU,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "zMQKTR1pB",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapmq10ty = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("VLuQPa8Od");
	});
	const onTapuu4jrc = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("zMQKTR1pB");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-gfbvmj",
							className,
							classNames,
						)}
						data-framer-name={"On"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"zMQKTR1pB"}
						onTap={onTapmq10ty}
						ref={refBinding}
						style={{
							backgroundColor: QLN6MPHwU,
							borderBottomLeftRadius: 10,
							borderBottomRightRadius: 10,
							borderTopLeftRadius: 10,
							borderTopRightRadius: 10,
							boxShadow: "none",
							opacity: 1,
							...style,
						}}
						variants={{
							"VLuQPa8Od-hover": {
								boxShadow: "none",
								opacity: 1,
							},
							"zMQKTR1pB-hover": {
								boxShadow: "none",
								opacity: 1,
							},
							c_3lxgK3K: {
								backgroundColor: "rgb(245, 245, 245)",
								opacity: 0.5,
							},
							e_pacDO43: {
								backgroundColor: "rgb(245, 245, 245)",
								boxShadow: "inset 0px 0px 0px 0px rgb(255, 170, 0)",
								opacity: 0.5,
							},
							VLuQPa8Od: {
								backgroundColor: "rgb(245, 245, 245)",
							},
						}}
						{...addPropertyOverrides(
							{
								"VLuQPa8Od-hover": {
									"data-framer-name": void 0,
								},
								"zMQKTR1pB-hover": {
									"data-framer-name": void 0,
								},
								c_3lxgK3K: {
									"data-framer-name": "On / Disabled",
									"data-highlight": void 0,
									onTap: void 0,
								},
								e_pacDO43: {
									"data-framer-name": "Off / Disabled",
									"data-highlight": void 0,
									onTap: void 0,
								},
								VLuQPa8Od: {
									"data-framer-name": "Off",
									onTap: onTapuu4jrc,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1dnszay"}
							layoutDependency={layoutDependency}
							layoutId={"JIlybh2Ib"}
							style={{
								backgroundColor: Rd347vBIu,
								borderBottomLeftRadius: "100%",
								borderBottomRightRadius: "100%",
								borderTopLeftRadius: "100%",
								borderTopRightRadius: "100%",
								boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.15)",
							}}
							transformTemplate={transformTemplate1}
							variants={{
								e_pacDO43: {
									backgroundColor: "rgba(255, 255, 255, 0)",
									boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0)",
								},
								VLuQPa8Od: {
									backgroundColor: "rgba(255, 255, 255, 0)",
									boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0)",
								},
							}}
						/>
						<motion.div
							className={"framer-rtxjo2"}
							layoutDependency={layoutDependency}
							layoutId={"EjYfy5Pkd"}
							style={{
								backgroundColor: "rgb(255, 255, 255)",
								borderBottomLeftRadius: 5,
								borderBottomRightRadius: 5,
								borderTopLeftRadius: 5,
								borderTopRightRadius: 5,
								boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.15)",
							}}
							variants={{
								"VLuQPa8Od-hover": {
									backgroundColor: "rgb(255, 255, 255)",
									boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.15)",
								},
								VLuQPa8Od: {
									backgroundColor: "rgba(255, 255, 255, 0)",
									boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0)",
								},
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-8RrLk.framer-fc5mhi, .framer-8RrLk .framer-fc5mhi { display: block; }",
	".framer-8RrLk.framer-gfbvmj { cursor: pointer; height: 20px; overflow: hidden; position: relative; width: 20px; will-change: var(--framer-will-change-override, transform); }",
	".framer-8RrLk .framer-1dnszay { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 20px); left: 50%; overflow: visible; position: absolute; top: 50%; width: 20px; }",
	".framer-8RrLk .framer-rtxjo2 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 10px); left: 5px; overflow: visible; position: absolute; top: 5px; width: 10px; }",
	".framer-8RrLk.framer-v-1eptoi8.framer-gfbvmj, .framer-8RrLk.framer-v-gfbvmj.hover.framer-gfbvmj { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 20px); }",
	".framer-8RrLk.framer-v-1eptoi8 .framer-1dnszay, .framer-8RrLk.framer-v-1n5ym60 .framer-1dnszay { height: var(--framer-aspect-ratio-supported, 2px); width: 2px; }",
	".framer-8RrLk.framer-v-1eptoi8 .framer-rtxjo2 { height: var(--framer-aspect-ratio-supported, 4px); left: 8px; top: 8px; width: 4px; }",
	".framer-8RrLk.framer-v-1jfu9ra.framer-gfbvmj, .framer-8RrLk.framer-v-1n5ym60.framer-gfbvmj { aspect-ratio: 1 / 1; cursor: unset; height: var(--framer-aspect-ratio-supported, 20px); }",
	".framer-8RrLk.framer-v-1eptoi8.hover .framer-rtxjo2 { height: var(--framer-aspect-ratio-supported, 10px); left: 5px; top: 5px; width: 10px; }",
	".framer-8RrLk.framer-v-gfbvmj.hover .framer-rtxjo2 { height: var(--framer-aspect-ratio-supported, 8px); left: 6px; top: 6px; width: 8px; }",
];
var Framergrs3mwIqr = withCSS(Component, css, "framer-8RrLk");
var stdin_default = Framergrs3mwIqr;
Framergrs3mwIqr.displayName = "radioButton";
Framergrs3mwIqr.defaultProps = {
	height: 20,
	width: 20,
};
addPropertyControls(Framergrs3mwIqr, {
	variant: {
		options: ["zMQKTR1pB", "VLuQPa8Od", "c_3lxgK3K", "e_pacDO43"],
		optionTitles: ["On", "Off", "On / Disabled", "Off / Disabled"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Rd347vBIu: {
		defaultValue:
			'var(--token-334ec294-103c-4e28-a9b8-6b5039fe5924, rgb(0, 153, 255)) /* {"name":"Primary"} */',
		title: "Color",
		type: ControlType.Color,
	},
	QLN6MPHwU: {
		defaultValue:
			"var(--token-f463e262-e656-4699-9b0f-08f0bb459b35, rgb(250, 250, 250))",
		title: "Background",
		type: ControlType.Color,
	},
});
addFonts(
	Framergrs3mwIqr,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:radio-button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "fpVdyfuAw",
		name: "Chinese",
		slug: "yue",
		code: "yue-Hant-HK",
	},
];
var defaultResponsiveVariants = {
	base: "VLuQPa8Od",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders RadioButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var radio_button_default = ComponentWithRoot;
export { radio_button_default as default };
