// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 826eadcfe2264c6d "Mantra Lingua", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'yue'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' // Variant
 * backgroundColour1?: string // Background - Colour - 1
 * backgroundColour2?: string // Background - Colour - 2
 * backgroundColour3?: string // Background - Colour - 3
}} Props

 */
import { stdin_default } from "./chunks/chunk-IXW6I6Z7.js";
import "./chunks/chunk-D53GR4VG.js";
import "./chunks/chunk-QWKSH5UA.js";
import { routes } from "./chunks/chunk-74LWP5VC.js";

// virtual:sliding-headerx3
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/6Hiv3ed5bTsKRsiNNmo7/YEAJWjvvZXfXdnfaBDPl/SJXSykrde.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext,
} from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/zvkTOpMSuRzRhLzZZIwG/vzgdvq3ezmf3RWurtT17/SlideShow.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { resize } from "@motionone/dom";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import {
	animate,
	LayoutGroup,
	mix,
	motion,
	frame,
	useInView,
	useMotionValue,
	useTransform,
	wrap,
} from "unframer";
import {
	Children,
	cloneElement,
	forwardRef,
	memo,
	startTransition,
	useCallback,
	useEffect as useEffect2,
	useLayoutEffect,
	useMemo,
	useRef,
	useState as useState2,
} from "react";

// /:https://framerusercontent.com/modules/V9ryrjN5Am9WM1dJeyyJ/GzHgU466IQmt8g4qOKj8/UsePageVisibility.js
import { useState, useEffect } from "react";
var isBrowser = () => typeof document === "object";
function usePageVisibility() {
	if (!isBrowser()) return;
	const [isVisible, setIsVisible] = useState(!document.hidden);
	useEffect(() => {
		const onVisibilityChange = () => setIsVisible(!document.hidden);
		document.addEventListener("visibilitychange", onVisibilityChange, false);
		return () => {
			document.removeEventListener("visibilitychange", onVisibilityChange);
		};
	}, []);
	return isVisible;
}

// /:https://framerusercontent.com/modules/zvkTOpMSuRzRhLzZZIwG/vzgdvq3ezmf3RWurtT17/SlideShow.js
function awaitRefCallback(element, controller) {
	let refCallbackResolve;
	let current = element.current;
	Object.defineProperty(element, "current", {
		get() {
			return current;
		},
		set(node) {
			current = node;
			if (node === null) {
				controller.abort();
				return;
			}
			refCallbackResolve?.(node);
		},
		configurable: true,
	});
	if (current) return current;
	const refCallbackPromise = new Promise((resolve, reject) => {
		refCallbackResolve = resolve;
		controller.signal.addEventListener("abort", reject);
	}).catch(() => {});
	return refCallbackPromise;
}
var OPACITY_0 = 1e-3;
function Slideshow(props) {
	const {
		slots = [],
		startFrom,
		direction,
		effectsOptions,
		autoPlayControl,
		dragControl,
		alignment,
		gap,
		padding,
		paddingPerSide,
		paddingTop,
		paddingRight,
		paddingBottom,
		paddingLeft,
		itemAmount,
		fadeOptions,
		intervalControl,
		transitionControl,
		arrowOptions,
		borderRadius,
		progressOptions,
		style,
	} = props;
	const {
		effectsOpacity,
		effectsScale,
		effectsRotate,
		effectsPerspective,
		effectsHover,
		playOffscreen,
	} = effectsOptions;
	const { fadeContent, overflow, fadeWidth, fadeInset, fadeAlpha } =
		fadeOptions;
	const {
		showMouseControls,
		arrowSize,
		arrowRadius,
		arrowFill,
		leftArrow,
		rightArrow,
		arrowShouldSpace = true,
		arrowShouldFadeIn = false,
		arrowPosition,
		arrowPadding,
		arrowGap,
		arrowPaddingTop,
		arrowPaddingRight,
		arrowPaddingBottom,
		arrowPaddingLeft,
	} = arrowOptions;
	const {
		showProgressDots,
		dotSize,
		dotsInset,
		dotsRadius,
		dotsPadding,
		dotsGap,
		dotsFill,
		dotsBackground,
		dotsActiveOpacity,
		dotsOpacity,
		dotsBlur,
	} = progressOptions;
	const paddingValue = paddingPerSide
		? `${paddingTop}px ${paddingRight}px ${paddingBottom}px ${paddingLeft}px`
		: `${padding}px`;
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	const filteredSlots = slots.filter(Boolean);
	const amountChildren = Children.count(filteredSlots);
	const hasChildren = amountChildren > 0;
	const isHorizontal = direction === "left" || direction === "right";
	const isInverted = direction === "right" || direction === "bottom";
	if (!hasChildren) {
		return (
			<section style={placeholderStyles}>
				<div style={emojiStyles}>{"\u2B50\uFE0F"}</div>
				<p style={titleStyles}>{"Connect to Content"}</p>
				<p style={subtitleStyles}>
					{"Add layers or components to make infinite auto-playing slideshows."}
				</p>
			</section>
		);
	}
	const parentRef = useRef(null);
	const childrenRef = useMemo(() => {
		return [
			{
				current: null,
			},
			{
				current: null,
			},
		];
	}, [filteredSlots]);
	const timeoutRef = useRef(void 0);
	const [size, setSize] = useState2({
		parent: null,
		children: null,
		item: null,
		itemWidth: null,
		itemHeight: null,
		viewportLength: null,
	});
	const [isHovering, setIsHovering] = useState2(false);
	const [shouldPlayOnHover, setShouldPlayOnHover] = useState2(autoPlayControl);
	const [isMouseDown, setIsMouseDown] = useState2(false);
	const [isResizing, setIsResizing] = useState2(false);
	let dupedChildren = [];
	let duplicateBy = 4;
	if (isCanvas) {
		duplicateBy = 1;
	}
	const measure = useCallback(() => {
		if (!parentRef.current) return;
		const firstChild = childrenRef[0].current;
		const lastChild = childrenRef[1].current;
		const parentLength = isHorizontal
			? parentRef.current.offsetWidth
			: parentRef.current.offsetHeight;
		const start = firstChild
			? isHorizontal
				? firstChild.offsetLeft
				: firstChild.offsetTop
			: 0;
		const end = lastChild
			? isHorizontal
				? lastChild.offsetLeft + lastChild.offsetWidth
				: lastChild.offsetTop + lastChild.offsetHeight
			: 0;
		const childrenLength = end - start + gap;
		const itemSize = firstChild
			? isHorizontal
				? firstChild.offsetWidth
				: firstChild.offsetHeight
			: 0;
		const itemWidth = firstChild ? firstChild.offsetWidth : 0;
		const itemHeight = firstChild ? firstChild.offsetHeight : 0;
		const viewportLength = isHorizontal
			? Math.max(
					document.documentElement.clientWidth || 0,
					window.innerWidth || 0,
					parentRef.current.offsetWidth,
				)
			: Math.max(
					document.documentElement.clientHeight || 0,
					window.innerHeight || 0,
					parentRef.current.offsetHeight,
				);
		setSize({
			parent: parentLength,
			children: childrenLength,
			item: itemSize,
			itemWidth,
			itemHeight,
			viewportLength,
		});
	}, []);
	const scheduleMeasure = useCallback(async () => {
		const controller = new AbortController();
		const [firstChild, lastChild] = childrenRef;
		if (!isCanvas && (!firstChild.current || !lastChild.current))
			try {
				await Promise.all([
					awaitRefCallback(firstChild, controller),
					amountChildren > 1 ? awaitRefCallback(lastChild, controller) : true,
				]);
			} catch {
				controller.abort();
			}
		frame.read(measure, false, true);
	}, [measure]);
	useLayoutEffect(() => {
		scheduleMeasure();
	}, [itemAmount]);
	const initialResize = useRef(true);
	useEffect2(() => {
		return resize(parentRef.current, ({ contentSize }) => {
			if (!initialResize.current && (contentSize.width || contentSize.height)) {
				scheduleMeasure();
				startTransition(() => setIsResizing(true));
			}
			initialResize.current = false;
		});
	}, []);
	useEffect2(() => {
		if (isResizing) {
			const timer = setTimeout(
				() => startTransition(() => setIsResizing(false)),
				500,
			);
			return () => clearTimeout(timer);
		}
	}, [isResizing]);
	const totalItems = filteredSlots?.length;
	const childrenSize = isCanvas ? 0 : size?.children;
	const itemWithGap = size?.item + gap;
	const itemOffset = startFrom * itemWithGap;
	const [currentItem, setCurrentItem] = useState2(startFrom + totalItems);
	const [isDragging, setIsDragging] = useState2(false);
	if (isCanvas) {
		if (currentItem !== startFrom) {
			setCurrentItem(startFrom);
		}
	}
	const visibilityRef = useRef(null);
	const isInView = useInView(visibilityRef);
	const isVisible = usePageVisibility() && isInView;
	const factor = isInverted ? 1 : -1;
	const xOrY = useMotionValue(childrenSize);
	const canvasPosition = isHorizontal
		? -startFrom * (size?.itemWidth + gap)
		: -startFrom * (size?.itemHeight + gap);
	const newPosition = () => factor * currentItem * itemWithGap;
	const wrappedValue = !isCanvas
		? useTransform(xOrY, (value) => {
				const wrapped = wrap(-childrenSize, -childrenSize * 2, value);
				return isNaN(wrapped) ? 0 : wrapped;
			})
		: 0;
	const wrappedIndex = wrap(0, totalItems, currentItem);
	const wrappedIndexInverted = wrap(0, -totalItems, currentItem);
	useLayoutEffect(() => {
		if (size?.children === null) return;
		if (!initialResize.current && isResizing) {
			xOrY.set(newPosition());
		}
	}, [
		size,
		childrenSize,
		factor,
		itemOffset,
		currentItem,
		itemWithGap,
		isResizing,
	]);
	const switchPages = () => {
		if (isCanvas || !hasChildren || !size.parent || isDragging) return;
		if (xOrY.get() !== newPosition()) {
			animate(xOrY, newPosition(), transitionControl);
		}
		if (autoPlayControl && shouldPlayOnHover && (playOffscreen || isVisible)) {
			timeoutRef.current = setTimeout(() => {
				startTransition(() => setCurrentItem((item) => item + 1));
				switchPages();
			}, intervalControl * 1e3);
		}
	};
	const setDelta = (delta, transition = false) => {
		if (!isInverted) {
			if (transition)
				startTransition(() => setCurrentItem((item) => item + delta));
			else setCurrentItem((item) => item + delta);
		} else {
			if (transition)
				startTransition(() => setCurrentItem((item) => item - delta));
			else setCurrentItem((item) => item - delta);
		}
	};
	const setPage = (index) => {
		const currentItemWrapped = wrap(0, totalItems, currentItem);
		const currentItemWrappedInvert = wrap(0, -totalItems, currentItem);
		const goto = index - currentItemWrapped;
		const gotoInverted = index - Math.abs(currentItemWrappedInvert);
		if (!isInverted) {
			startTransition(() => setCurrentItem((item) => item + goto));
		} else {
			startTransition(() => setCurrentItem((item) => item - gotoInverted));
		}
	};
	const handleDragStart = () => {
		startTransition(() => setIsDragging(true));
	};
	const handleDragEnd = (event, { offset, velocity }) => {
		startTransition(() => setIsDragging(false));
		const offsetXorY = isHorizontal ? offset.x : offset.y;
		const velocityThreshold = 200;
		const velocityXorY = isHorizontal ? velocity.x : velocity.y;
		const isHalfOfNext = offsetXorY < -size.item / 2;
		const isHalfOfPrev = offsetXorY > size.item / 2;
		const normalizedOffset = Math.abs(offsetXorY);
		const itemDelta = Math.round(normalizedOffset / size.item);
		const itemDeltaFromOne = itemDelta === 0 ? 1 : itemDelta;
		if (velocityXorY > velocityThreshold) {
			setDelta(-itemDeltaFromOne, true);
		} else if (velocityXorY < -velocityThreshold) {
			setDelta(itemDeltaFromOne, true);
		} else {
			if (isHalfOfNext) {
				setDelta(itemDelta, true);
			}
			if (isHalfOfPrev) {
				setDelta(-itemDelta, true);
			}
		}
	};
	useEffect2(() => {
		if (!isVisible || isResizing || amountChildren <= 1) return;
		switchPages();
		return () => timeoutRef.current && clearTimeout(timeoutRef.current);
	}, [dupedChildren, isVisible, isResizing]);
	let childCounter = 0;
	const columnOrRowValue = `calc(${100 / itemAmount}% - ${gap}px + ${gap / itemAmount}px)`;
	for (let index = 0; index < duplicateBy; index++) {
		dupedChildren = dupedChildren.concat(
			Children.map(filteredSlots, (child, childIndex) => {
				let ref;
				if (index === 0) {
					if (childIndex === 0) {
						ref = childrenRef[0];
					} else if (childIndex === filteredSlots.length - 1) {
						ref = childrenRef[1];
					}
				}
				return (
					<Slide
						ref={ref}
						slideKey={index + childIndex + "lg"}
						index={index}
						width={
							isHorizontal
								? itemAmount > 1
									? columnOrRowValue
									: "100%"
								: "100%"
						}
						height={
							!isHorizontal
								? itemAmount > 1
									? columnOrRowValue
									: "100%"
								: "100%"
						}
						size={size}
						child={child}
						numChildren={filteredSlots?.length}
						wrappedValue={wrappedValue}
						childCounter={childCounter++}
						gap={gap}
						isCanvas={isCanvas}
						isHorizontal={isHorizontal}
						effectsOpacity={effectsOpacity}
						effectsScale={effectsScale}
						effectsRotate={effectsRotate}
					>
						{index + childIndex}
					</Slide>
				);
			}),
		);
	}
	const fadeDirection = isHorizontal ? "to right" : "to bottom";
	const fadeWidthStart = fadeWidth / 2;
	const fadeWidthEnd = 100 - fadeWidth / 2;
	const fadeInsetStart = clamp(fadeInset, 0, fadeWidthStart);
	const fadeInsetEnd = 100 - fadeInset;
	const fadeMask = `linear-gradient(${fadeDirection}, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetStart}%, rgba(0, 0, 0, 1) ${fadeWidthStart}%, rgba(0, 0, 0, 1) ${fadeWidthEnd}%, rgba(0, 0, 0, ${fadeAlpha}) ${fadeInsetEnd}%)`;
	const dots = [];
	const dotsBlurStyle = {};
	if (showProgressDots) {
		for (let i = 0; i < filteredSlots?.length; i++) {
			dots.push(
				<Dot
					dotStyle={{
						...dotStyle,
						width: dotSize,
						height: dotSize,
						backgroundColor: dotsFill,
					}}
					buttonStyle={baseButtonStyles}
					selectedOpacity={dotsActiveOpacity}
					opacity={dotsOpacity}
					onClick={() => setPage(i)}
					wrappedIndex={wrappedIndex}
					wrappedIndexInverted={wrappedIndexInverted}
					total={totalItems}
					index={i}
					gap={dotsGap}
					padding={dotsPadding}
					isHorizontal={isHorizontal}
					isInverted={isInverted}
				/>,
			);
		}
		if (dotsBlur > 0) {
			dotsBlurStyle.backdropFilter =
				dotsBlurStyle.WebkitBackdropFilter = `blur(${dotsBlur}px)`;
		}
	}
	const dragProps = dragControl
		? {
				drag: isHorizontal ? "x" : "y",
				onDragStart: handleDragStart,
				onDragEnd: handleDragEnd,
				dragDirectionLock: true,
				values: {
					x: xOrY,
					y: xOrY,
				},
				dragMomentum: false,
			}
		: {};
	const arrowHasTop =
		arrowPosition === "top-left" ||
		arrowPosition === "top-mid" ||
		arrowPosition === "top-right";
	const arrowHasBottom =
		arrowPosition === "bottom-left" ||
		arrowPosition === "bottom-mid" ||
		arrowPosition === "bottom-right";
	const arrowHasLeft =
		arrowPosition === "top-left" || arrowPosition === "bottom-left";
	const arrowHasRight =
		arrowPosition === "top-right" || arrowPosition === "bottom-right";
	const arrowHasMid =
		arrowPosition === "top-mid" ||
		arrowPosition === "bottom-mid" ||
		arrowPosition === "auto";
	return (
		<section
			style={{
				...containerStyle,
				padding: paddingValue,
				WebkitMaskImage: fadeContent ? fadeMask : void 0,
				maskImage: fadeContent ? fadeMask : void 0,
				opacity: size?.item !== null ? 1 : OPACITY_0,
				userSelect: "none",
			}}
			onMouseEnter={() => {
				setIsHovering(true);
				if (!effectsHover) setShouldPlayOnHover(false);
			}}
			onMouseLeave={() => {
				setIsHovering(false);
				if (!effectsHover) setShouldPlayOnHover(true);
			}}
			onMouseDown={(event) => {
				event.preventDefault();
				startTransition(() => setIsMouseDown(true));
			}}
			onMouseUp={() => startTransition(() => setIsMouseDown(false))}
			ref={visibilityRef}
		>
			<div
				style={{
					width: "100%",
					height: "100%",
					margin: 0,
					padding: "inherit",
					position: "absolute",
					inset: 0,
					overflow: overflow ? "visible" : "hidden",
					borderRadius,
					userSelect: "none",
					perspective: isCanvas ? "none" : effectsPerspective,
				}}
			>
				<motion.ul
					ref={parentRef}
					{...dragProps}
					style={{
						...containerStyle,
						gap,
						placeItems: alignment,
						x: isHorizontal ? (isCanvas ? canvasPosition : wrappedValue) : 0,
						y: !isHorizontal ? (isCanvas ? canvasPosition : wrappedValue) : 0,
						flexDirection: isHorizontal ? "row" : "column",
						transformStyle:
							effectsRotate !== 0 && !isCanvas ? "preserve-3d" : void 0,
						cursor: dragControl ? (isMouseDown ? "grabbing" : "grab") : "auto",
						userSelect: "none",
						...style,
					}}
				>
					{dupedChildren}
				</motion.ul>
			</div>
			<fieldset
				style={{
					...controlsStyles,
				}}
				aria-label={"Slideshow pagination controls"}
				className={"framer--slideshow-controls"}
			>
				<motion.div
					style={{
						position: "absolute",
						display: "flex",
						flexDirection: isHorizontal ? "row" : "column",
						justifyContent: arrowShouldSpace ? "space-between" : "center",
						gap: arrowShouldSpace ? "unset" : arrowGap,
						opacity: arrowShouldFadeIn ? OPACITY_0 : 1,
						alignItems: "center",
						inset: arrowPadding,
						top: arrowShouldSpace
							? arrowPadding
							: arrowHasTop
								? arrowPaddingTop
								: "unset",
						left: arrowShouldSpace
							? arrowPadding
							: arrowHasLeft
								? arrowPaddingLeft
								: arrowHasMid
									? 0
									: "unset",
						right: arrowShouldSpace
							? arrowPadding
							: arrowHasRight
								? arrowPaddingRight
								: arrowHasMid
									? 0
									: "unset",
						bottom: arrowShouldSpace
							? arrowPadding
							: arrowHasBottom
								? arrowPaddingBottom
								: "unset",
					}}
					animate={
						arrowShouldFadeIn && {
							opacity: isHovering ? 1 : OPACITY_0,
						}
					}
					transition={transitionControl}
				>
					<motion.button
						type={"button"}
						style={{
							...baseButtonStyles,
							backgroundColor: arrowFill,
							width: arrowSize,
							height: arrowSize,
							borderRadius: arrowRadius,
							rotate: !isHorizontal ? 90 : 0,
							display: showMouseControls ? "block" : "none",
							pointerEvents: "auto",
						}}
						onClick={() => setDelta(-1, true)}
						aria-label={"Previous"}
						whileTap={{
							scale: 0.9,
						}}
						transition={{
							duration: 0.15,
						}}
					>
						<img
							decoding={"async"}
							width={arrowSize}
							height={arrowSize}
							src={
								leftArrow ||
								"https://framerusercontent.com/images/6tTbkXggWgQCAJ4DO2QEdXXmgM.svg"
							}
							alt={"Back Arrow"}
						/>
					</motion.button>
					<motion.button
						type={"button"}
						style={{
							...baseButtonStyles,
							backgroundColor: arrowFill,
							width: arrowSize,
							height: arrowSize,
							borderRadius: arrowRadius,
							rotate: !isHorizontal ? 90 : 0,
							display: showMouseControls ? "block" : "none",
							pointerEvents: "auto",
						}}
						onClick={() => setDelta(1, true)}
						aria-label={"Next"}
						whileTap={{
							scale: 0.9,
						}}
						transition={{
							duration: 0.15,
						}}
					>
						<img
							decoding={"async"}
							width={arrowSize}
							height={arrowSize}
							src={
								rightArrow ||
								"https://framerusercontent.com/images/11KSGbIZoRSg4pjdnUoif6MKHI.svg"
							}
							alt={"Next Arrow"}
						/>
					</motion.button>
				</motion.div>
				{dots.length > 1 ? (
					<div
						style={{
							...dotsContainerStyle,
							left: isHorizontal ? "50%" : dotsInset,
							top: !isHorizontal ? "50%" : "unset",
							transform: isHorizontal ? "translateX(-50%)" : "translateY(-50%)",
							flexDirection: isHorizontal ? "row" : "column",
							bottom: isHorizontal ? dotsInset : "unset",
							borderRadius: dotsRadius,
							backgroundColor: dotsBackground,
							userSelect: "none",
							...dotsBlurStyle,
						}}
					>
						{dots}
					</div>
				) : null}
			</fieldset>
		</section>
	);
}
Slideshow.defaultProps = {
	direction: "left",
	dragControl: false,
	startFrom: 0,
	itemAmount: 1,
	infinity: true,
	gap: 10,
	padding: 10,
	autoPlayControl: true,
	effectsOptions: {
		effectsOpacity: 1,
		effectsScale: 1,
		effectsRotate: 0,
		effectsPerspective: 1200,
		effectsHover: true,
		playOffscreen: false,
	},
	transitionControl: {
		type: "spring",
		stiffness: 200,
		damping: 40,
	},
	fadeOptions: {
		fadeContent: false,
		overflow: false,
		fadeWidth: 25,
		fadeAlpha: 0,
		fadeInset: 0,
	},
	arrowOptions: {
		showMouseControls: true,
		arrowShouldFadeIn: false,
		arrowShouldSpace: true,
		arrowFill: "rgba(0,0,0,0.2)",
		arrowSize: 40,
	},
	progressOptions: {
		showProgressDots: true,
	},
};
addPropertyControls(Slideshow, {
	slots: {
		type: ControlType.Array,
		title: "Content",
		control: {
			type: ControlType.ComponentInstance,
		},
	},
	direction: {
		type: ControlType.Enum,
		title: "Direction",
		options: ["left", "right", "top", "bottom"],
		optionIcons: [
			"direction-left",
			"direction-right",
			"direction-up",
			"direction-down",
		],
		optionTitles: ["Left", "Right", "Top", "Bottom"],
		displaySegmentedControl: true,
		defaultValue: Slideshow.defaultProps.direction,
	},
	autoPlayControl: {
		type: ControlType.Boolean,
		title: "Auto Play",
		defaultValue: true,
	},
	intervalControl: {
		type: ControlType.Number,
		title: "Interval",
		defaultValue: 1.5,
		min: 0.5,
		max: 10,
		step: 0.1,
		displayStepper: true,
		unit: "s",
		hidden: (props) => !props.autoPlayControl,
	},
	dragControl: {
		type: ControlType.Boolean,
		title: "Draggable",
		defaultValue: false,
	},
	startFrom: {
		type: ControlType.Number,
		title: "Current",
		min: 0,
		max: 10,
		displayStepper: true,
		defaultValue: Slideshow.defaultProps.startFrom,
	},
	effectsOptions: {
		type: ControlType.Object,
		title: "Effects",
		controls: {
			effectsOpacity: {
				type: ControlType.Number,
				title: "Opacity",
				defaultValue: Slideshow.defaultProps.effectsOptions.effectsOpacity,
				min: 0,
				max: 1,
				step: 0.01,
				displayStepper: true,
			},
			effectsScale: {
				type: ControlType.Number,
				title: "Scale",
				defaultValue: Slideshow.defaultProps.effectsOptions.effectsScale,
				min: 0,
				max: 1,
				step: 0.01,
				displayStepper: true,
			},
			effectsPerspective: {
				type: ControlType.Number,
				title: "Perspective",
				defaultValue: Slideshow.defaultProps.effectsOptions.effectsPerspective,
				min: 200,
				max: 2e3,
				step: 1,
			},
			effectsRotate: {
				type: ControlType.Number,
				title: "Rotate",
				defaultValue: Slideshow.defaultProps.effectsOptions.effectsRotate,
				min: -180,
				max: 180,
				step: 1,
			},
			effectsHover: {
				type: ControlType.Boolean,
				title: "On Hover",
				enabledTitle: "Play",
				disabledTitle: "Pause",
				defaultValue: Slideshow.defaultProps.effectsOptions.effectsHover,
			},
			playOffscreen: {
				type: ControlType.Boolean,
				title: "Offscreen",
				enabledTitle: "Play",
				disabledTitle: "Pause",
				defaultValue: Slideshow.defaultProps.effectsOptions.playOffscreen,
			},
		},
	},
	alignment: {
		type: ControlType.Enum,
		title: "Align",
		options: ["flex-start", "center", "flex-end"],
		optionIcons: {
			direction: {
				right: ["align-top", "align-middle", "align-bottom"],
				left: ["align-top", "align-middle", "align-bottom"],
				top: ["align-left", "align-center", "align-right"],
				bottom: ["align-left", "align-center", "align-right"],
			},
		},
		defaultValue: "center",
		displaySegmentedControl: true,
	},
	itemAmount: {
		type: ControlType.Number,
		title: "Items",
		min: 1,
		max: 10,
		displayStepper: true,
		defaultValue: Slideshow.defaultProps.itemAmount,
	},
	gap: {
		type: ControlType.Number,
		title: "Gap",
		min: 0,
	},
	padding: {
		title: "Padding",
		type: ControlType.FusedNumber,
		toggleKey: "paddingPerSide",
		toggleTitles: ["Padding", "Padding per side"],
		defaultValue: 0,
		valueKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
		valueLabels: ["T", "R", "B", "L"],
		min: 0,
	},
	borderRadius: {
		type: ControlType.Number,
		title: "Radius",
		min: 0,
		max: 500,
		displayStepper: true,
		defaultValue: 0,
	},
	transitionControl: {
		type: ControlType.Transition,
		defaultValue: Slideshow.defaultProps.transitionControl,
		title: "Transition",
	},
	fadeOptions: {
		type: ControlType.Object,
		title: "Clipping",
		controls: {
			fadeContent: {
				type: ControlType.Boolean,
				title: "Fade",
				defaultValue: false,
			},
			overflow: {
				type: ControlType.Boolean,
				title: "Overflow",
				enabledTitle: "Show",
				disabledTitle: "Hide",
				defaultValue: false,
				hidden(props) {
					return props.fadeContent === true;
				},
			},
			fadeWidth: {
				type: ControlType.Number,
				title: "Width",
				defaultValue: 25,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeInset: {
				type: ControlType.Number,
				title: "Inset",
				defaultValue: 0,
				min: 0,
				max: 100,
				unit: "%",
				hidden(props) {
					return props.fadeContent === false;
				},
			},
			fadeAlpha: {
				type: ControlType.Number,
				title: "Opacity",
				defaultValue: 0,
				min: 0,
				max: 1,
				step: 0.05,
				hidden(props) {
					return props.fadeContent === false;
				},
			},
		},
	},
	arrowOptions: {
		type: ControlType.Object,
		title: "Arrows",
		controls: {
			showMouseControls: {
				type: ControlType.Boolean,
				title: "Show",
				defaultValue: Slideshow.defaultProps.arrowOptions.showMouseControls,
			},
			arrowFill: {
				type: ControlType.Color,
				title: "Fill",
				hidden: (props) => !props.showMouseControls,
				defaultValue: Slideshow.defaultProps.arrowOptions.arrowFill,
			},
			leftArrow: {
				type: ControlType.Image,
				title: "Previous",
				hidden: (props) => !props.showMouseControls,
			},
			rightArrow: {
				type: ControlType.Image,
				title: "Next",
				hidden: (props) => !props.showMouseControls,
			},
			arrowSize: {
				type: ControlType.Number,
				title: "Size",
				min: 0,
				max: 200,
				displayStepper: true,
				defaultValue: Slideshow.defaultProps.arrowOptions.arrowSize,
				hidden: (props) => !props.showMouseControls,
			},
			arrowRadius: {
				type: ControlType.Number,
				title: "Radius",
				min: 0,
				max: 500,
				defaultValue: 40,
				hidden: (props) => !props.showMouseControls,
			},
			arrowShouldFadeIn: {
				type: ControlType.Boolean,
				title: "Fade In",
				defaultValue: false,
				hidden: (props) => !props.showMouseControls,
			},
			arrowShouldSpace: {
				type: ControlType.Boolean,
				title: "Distance",
				enabledTitle: "Space",
				disabledTitle: "Group",
				defaultValue: Slideshow.defaultProps.arrowOptions.arrowShouldSpace,
				hidden: (props) => !props.showMouseControls,
			},
			arrowPosition: {
				type: ControlType.Enum,
				title: "Position",
				options: [
					"auto",
					"top-left",
					"top-mid",
					"top-right",
					"bottom-left",
					"bottom-mid",
					"bottom-right",
				],
				optionTitles: [
					"Center",
					"Top Left",
					"Top Middle",
					"Top Right",
					"Bottom Left",
					"Bottom Middle",
					"Bottom Right",
				],
				hidden: (props) => !props.showMouseControls || props.arrowShouldSpace,
			},
			arrowPadding: {
				type: ControlType.Number,
				title: "Inset",
				min: -100,
				max: 100,
				defaultValue: 20,
				displayStepper: true,
				hidden: (props) => !props.showMouseControls || !props.arrowShouldSpace,
			},
			arrowPaddingTop: {
				type: ControlType.Number,
				title: "Top",
				min: -500,
				max: 500,
				defaultValue: 0,
				displayStepper: true,
				hidden: (props) =>
					!props.showMouseControls ||
					props.arrowShouldSpace ||
					props.arrowPosition === "auto" ||
					props.arrowPosition === "bottom-mid" ||
					props.arrowPosition === "bottom-left" ||
					props.arrowPosition === "bottom-right",
			},
			arrowPaddingBottom: {
				type: ControlType.Number,
				title: "Bottom",
				min: -500,
				max: 500,
				defaultValue: 0,
				displayStepper: true,
				hidden: (props) =>
					!props.showMouseControls ||
					props.arrowShouldSpace ||
					props.arrowPosition === "auto" ||
					props.arrowPosition === "top-mid" ||
					props.arrowPosition === "top-left" ||
					props.arrowPosition === "top-right",
			},
			arrowPaddingRight: {
				type: ControlType.Number,
				title: "Right",
				min: -500,
				max: 500,
				defaultValue: 0,
				displayStepper: true,
				hidden: (props) =>
					!props.showMouseControls ||
					props.arrowShouldSpace ||
					props.arrowPosition === "auto" ||
					props.arrowPosition === "top-left" ||
					props.arrowPosition === "top-mid" ||
					props.arrowPosition === "bottom-left" ||
					props.arrowPosition === "bottom-mid",
			},
			arrowPaddingLeft: {
				type: ControlType.Number,
				title: "Left",
				min: -500,
				max: 500,
				defaultValue: 0,
				displayStepper: true,
				hidden: (props) =>
					!props.showMouseControls ||
					props.arrowShouldSpace ||
					props.arrowPosition === "auto" ||
					props.arrowPosition === "top-right" ||
					props.arrowPosition === "top-mid" ||
					props.arrowPosition === "bottom-right" ||
					props.arrowPosition === "bottom-mid",
			},
			arrowGap: {
				type: ControlType.Number,
				title: "Gap",
				min: 0,
				max: 100,
				defaultValue: 10,
				displayStepper: true,
				hidden: (props) => !props.showMouseControls || props.arrowShouldSpace,
			},
		},
	},
	progressOptions: {
		type: ControlType.Object,
		title: "Dots",
		controls: {
			showProgressDots: {
				type: ControlType.Boolean,
				title: "Show",
				defaultValue: false,
			},
			dotSize: {
				type: ControlType.Number,
				title: "Size",
				min: 1,
				max: 100,
				defaultValue: 10,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsInset: {
				type: ControlType.Number,
				title: "Inset",
				min: -100,
				max: 100,
				defaultValue: 10,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsGap: {
				type: ControlType.Number,
				title: "Gap",
				min: 0,
				max: 100,
				defaultValue: 10,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsPadding: {
				type: ControlType.Number,
				title: "Padding",
				min: 0,
				max: 100,
				defaultValue: 10,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsFill: {
				type: ControlType.Color,
				title: "Fill",
				defaultValue: "#fff",
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsBackground: {
				type: ControlType.Color,
				title: "Backdrop",
				defaultValue: "rgba(0,0,0,0.2)",
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsRadius: {
				type: ControlType.Number,
				title: "Radius",
				min: 0,
				max: 200,
				defaultValue: 50,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsOpacity: {
				type: ControlType.Number,
				title: "Opacity",
				min: 0,
				max: 1,
				defaultValue: 0.5,
				step: 0.1,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsActiveOpacity: {
				type: ControlType.Number,
				title: "Current",
				min: 0,
				max: 1,
				defaultValue: 1,
				step: 0.1,
				displayStepper: true,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
			dotsBlur: {
				type: ControlType.Number,
				title: "Blur",
				min: 0,
				max: 50,
				defaultValue: 0,
				step: 1,
				hidden: (props) => !props.showProgressDots || props.showScrollbar,
			},
		},
	},
});
var containerStyle = {
	display: "flex",
	flexDirection: "row",
	width: "100%",
	height: "100%",
	maxWidth: "100%",
	maxHeight: "100%",
	placeItems: "center",
	margin: 0,
	padding: 0,
	listStyleType: "none",
	textIndent: "none",
};
var placeholderStyles = {
	display: "flex",
	width: "100%",
	height: "100%",
	placeContent: "center",
	placeItems: "center",
	flexDirection: "column",
	color: "#96F",
	background: "rgba(136, 85, 255, 0.1)",
	fontSize: 11,
	overflow: "hidden",
	padding: "20px 20px 30px 20px",
};
var emojiStyles = {
	fontSize: 32,
	marginBottom: 10,
};
var titleStyles = {
	margin: 0,
	marginBottom: 10,
	fontWeight: 600,
	textAlign: "center",
};
var subtitleStyles = {
	margin: 0,
	opacity: 0.7,
	maxWidth: 180,
	lineHeight: 1.5,
	textAlign: "center",
};
var baseButtonStyles = {
	border: "none",
	display: "flex",
	placeContent: "center",
	placeItems: "center",
	overflow: "hidden",
	background: "transparent",
	cursor: "pointer",
	margin: 0,
	padding: 0,
};
var controlsStyles = {
	display: "flex",
	justifyContent: "space-between",
	alignItems: "center",
	position: "absolute",
	pointerEvents: "none",
	userSelect: "none",
	top: 0,
	left: 0,
	right: 0,
	bottom: 0,
	border: 0,
	padding: 0,
	margin: 0,
};
var clamp = (num, min, max) => Math.min(Math.max(num, min), max);
var Slide = /* @__PURE__ */ memo(
	/* @__PURE__ */ forwardRef(function Component(props, ref) {
		const {
			slideKey,
			width,
			height,
			child,
			size,
			gap,
			wrappedValue,
			numChildren,
			childCounter,
			isCanvas,
			effects,
			effectsOpacity,
			effectsScale,
			effectsRotate,
			isHorizontal,
			isLast,
			index,
		} = props;
		const fallbackRef = useRef();
		const childOffset = (size?.item + gap) * childCounter;
		const scrollRange = [
			-size?.item,
			0,
			size?.parent - size?.item + gap,
			size?.parent,
		].map((val) => val - childOffset);
		const rotateY =
			!isCanvas &&
			useTransform(wrappedValue, scrollRange, [
				-effectsRotate,
				0,
				0,
				effectsRotate,
			]);
		const rotateX =
			!isCanvas &&
			useTransform(wrappedValue, scrollRange, [
				effectsRotate,
				0,
				0,
				-effectsRotate,
			]);
		const opacity =
			!isCanvas &&
			useTransform(wrappedValue, scrollRange, [
				effectsOpacity,
				1,
				1,
				effectsOpacity,
			]);
		const scale =
			!isCanvas &&
			useTransform(wrappedValue, scrollRange, [
				effectsScale,
				1,
				1,
				effectsScale,
			]);
		const originXorY =
			!isCanvas && useTransform(wrappedValue, scrollRange, [1, 1, 0, 0]);
		const isVisible =
			!isCanvas &&
			useTransform(
				wrappedValue,
				(latest) => latest >= scrollRange[1] && latest <= scrollRange[2],
			);
		useEffect2(() => {
			if (!isVisible) return;
			return isVisible.on("change", (newValue) => {
				const node = ref?.current ?? fallbackRef.current;
				node?.setAttribute("aria-hidden", !newValue);
			});
		}, []);
		const visibility = isCanvas
			? "visible"
			: useTransform(
					wrappedValue,
					[
						scrollRange[0] - size.viewportLength,
						mix(scrollRange[1], scrollRange[2], 0.5),
						scrollRange[3] + size.viewportLength,
					],
					["hidden", "visible", "hidden"],
				);
		const key = slideKey + "child";
		return (
			<LayoutGroup inherit={"id"} id={key}>
				<li
					style={{
						display: "contents",
					}}
					aria-hidden={index === 0 ? false : true}
				>
					{
						/* @__PURE__ */ cloneElement(child, {
							ref: ref ?? fallbackRef,
							key,
							style: {
								...child.props?.style,
								flexShrink: 0,
								userSelect: "none",
								width,
								height,
								opacity,
								scale,
								originX: isHorizontal ? originXorY : 0.5,
								originY: !isHorizontal ? originXorY : 0.5,
								rotateY: isHorizontal ? rotateY : 0,
								rotateX: !isHorizontal ? rotateX : 0,
								visibility,
							},
							layoutId: child.props.layoutId
								? child.props.layoutId + "-original-" + index
								: void 0,
						})
					}
				</li>
			</LayoutGroup>
		);
	}),
);
var Dot = /* @__PURE__ */ memo(function Dot2({
	selectedOpacity,
	opacity,
	total,
	index,
	wrappedIndex,
	wrappedIndexInverted,
	dotStyle: dotStyle2,
	buttonStyle,
	gap,
	padding,
	isHorizontal,
	isInverted,
	...props
}) {
	let isSelected = wrappedIndex === index;
	if (isInverted) {
		isSelected = Math.abs(wrappedIndexInverted) === index;
	}
	const inlinePadding = gap / 2;
	const top = !isHorizontal && index > 0 ? inlinePadding : padding;
	const bottom = !isHorizontal && index !== total - 1 ? inlinePadding : padding;
	const right = isHorizontal && index !== total - 1 ? inlinePadding : padding;
	const left = isHorizontal && index > 0 ? inlinePadding : padding;
	return (
		<button
			aria-label={`Scroll to page ${index + 1}`}
			type={"button"}
			{...props}
			style={{
				...buttonStyle,
				padding: `${top}px ${right}px ${bottom}px ${left}px`,
			}}
		>
			<motion.div
				style={{
					...dotStyle2,
				}}
				initial={false}
				animate={{
					opacity: isSelected ? selectedOpacity : opacity,
				}}
				transition={{
					duration: 0.3,
				}}
			/>
		</button>
	);
});
var dotsContainerStyle = {
	display: "flex",
	placeContent: "center",
	placeItems: "center",
	overflow: "hidden",
	position: "absolute",
	pointerEvents: "auto",
};
var dotStyle = {
	borderRadius: "50%",
	background: "white",
	cursor: "pointer",
	border: "none",
	placeContent: "center",
	placeItems: "center",
	padding: 0,
};

// /:https://framerusercontent.com/modules/6Hiv3ed5bTsKRsiNNmo7/YEAJWjvvZXfXdnfaBDPl/SJXSykrde.js
var StaticHeaderX1Fonts = getFonts(stdin_default);
var SlideshowFonts = getFonts(Slideshow);
var cycleOrder = ["slkOmBvZb", "xBkkFpJY2"];
var serializationHash = "framer-DqR7o";
var variantClassNames = {
	slkOmBvZb: "framer-v-1i7r6ds",
	xBkkFpJY2: "framer-v-14ub2jd",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "slkOmBvZb",
	Mobile: "xBkkFpJY2",
};
var getProps = ({
	backgroundColour1,
	backgroundColour2,
	backgroundColour3,
	height,
	id,
	width,
	...props
}) => {
	return {
		...props,
		imh_kmDLE:
			backgroundColour1 ??
			props.imh_kmDLE ??
			"var(--token-ec739675-353b-4bcc-a4b5-591586bda897, rgb(119, 149, 226))",
		KdwTH1pfy:
			backgroundColour2 ??
			props.KdwTH1pfy ??
			"var(--token-4d34ddf6-401e-4fb8-a0b9-06dfe2616683, rgb(152, 89, 216))",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "slkOmBvZb",
		Xr88wZ0Qi:
			backgroundColour3 ??
			props.Xr88wZ0Qi ??
			"var(--token-3dbe97d3-5f9e-42f3-9e48-066b84497514, rgb(221, 249, 165))",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		imh_kmDLE,
		KdwTH1pfy,
		Xr88wZ0Qi,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "slkOmBvZb",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "xBkkFpJY2") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "xBkkFpJY2") return true;
		return false;
	};
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1i7r6ds",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"slkOmBvZb"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								xBkkFpJY2: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1x8p3cd"}
							data-framer-name={"Content Wrap"}
							layoutDependency={layoutDependency}
							layoutId={"UFfjODQoz"}
						>
							{isDisplayed() && (
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-17q2uoo-container"}
										data-framer-name={"Slideshow Desktop"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"XUsxcrYkr-container"}
										name={"Slideshow Desktop"}
										nodeId={"XUsxcrYkr"}
										rendersWithMotion={true}
										scopeId={"SJXSykrde"}
									>
										<Slideshow
											alignment={"center"}
											arrowOptions={{
												arrowFill: "rgba(0, 0, 0, 0.2)",
												arrowGap: 10,
												arrowPadding: 20,
												arrowPaddingBottom: 0,
												arrowPaddingLeft: 0,
												arrowPaddingRight: 0,
												arrowPaddingTop: 0,
												arrowPosition: "auto",
												arrowRadius: 40,
												arrowShouldFadeIn: false,
												arrowShouldSpace: true,
												arrowSize: 40,
												showMouseControls: false,
											}}
											autoPlayControl={true}
											borderRadius={0}
											direction={"left"}
											dragControl={false}
											effectsOptions={{
												effectsHover: true,
												effectsOpacity: 1,
												effectsPerspective: 1200,
												effectsRotate: 0,
												effectsScale: 1,
												playOffscreen: false,
											}}
											fadeOptions={{
												fadeAlpha: 0,
												fadeContent: false,
												fadeInset: 0,
												fadeWidth: 25,
												overflow: false,
											}}
											gap={10}
											height={"100%"}
											id={"XUsxcrYkr"}
											intervalControl={4}
											itemAmount={1}
											layoutId={"XUsxcrYkr"}
											name={"Slideshow Desktop"}
											padding={0}
											paddingBottom={0}
											paddingLeft={0}
											paddingPerSide={false}
											paddingRight={0}
											paddingTop={0}
											progressOptions={{
												dotsActiveOpacity: 1,
												dotsBackground: "rgba(0, 0, 0, 0.2)",
												dotsBlur: 0,
												dotsFill: "rgb(255, 255, 255)",
												dotsGap: 10,
												dotsInset: 44,
												dotSize: 10,
												dotsOpacity: 0.5,
												dotsPadding: 10,
												dotsRadius: 50,
												showProgressDots: true,
											}}
											slots={[
												<ComponentViewportProvider
													height={680}
													width={"1920px"}
												>
													<SmartComponentScopedContainer
														className={"framer-1tv1kpv-container"}
														inComponentSlot={true}
														layoutDependency={layoutDependency}
														layoutId={"QacRjQGNT-container"}
														nodeId={"QacRjQGNT"}
														rendersWithMotion={true}
														scopeId={"SJXSykrde"}
													>
														{_jsx2(stdin_default, {
															BpXMhbk6U: "View Book",
															CJutSz3Ed: "",
															DcOfJkOkA:
																"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
															Eezi8h86g: true,
															gnAeTXg4S:
																"Let the magic of books begin with Mantra Lingua",
															height: "100%",
															id: "QacRjQGNT",
															imh_kmDLE,
															L_TthkWVG: "0px 36px 36px 36px",
															layoutId: "QacRjQGNT",
															style: {
																height: "100%",
																width: "100%",
															},
															ufNzYQW0V:
																"Unlock the world of words with this diverse collection of language books, crafted to enhance your linguistic skills and cultural understanding.",
															UNjskzKHW: true,
															variant: "Ebax59or2",
															vPwaC2RDW: "rgb(0, 0, 0)",
															width: "100%",
															zgYbh0hRH: false,
															ZMUpEOUrG: "d_dQwBXKY",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>,
												<ComponentViewportProvider
													height={680}
													width={"1920px"}
												>
													<SmartComponentScopedContainer
														className={"framer-d0ake8-container"}
														inComponentSlot={true}
														layoutDependency={layoutDependency}
														layoutId={"acEQR2Yjx-container"}
														nodeId={"acEQR2Yjx"}
														rendersWithMotion={true}
														scopeId={"SJXSykrde"}
													>
														{_jsx2(stdin_default, {
															BpXMhbk6U: "View Book",
															CJutSz3Ed: "",
															DcOfJkOkA:
																"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
															Eezi8h86g: true,
															gnAeTXg4S:
																"The tale of two sisters lost in a wonderland",
															height: "100%",
															id: "acEQR2Yjx",
															imh_kmDLE: KdwTH1pfy,
															L_TthkWVG: "0px 36px 36px 36px",
															layoutId: "acEQR2Yjx",
															psMvIuiGt:
																"https://framerusercontent.com/assets/xA57OXl2Rf6JcRQZrWu0Uc8a9w.mp4",
															Q7EWrRKPK: addImageAlt(
																{
																	pixelHeight: 1130,
																	pixelWidth: 2034,
																	src: "https://framerusercontent.com/images/TaMC52FF34slyJ65btlwxfvNs3c.png?width=2034&height=1130",
																	srcSet:
																		"https://framerusercontent.com/images/TaMC52FF34slyJ65btlwxfvNs3c.png?scale-down-to=512&width=2034&height=1130 512w,https://framerusercontent.com/images/TaMC52FF34slyJ65btlwxfvNs3c.png?scale-down-to=1024&width=2034&height=1130 1024w,https://framerusercontent.com/images/TaMC52FF34slyJ65btlwxfvNs3c.png?width=2034&height=1130 2034w",
																},
																"",
															),
															style: {
																height: "100%",
																width: "100%",
															},
															ufNzYQW0V:
																"Unlock the world of words with this diverse collection of language books, crafted to enhance your linguistic skills and cultural understanding.",
															UNjskzKHW: true,
															variant: "Ebax59or2",
															vPwaC2RDW: "rgb(0, 0, 0)",
															width: "100%",
															zgYbh0hRH: false,
															ZMUpEOUrG: "d_dQwBXKY",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>,
												<ComponentViewportProvider
													height={680}
													width={"1920px"}
												>
													<SmartComponentScopedContainer
														className={"framer-18thbm8-container"}
														inComponentSlot={true}
														layoutDependency={layoutDependency}
														layoutId={"lhtA4npAD-container"}
														nodeId={"lhtA4npAD"}
														rendersWithMotion={true}
														scopeId={"SJXSykrde"}
													>
														{_jsx2(stdin_default, {
															BpXMhbk6U: "View Book",
															CJutSz3Ed: "",
															DcOfJkOkA:
																"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
															Eezi8h86g: true,
															gnAeTXg4S:
																"Plunge into your beloved dragon adventure",
															height: "100%",
															id: "lhtA4npAD",
															imh_kmDLE: Xr88wZ0Qi,
															L_TthkWVG: "0px 36px 36px 36px",
															layoutId: "lhtA4npAD",
															psMvIuiGt:
																"https://framerusercontent.com/assets/ZyfLZW6dxlJC07rAGeTK2YSS8Q.mp4",
															Q7EWrRKPK: addImageAlt(
																{
																	pixelHeight: 998,
																	pixelWidth: 1408,
																	src: "https://framerusercontent.com/images/HbExoQF4Ph8bbkbPGJIMV74sL0.png?width=1408&height=998",
																	srcSet:
																		"https://framerusercontent.com/images/HbExoQF4Ph8bbkbPGJIMV74sL0.png?scale-down-to=512&width=1408&height=998 512w,https://framerusercontent.com/images/HbExoQF4Ph8bbkbPGJIMV74sL0.png?scale-down-to=1024&width=1408&height=998 1024w,https://framerusercontent.com/images/HbExoQF4Ph8bbkbPGJIMV74sL0.png?width=1408&height=998 1408w",
																},
																"",
															),
															style: {
																height: "100%",
																width: "100%",
															},
															ufNzYQW0V:
																"Unlock the world of words with this diverse collection of language books, crafted to enhance your linguistic skills and cultural understanding.",
															UNjskzKHW: true,
															variant: "Ebax59or2",
															vPwaC2RDW: "rgb(0, 0, 0)",
															width: "100%",
															zgYbh0hRH: false,
															ZMUpEOUrG: "d_dQwBXKY",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>,
											]}
											startFrom={0}
											style={{
												height: "100%",
												width: "100%",
											}}
											transitionControl={{
												damping: 40,
												delay: 0,
												mass: 1,
												stiffness: 200,
												type: "spring",
											}}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
							{isDisplayed1() && (
								<ComponentViewportProvider>
									<SmartComponentScopedContainer
										className={"framer-tk8tfe-container"}
										data-framer-name={"SlideShow Mobile"}
										isAuthoredByUser={true}
										isModuleExternal={true}
										layoutDependency={layoutDependency}
										layoutId={"Vd5FKTBRy-container"}
										name={"SlideShow Mobile"}
										nodeId={"Vd5FKTBRy"}
										rendersWithMotion={true}
										scopeId={"SJXSykrde"}
									>
										<Slideshow
											alignment={"flex-start"}
											arrowOptions={{
												arrowFill: "rgba(0, 0, 0, 0.2)",
												arrowGap: 10,
												arrowPadding: 20,
												arrowPaddingBottom: 0,
												arrowPaddingLeft: 0,
												arrowPaddingRight: 0,
												arrowPaddingTop: 0,
												arrowPosition: "auto",
												arrowRadius: 40,
												arrowShouldFadeIn: false,
												arrowShouldSpace: true,
												arrowSize: 40,
												showMouseControls: false,
											}}
											autoPlayControl={true}
											borderRadius={0}
											direction={"left"}
											dragControl={false}
											effectsOptions={{
												effectsHover: true,
												effectsOpacity: 1,
												effectsPerspective: 1200,
												effectsRotate: 0,
												effectsScale: 1,
												playOffscreen: false,
											}}
											fadeOptions={{
												fadeAlpha: 0,
												fadeContent: false,
												fadeInset: 0,
												fadeWidth: 25,
												overflow: false,
											}}
											gap={0}
											height={"100%"}
											id={"Vd5FKTBRy"}
											intervalControl={4}
											itemAmount={1}
											layoutId={"Vd5FKTBRy"}
											name={"SlideShow Mobile"}
											padding={0}
											paddingBottom={0}
											paddingLeft={0}
											paddingPerSide={false}
											paddingRight={0}
											paddingTop={0}
											progressOptions={{
												dotsActiveOpacity: 1,
												dotsBackground: "rgba(0, 0, 0, 0.2)",
												dotsBlur: 0,
												dotsFill: "rgb(255, 255, 255)",
												dotsGap: 10,
												dotsInset: 40,
												dotSize: 10,
												dotsOpacity: 0.5,
												dotsPadding: 10,
												dotsRadius: 50,
												showProgressDots: false,
											}}
											slots={[
												<ComponentViewportProvider height={680} width={"360px"}>
													<SmartComponentScopedContainer
														className={"framer-pksyyu-container"}
														inComponentSlot={true}
														layoutDependency={layoutDependency}
														layoutId={"PsFJcxRmt-container"}
														nodeId={"PsFJcxRmt"}
														rendersWithMotion={true}
														scopeId={"SJXSykrde"}
													>
														{_jsx2(stdin_default, {
															BpXMhbk6U: "View Book",
															CJutSz3Ed: "",
															DcOfJkOkA:
																"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
															Eezi8h86g: true,
															gnAeTXg4S:
																"Let the magic of books begin with Mantra Lingua",
															height: "100%",
															id: "PsFJcxRmt",
															imh_kmDLE,
															L_TthkWVG: "0px",
															layoutId: "PsFJcxRmt",
															style: {
																width: "100%",
															},
															ufNzYQW0V:
																"Unlock the world of words with this diverse collection of language books, crafted to enhance your linguistic skills and cultural understanding.",
															UNjskzKHW: true,
															variant: "m9aqTpWDo",
															vPwaC2RDW: "rgb(0, 0, 0)",
															width: "100%",
															zgYbh0hRH: true,
															ZMUpEOUrG: "d_dQwBXKY",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>,
												<ComponentViewportProvider height={680} width={"360px"}>
													<SmartComponentScopedContainer
														className={"framer-vamdey-container"}
														inComponentSlot={true}
														layoutDependency={layoutDependency}
														layoutId={"DUY4jZWkm-container"}
														nodeId={"DUY4jZWkm"}
														rendersWithMotion={true}
														scopeId={"SJXSykrde"}
													>
														{_jsx2(stdin_default, {
															BpXMhbk6U: "View Book",
															CJutSz3Ed: "",
															DcOfJkOkA:
																"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
															Eezi8h86g: true,
															gnAeTXg4S:
																"The tale of two sisters lost in a wonderland",
															height: "100%",
															id: "DUY4jZWkm",
															imh_kmDLE: KdwTH1pfy,
															L_TthkWVG: "0px",
															layoutId: "DUY4jZWkm",
															psMvIuiGt:
																"https://framerusercontent.com/assets/xA57OXl2Rf6JcRQZrWu0Uc8a9w.mp4",
															Q7EWrRKPK: addImageAlt(
																{
																	pixelHeight: 1168,
																	pixelWidth: 2092,
																	src: "https://framerusercontent.com/images/jisA9dKdAvjPSRM9qjARn7CbSlo.png?width=2092&height=1168",
																	srcSet:
																		"https://framerusercontent.com/images/jisA9dKdAvjPSRM9qjARn7CbSlo.png?scale-down-to=512&width=2092&height=1168 512w,https://framerusercontent.com/images/jisA9dKdAvjPSRM9qjARn7CbSlo.png?scale-down-to=1024&width=2092&height=1168 1024w,https://framerusercontent.com/images/jisA9dKdAvjPSRM9qjARn7CbSlo.png?scale-down-to=2048&width=2092&height=1168 2048w,https://framerusercontent.com/images/jisA9dKdAvjPSRM9qjARn7CbSlo.png?width=2092&height=1168 2092w",
																},
																"",
															),
															style: {
																width: "100%",
															},
															ufNzYQW0V:
																"Unlock the world of words with this diverse collection of language books, crafted to enhance your linguistic skills and cultural understanding.",
															UNjskzKHW: true,
															variant: "m9aqTpWDo",
															vPwaC2RDW: "rgb(0, 0, 0)",
															width: "100%",
															zgYbh0hRH: true,
															ZMUpEOUrG: "d_dQwBXKY",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>,
												<ComponentViewportProvider height={680} width={"360px"}>
													<SmartComponentScopedContainer
														className={"framer-yxymc4-container"}
														inComponentSlot={true}
														layoutDependency={layoutDependency}
														layoutId={"Wxb0MeyXD-container"}
														nodeId={"Wxb0MeyXD"}
														rendersWithMotion={true}
														scopeId={"SJXSykrde"}
													>
														{_jsx2(stdin_default, {
															BpXMhbk6U: "View Book",
															CJutSz3Ed: "",
															DcOfJkOkA:
																"var(--token-9a5e7ff9-a6fa-490a-8297-eb2aa864e5ad, rgb(0, 0, 0))",
															Eezi8h86g: true,
															gnAeTXg4S:
																"Plunge into your beloved dragon adventure",
															height: "100%",
															id: "Wxb0MeyXD",
															imh_kmDLE: Xr88wZ0Qi,
															L_TthkWVG: "0px",
															layoutId: "Wxb0MeyXD",
															psMvIuiGt:
																"https://framerusercontent.com/assets/ZyfLZW6dxlJC07rAGeTK2YSS8Q.mp4",
															Q7EWrRKPK: addImageAlt(
																{
																	pixelHeight: 1108,
																	pixelWidth: 2044,
																	src: "https://framerusercontent.com/images/bjADZCJoChI7fRX3VAicoKFe9xE.png?width=2044&height=1108",
																	srcSet:
																		"https://framerusercontent.com/images/bjADZCJoChI7fRX3VAicoKFe9xE.png?scale-down-to=512&width=2044&height=1108 512w,https://framerusercontent.com/images/bjADZCJoChI7fRX3VAicoKFe9xE.png?scale-down-to=1024&width=2044&height=1108 1024w,https://framerusercontent.com/images/bjADZCJoChI7fRX3VAicoKFe9xE.png?width=2044&height=1108 2044w",
																},
																"",
															),
															style: {
																width: "100%",
															},
															ufNzYQW0V:
																"Unlock the world of words with this diverse collection of language books, crafted to enhance your linguistic skills and cultural understanding.",
															UNjskzKHW: true,
															variant: "m9aqTpWDo",
															vPwaC2RDW: "rgb(0, 0, 0)",
															width: "100%",
															zgYbh0hRH: true,
															ZMUpEOUrG: "d_dQwBXKY",
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>,
											]}
											startFrom={0}
											style={{
												height: "100%",
												width: "100%",
											}}
											transitionControl={{
												damping: 40,
												delay: 0,
												mass: 1,
												stiffness: 200,
												type: "spring",
											}}
											width={"100%"}
										/>
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							)}
						</motion2.div>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup2>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-DqR7o.framer-1msvano, .framer-DqR7o .framer-1msvano { display: block; }",
	".framer-DqR7o.framer-1i7r6ds { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: wrap; gap: 0px; height: 636px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 1920px; }",
	".framer-DqR7o .framer-1x8p3cd { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-DqR7o .framer-17q2uoo-container { flex: none; height: 636px; position: relative; width: 100%; }",
	".framer-DqR7o .framer-1tv1kpv-container, .framer-DqR7o .framer-d0ake8-container, .framer-DqR7o .framer-18thbm8-container { height: 680px; position: relative; width: 1920px; }",
	".framer-DqR7o .framer-tk8tfe-container { flex: none; height: 1064px; position: relative; width: 100%; }",
	".framer-DqR7o .framer-pksyyu-container, .framer-DqR7o .framer-vamdey-container, .framer-DqR7o .framer-yxymc4-container { height: auto; position: relative; width: 360px; }",
	".framer-DqR7o.framer-v-14ub2jd.framer-1i7r6ds { align-content: center; align-items: center; flex-direction: column; height: min-content; width: 360px; }",
	".framer-DqR7o.framer-v-14ub2jd .framer-1x8p3cd { flex: none; width: 100%; }",
];
var FramerSJXSykrde = withCSS(Component2, css, "framer-DqR7o");
var stdin_default2 = FramerSJXSykrde;
FramerSJXSykrde.displayName = "slidingHeaderx3";
FramerSJXSykrde.defaultProps = {
	height: 636,
	width: 1920,
};
addPropertyControls2(FramerSJXSykrde, {
	variant: {
		options: ["slkOmBvZb", "xBkkFpJY2"],
		optionTitles: ["Desktop", "Mobile"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	imh_kmDLE: {
		defaultValue:
			'var(--token-ec739675-353b-4bcc-a4b5-591586bda897, rgb(119, 149, 226)) /* {"name":"200"} */',
		description: "",
		title: "Background - Colour - 1",
		type: ControlType2.Color,
	},
	KdwTH1pfy: {
		defaultValue:
			'var(--token-4d34ddf6-401e-4fb8-a0b9-06dfe2616683, rgb(152, 89, 216)) /* {"name":"300"} */',
		description: "",
		title: "Background - Colour - 2",
		type: ControlType2.Color,
	},
	Xr88wZ0Qi: {
		defaultValue:
			'var(--token-3dbe97d3-5f9e-42f3-9e48-066b84497514, rgb(221, 249, 165)) /* {"name":"100"} */',
		description: "",
		title: "Background - Colour - 3",
		type: ControlType2.Color,
	},
});
addFonts(
	FramerSJXSykrde,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...StaticHeaderX1Fonts,
		...SlideshowFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:sliding-headerx3
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "fpVdyfuAw",
		name: "Chinese",
		slug: "yue",
		code: "yue-Hant-HK",
	},
];
var defaultResponsiveVariants = {
	base: "xBkkFpJY2",
	"2xl": "slkOmBvZb",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SlidingHeaderx3FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var sliding_headerx3_default = ComponentWithRoot;
export { sliding_headerx3_default as default };
