// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 826eadcfe2264c6d "Mantra Lingua", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'yue'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * orientation?: 'Portrait' | 'Landscape' // Orientation
 * frontImage?: {src: string, srcSet?: string, alt?: string} // Front Image
 * backImage?: {src: string, srcSet?: string, alt?: string} // Back Image
 * flipDirection?: 'Horizontal' | 'Vertical' // Flip Direction
 * tiltIntensity?: number // Tilt Intensity
 * shadowIntensity?: number // Shadow Intensity
 * shadowColor?: string // Shadow Color
 * borderRadius?: number // Border Radius
 * cardWidth?: number // Card Width
 * cardHeight?: number // Card Height
 * backgroundColor?: string // Background Color
}} Props

 */
import { TiltCard } from "./chunks/chunk-2OT4HGUT.js";
import { routes } from "./chunks/chunk-74LWP5VC.js";

// virtual:tilt-card
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "fpVdyfuAw",
		name: "Chinese",
		slug: "yue",
		code: "yue-Hant-HK",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<TiltCard {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TiltCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={TiltCard}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, TiltCard);
var tilt_card_default = ComponentWithRoot;
export { tilt_card_default as default };
