// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 826eadcfe2264c6d "Mantra Lingua", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'yue'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * subtitle?: string // Subtitle
 * buttonText?: string // Button Text
 * errorMessage?: string // Error Message
 * onVerify?: Function // On Verify
 * background?: string // Background
 * inputBackground?: string // Input Background
 * inputBorder?: string // Input Border
 * inputFocus?: string // Input Focus
 * textColor?: string // Text Color
 * buttonActive?: string // Button Active
 * buttonInactive?: string // Button Inactive
 * buttonText?: string // Button Text
 * padding?: undefined // Padding
 * titleFont?: undefined // Title Font
 * subtitleFont?: undefined // Subtitle Font
 * inputFont?: undefined // Input Font
 * buttonFont?: undefined // Button Font
 * borderRadius?: number // Border Radius
 * inputSpacing?: number // Input Spacing
}} Props

 */
import { VerificationCodeInput } from "./chunks/chunk-X5RIED6B.js";
import { routes } from "./chunks/chunk-74LWP5VC.js";

// virtual:verification-code-input
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "fpVdyfuAw",
		name: "Chinese",
		slug: "yue",
		code: "yue-Hant-HK",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<VerificationCodeInput {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders VerificationCodeInputFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"826eadcfe2264c6d2229fd04fa5eb333deb0eadb9ffdc700c653a9ec57b56ae2"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={VerificationCodeInput}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, VerificationCodeInput);
var verification_code_input_default = ComponentWithRoot;
export { verification_code_input_default as default };
